#pragma execution_character_set("utf-8")
#ifndef Visindigo_General_AUTO_VERSION_h
#define Visindigo_General_AUTO_VERSION_h

// This file is auto generated by Visindigo/pytools/AutoVersionFromGIT.py
// Do not modify this file manually
#define Visindigo_VERSION_BUILD 184
#define Visindigo_VERSION_STRING "0.16.0.184"
#define Visindigo_VERSION_BUILD_DATE "2026-08-12"
#define Visindigo_VERSION_BUILD_TIME "23:52:23"
#define Visindigo_VERSION_NICKNAME "EA TP3"

#endif // Visindigo_General_AUTO_VERSION_h
