#pragma execution_character_set("utf-8")
#ifndef Visindigo_General_AUTO_VERSION_h
#define Visindigo_General_AUTO_VERSION_h

// This file is auto generated by Visindigo/pytools/AutoVersionFromGIT.py
// Do not modify this file manually
#define Visindigo_VERSION_BUILD 172
#define Visindigo_VERSION_BUILD_DATE "2026-08-03"
#define Visindigo_VERSION_BUILD_TIME "11:12:31"
#define Visindigo_VERSION_NICKNAME "EA TP2"

#endif // Visindigo_General_AUTO_VERSION_h
