#ifdef _MSC_VER
#pragma execution_character_set("utf-8")
#endif
#ifndef Visindigo_General_private_AUTO_VERSION_h
#define Visindigo_General_private_AUTO_VERSION_h

// This file is auto generated by Visindigo/pytools/AutoVersionFromGIT.py
// Do not modify this file manually
#define Visindigo_VERSION_BUILD 215
#define Visindigo_VERSION_STRING "0.17.0.215"
#define Visindigo_VERSION_BUILD_DATE "2026-09-03"
#define Visindigo_VERSION_BUILD_TIME "19:49:54"
#define Visindigo_VERSION_NICKNAME "EA TP1"

#endif // Visindigo_General_private_AUTO_VERSION_h
