#pragma execution_character_set("utf-8")
#pragma once
// This file is auto generated by Visindigo/pytools/AutoVersionFromGIT.py
// Do not modify this file manually
#define Visindigo_VERSION_BUILD 39
#define Visindigo_VERSION_BUILD_DATE "2025-08-04"
#define Visindigo_VERSION_BUILD_TIME "22:53:31"
#define Visindigo_VERSION_NICKNAME "Technical Preview 5"
