#pragma execution_character_set("utf-8")
#pragma once
// This file is auto generated by Visindigo/pytools/AutoVersionFromGIT.py
// Do not modify this file manually
#define Visindigo_VERSION_BUILD 44
#define Visindigo_VERSION_BUILD_DATE "2025-09-17"
#define Visindigo_VERSION_BUILD_TIME "00:47:46"
#define Visindigo_VERSION_NICKNAME "Technical Preview 5"
