#pragma execution_character_set("utf-8")
#pragma once
// This file is auto generated by Visindigo/pytools/AutoVersionFromGIT.py
// Do not modify this file manually
#define Visindigo_VERSION_BUILD 46
#define Visindigo_VERSION_BUILD_DATE "2025-09-19"
#define Visindigo_VERSION_BUILD_TIME "20:15:08"
#define Visindigo_VERSION_NICKNAME "Technical Preview 6"
