/*
	Visindigo Project Full AI Generated Declaration

	1. This file was entirely generated by AI. There was almost no human
	   involvement in the design of its API and implementation.
	2. Provided that the usage characteristics of the program corresponding
	   to this code are not substantially changed, anyone is free to make
	   fundamental modifications to this code.
	3. This code does not guarantee implementation consistency across
	   generations; it only guarantees that the corresponding program
	   features remain basically stable.
*/
#include <QtCore/qbytearray.h>
#include <QtCore/qjsonarray.h>
#include <QtCore/qjsondocument.h>
#include <QtCore/qjsonobject.h>
#include <QtCore/qjsonvalue.h>
#include <QtCore/qlist.h>
#include <QtCore/qmap.h>
#include <QtCore/qregularexpression.h>
#include <QtCore/qstring.h>
#include <QtCore/qstringlist.h>
#include <QtCore/quuid.h>
#include <QtCore/qurl.h>
#include <Network/HttpCenter.h>
#include <Network/HttpRequest.h>
#include <Network/HttpTypes.h>
#include <Network/SSERequest.h>
#include <Utility/JsonConfig.h>
#include "Agent/Center.h"
#include "Agent/Dialog.h"
#include "Agent/Function.h"
#include "Agent/MCP.h"
#include "Agent/Model.h"
#include "Agent/Prompt.h"
#include "Agent/Provider.h"
#include "Agent/Skill.h"
#include "Agent/private/Center_p.h"
#include "Agent/private/Dialog_p.h"

namespace Visindigo::Agent {
	/*!
		\enum Visindigo::Agent::Message::Role
		\since Visindigo 0.17.0

		消息在对话中扮演的角色。

		\value System 系统提示。通常由 \l Dialog::run() 自动生成，不需要手工添加。
		\value User 用户输入。
		\value Assistant 模型输出。
		\value Tool 工具执行结果。必须同时设置 \l{Message::setToolCallID()}，
			否则服务端无法把它对应回某次调用。
		\value Prompt 由 \l Prompt::render() 生成的模板消息。
		\note \l Role::Prompt 只在本地区分"用户手打的"与"模板生成的"，发往服务端时
			与 \l Role::User 同为 \c user 角色。
	*/

	/*!
		\class Visindigo::Agent::Message
		\inheaderfile Agent/Dialog.h
		\since Visindigo 0.17.0
		\inmodule Visindigo
		\brief 对话中的一条消息.

		Message 是纯值类型，可以自由拷贝与序列化。它同时承担两种用途：一是请求体
		里的 \c messages 数组元素，二是本地会话记录。两者字段基本重合，唯一的
		差别是 \l{getToolCalls()}——它保存的是原始 JSON 数组文本，只在请求体重
		逐字回传，本地展示时不使用。
	*/

	/*!
		\since Visindigo 0.17.0

		构造一条空消息，角色默认为 \l{Role::User}。
	*/
	Message::Message() {
		d = new MessagePrivate();
	}

	/*!
		\since Visindigo 0.17.0

		以角色与内容构造消息。

		\a role 消息角色。
		\a content 消息正文。
	*/
	Message::Message(Role role, const QString& content) {
		d = new MessagePrivate();
		d->RoleName = role;
		d->Content = content;
	}

	VICopyable_Impl(Message);
	VIMoveable_Impl(Message);

	/*!
		\since Visindigo 0.17.0
	*/
	Message::~Message() {
		delete d;
	}

	/*!
		\since Visindigo 0.17.0

		设置角色。

		\a role 新的角色。
	*/
	Message& Message::setRole(Role role) {
		d->RoleName = role;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		设置正文。

		\a content 新的正文文本。
	*/
	Message& Message::setContent(const QString& content) {
		d->Content = content;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		设置发送者名称。

		\note 这个字段在标准协议里是可选的，多数服务端会忽略它。它在本模块中的
		实际用途是记录模板消息来自哪个 \l{Prompt}，以及工具结果来自哪个工具。

		\a name 发送者名称；模板消息可填模板名，工具结果可填工具名。
	*/
	Message& Message::setName(const QString& name) {
		d->Name = name;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		设置本条消息对应的工具调用标识。仅对 \l Role::Tool 有意义。

		\a id 必须与模型给出的调用标识完全一致，包括大小写。服务端按它把结果配回
		具体的调用，配不上就会拒绝整条请求。
	*/
	Message& Message::setToolCallID(const QString& id) {
		d->ToolCallID = id;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		设置本条助手消息请求的工具调用，内容为原始 JSON 数组文本。

		这里刻意不收结构化数据：字段只要原样回传就不会出错，一旦解析再重新拼装，
		就得自己保证每个字段的形态与收到的完全一致，反而多出一处可能出错的地方。

		\warning 这段文本会被原样放进请求体。构造它的人应当确保它来自服务端响应，
		而不是用户输入。

		\a rawJsonArray 服务端给出的工具调用数组的原始 JSON 文本。
	*/
	Message& Message::setToolCalls(const QString& rawJsonArray) {
		d->ToolCalls = rawJsonArray;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		设置本条助手消息的思考内容。

		推理模型会先输出一段思考再生出回答，这段思考被单独存下来，因为它属于这一次
		回答本身：不看它，就无法理解模型当时为什么做出那个结论，事后重读对话时
		只剩下一个看不出理由的结果。

		\note 它永远不会被发回服务端。思考是模型的中间产物，不是它已经说出口的话，
		把上一轮的思考当作助手内容回传，会让模型以为自己已经给出过那个结论，
		从而在下一轮里跳过论证直接引用它。

		\a reasoning 本轮的思考内容。
	*/
	Message& Message::setReasoning(const QString& reasoning) {
		d->Reasoning = reasoning;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		返回角色。
	*/
	Message::Role Message::getRole() const {
		return d->RoleName;
	}

	/*!
		\since Visindigo 0.17.0

		返回正文。
	*/
	QString Message::getContent() const {
		return d->Content;
	}

	/*!
		\since Visindigo 0.17.0

		返回发送者名称。
	*/
	QString Message::getName() const {
		return d->Name;
	}

	/*!
		\since Visindigo 0.17.0

		返回本条消息对应的工具调用标识。
	*/
	QString Message::getToolCallID() const {
		return d->ToolCallID;
	}

	/*!
		\since Visindigo 0.17.0

		返回助手消息请求的工具调用，形态为原始 JSON 数组文本。
	*/
	QString Message::getToolCalls() const {
		return d->ToolCalls;
	}

	/*!
		\since Visindigo 0.17.0

		返回本条助手消息的思考内容；非推理模型或未记录时为空串。
	*/
	QString Message::getReasoning() const {
		return d->Reasoning;
	}

	/*!
		\since Visindigo 0.17.0

		判断消息是否既没有正文也没有工具调用。

		\note 一条只有工具调用的助手消息不算空：它的正文可能为空，但携带的调用
		信息才是重点，把它当作空消息丢掉会让下一轮的请求缺一条必要的前置消息。

		return 消息是否既没有正文也没有工具调用。
	*/
	bool Message::isEmpty() const {
		return d->Content.isEmpty() and d->ToolCalls.isEmpty();
	}

	/*!
		\since Visindigo 0.17.0

		序列化为 JSON 对象，角色以字符串保存。
	*/
	Visindigo::Utility::JsonConfig Message::toJson() const {
		Visindigo::Utility::JsonConfig config;
		switch (d->RoleName) {
		case Role::System: config.setString("role", "system"); break;
		case Role::User: config.setString("role", "user"); break;
		case Role::Assistant: config.setString("role", "assistant"); break;
		case Role::Tool: config.setString("role", "tool"); break;
		case Role::Prompt: config.setString("role", "prompt"); break;
		}
		config.setString("content", d->Content);
		if (not d->Name.isEmpty()) {
			config.setString("name", d->Name);
		}
		if (not d->ToolCallID.isEmpty()) {
			config.setString("toolCallId", d->ToolCallID);
		}
		if (not d->ToolCalls.isEmpty()) {
			config.setString("toolCalls", d->ToolCalls);
		}
		if (not d->Reasoning.isEmpty()) {
			config.setString("reasoning", d->Reasoning);
		}
		return config;
	}

	/*!
		\since Visindigo 0.17.0

		从 JSON 对象恢复。

		无法识别的角色字符串会退回 \l{Role::User}，因为把一条消息当作用户输入
		与模型继续对话，比丢掉它造成的破坏更小。

		\a json 已解析的 JSON 对象。

		return 是否读到了可识别的角色。
	*/
	bool Message::fromJson(const Visindigo::Utility::JsonConfig& json) {
		const QString role = json.getString("role");
		bool known = true;
		if (role == "system") {
			d->RoleName = Role::System;
		}
		else if (role == "user") {
			d->RoleName = Role::User;
		}
		else if (role == "assistant") {
			d->RoleName = Role::Assistant;
		}
		else if (role == "tool") {
			d->RoleName = Role::Tool;
		}
		else if (role == "prompt") {
			d->RoleName = Role::Prompt;
		}
		else {
			d->RoleName = Role::User;
			known = false;
		}
		d->Content = json.getString("content");
		d->Name = json.getString("name");
		d->ToolCallID = json.getString("toolCallId");
		d->ToolCalls = json.getString("toolCalls");
		d->Reasoning = json.getString("reasoning");
		return known;
	}

	/*!
		\class Visindigo::Agent::Dialog
		\inheaderfile Agent/Dialog.h
		\since Visindigo 0.17.0
		\inmodule Visindigo
		\brief 一次完整的对话及其执行入口.

		Dialog 持有消息列表、这次对话可用的 Skill / MCP / Function / Prompt，
		以及要用哪个 Provider 的哪个模型。\l run() 会把当前消息发出去，把流式
		返回的内容通过信号吐出，并在模型请求调用工具时自动执行工具、把结果
		回灌后继续请求，直到模型给出最终答复。

		每个 Dialog 在构造时获得一个 UUID，之后不再改变——它同时是 Center 里的
		索引键和会话记录里的标识。\l setBranchFromID() 记录"本条对话是从哪条
		分出来的"，重新生成回答时新对话会指向被它取代的那条，于是分支关系自然而
		然地留在数据里，不需要额外维护一棵树。

		\l run() 上的配置优先级是：本 Dialog 上挂的 Skill / MCP / Function / Prompt
		覆盖 Center 上的同名全局配置。这让人可以给某次特殊对话临时挂一个技能，
		而不必先去全局配置里删掉同名项。

		\note Dialog 的所有权属于 \l{Center}。请通过 \l{Center::removeDialog()} 销毁，
		直接 \c delete 会让 Center 的表里留下一个悬空指针。
	*/

	/*!
		\fn void Visindigo::Agent::Dialog::messageAppended(qint32 index)
		\since Visindigo 0.17.0

		新增了一条消息。\a index 是它在 \l{getMessages()} 中的下标。

		\note 只报下标不报内容，是为了让监听方自己去取：同一条消息在发出信号之后
		仍可能被继续改写，传一份副本出去反而会造成"界面上的和实际存的不一样"。
	*/

	/*!
		\fn void Visindigo::Agent::Dialog::streamBegan()
		\since Visindigo 0.17.0

		开始一轮生成。这一轮的增量从此刻开始到达。
	*/

	/*!
		\fn void Visindigo::Agent::Dialog::streamDelta(const QString& delta)
		\since Visindigo 0.17.0

		回答正文的增量。

		\a delta 本次新增的正文片段。
	*/

	/*!
		\fn void Visindigo::Agent::Dialog::streamReasoning(const QString& delta)
		\since Visindigo 0.17.0

		思考内容的增量。仅推理模型会发出。

		\note 它与 \l{streamDelta} 是两条独立的通道：思考不属于回答，不会进入下一轮
		请求，但会随 \l{Message::setReasoning()} 存进对应的助手消息。

		\a delta 本次新增的思考片段。
	*/

	/*!
		\fn void Visindigo::Agent::Dialog::streamEnded(const QString& fullContent)
		\since Visindigo 0.17.0

		这一轮生成结束。\a fullContent 是完整的回答正文。

		出现工具调用时，一轮结束后会立刻开始下一轮，因此一次 \l run() 可能触发
		多次 \l{streamBegan} 与 \l{streamEnded}。
	*/

	/*!
		\fn void Visindigo::Agent::Dialog::runFailed(const QString& message)
		\since Visindigo 0.17.0

		执行失败。\a message 是可以直接展示给用户的原因描述。

		\note 失败之后不会再有 \l{streamEnded}，因此界面上必须两个信号都接，否则
		"正在生成"的状态会一直挂着消不掉。
	*/

	/*!
		\since Visindigo 0.17.0

		构造一个空对话，并立即分配一个新的 UUID。
	*/
	Dialog::Dialog() : QObject() {
		d = new DialogPrivate();
		d->q = this;
		d->Id = QUuid::createUuid().toString(QUuid::WithoutBraces);
	}

	/*!
		\since Visindigo 0.17.0

		中止仍在进行的请求，并释放本对话独占的函数对象。

		\warning 这里不会把自己从 Center 的表中摘除。销毁对话请调用
		\l{Center::removeDialog()}。
	*/
	Dialog::~Dialog() {
		d->abortPendingReply();
		for (Function* function : d->Functions) {
			delete function;
		}
		d->Functions.clear();
		delete d;
	}

	/*!
		\since Visindigo 0.17.0

		追加一条消息，并发出 \l{messageAppended()}。

		\a message 要追加的消息。
	*/
	Dialog& Dialog::appendMessage(const Message& message) {
		d->Messages.append(message);
		emit messageAppended(d->Messages.size() - 1);
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		以角色与内容追加一条消息的便捷重载。
	*/
	Dialog& Dialog::appendMessage(Message::Role role, const QString& content) {
		return appendMessage(Message(role, content));
	}

	/*!
		\since Visindigo 0.17.0

		清空全部消息，但保留技能、工具与模型配置。
	*/
	Dialog& Dialog::clearMessages() {
		d->Messages.clear();
		d->StreamingBuffer.clear();
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		返回全部消息，按时间顺序。
	*/
	QList<Message> Dialog::getMessages() const {
		return d->Messages;
	}

	/*!
		\since Visindigo 0.17.0

		返回最后一条消息；没有任何消息时返回空消息。
	*/
	Message Dialog::getLastMessage() const {
		if (d->Messages.isEmpty()) {
			return Message();
		}
		return d->Messages.last();
	}

	/*!
		\since Visindigo 0.17.0

		返回消息条数。
	*/
	qint32 Dialog::getMessageCount() const {
		return static_cast<qint32>(d->Messages.size());
	}

	/*!
		\since Visindigo 0.17.0

		只保留前 \a messageCount 条消息，删除其余部分。

		\a messageCount 大于当前条数时什么也不做；为 \c 0 时清空全部消息。
	*/
	Dialog& Dialog::truncateTo(qint32 messageCount) {
		if (messageCount < 0) {
			return *this;
		}
		while (d->Messages.size() > messageCount) {
			d->Messages.removeLast();
		}
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		返回最后一条助手消息的下标；没有助手消息时返回 \c -1。

		下标可以直接交给 \l{truncateTo()}：保留到这个下标为止，就恰好丢掉了那次
		回答以及之后的所有内容，这正是"重新生成"需要的前置状态。
	*/
	qint32 Dialog::findLastAssistantMessage() const {
		for (qsizetype i = d->Messages.size() - 1; i >= 0; --i) {
			if (d->Messages.at(i).getRole() == Message::Role::Assistant) {
				return static_cast<qint32>(i);
			}
		}
		return -1;
	}

	/*!
		\since Visindigo 0.17.0

		把消息与配置复制到另一条对话。

		复制的内容包括消息列表、Skill / MCP / Prompt、Provider 与模型选择、
		能力要求。目标对话保留自己的 id，这样可以先看一份草稿再决定是否让它
		取代原对话。

		\note 函数对象不会被复制。\l Function 是带有独占所有权的接口，无法深拷贝，
		共享指针又会在两边析构时重复释放；需要跨对话复用的工具请注册到 Center 上，
		那里本来就是通过 id 解析的。目标对话自己原有的函数保持不变。

		\a target 复制目标对话。

		return 复制是否成功；目标为空或就是自身时返回 false。
	*/
	bool Dialog::copyTo(Dialog* target) const {
		if (target == nullptr or target == this) {
			return false;
		}
		target->d->Messages = d->Messages;
		target->d->Skills = d->Skills;
		target->d->MCPs = d->MCPs;
		target->d->Prompts = d->Prompts;
		target->d->ProviderId = d->ProviderId;
		target->d->ModelId = d->ModelId;
		target->d->CapabilityRequirement = d->CapabilityRequirement;
		return true;
	}

	/*!
		\since Visindigo 0.17.0

		开始接收一条助手消息：清空流式缓冲并发出 \l{streamBegan()}。

		流式接收由 \l run() 自行驱动，手工调用它只适用于自己实现了传输、
		想复用本对话渲染逻辑的场景。
	*/
	void Dialog::beginAssistantMessage() {
		d->StreamingBuffer.clear();
		d->ReasoningBuffer.clear();
		d->Streaming = true;
		emit streamBegan();
	}

	/*!
		\since Visindigo 0.17.0

		追加一段流式增量，并发出 \l{streamDelta()}。

		\note 增量是模型输出的碎片，可能从多字节字符或 Markdown 语法的中途切开，
		因此不要对单个增量做解析，只能对累积结果做。

		\a delta 本次新增的正文片段。
	*/
	void Dialog::appendDelta(const QString& delta) {
		if (not d->Streaming) {
			return;
		}
		d->StreamingBuffer += delta;
		emit streamDelta(delta);
	}

	/*!
		\since Visindigo 0.17.0

		结束流式接收：把缓冲内容作为一条助手消息追加到对话末尾，发出
		\l{messageAppended()} 与 \l{streamEnded()}。

		缓冲为空时不追加消息，但仍会发出 \l{streamEnded()}，以便界面上把"正在
		生成"的状态收回去。

		思考内容会被一并写进这条消息（见 \l{Message::setReasoning()}），因此历史
		记录里每一轮都能看到当时是怎么想的，而不只是最后说了什么。这一步必须在
		清空缓冲之前完成：思考原本只活在缓冲区里，一旦漏掉，界面上那一段就会
		随着流式状态一起消失，留下的答复看不出为什么是那个结论。
	*/
	void Dialog::endAssistantMessage() {
		const QString content = d->StreamingBuffer;
		const QString reasoning = d->ReasoningBuffer;
		d->StreamingBuffer.clear();
		d->Streaming = false;
		if (not content.isEmpty() or not reasoning.isEmpty()) {
			Message message(Message::Role::Assistant, content);
			message.setReasoning(reasoning);
			d->Messages.append(message);
			emit messageAppended(d->Messages.size() - 1);
		}
		emit streamEnded(content);
	}

	/*!
		\since Visindigo 0.17.0

		判断本对话是否正在接收流式响应。

		return 正在接收流式响应时返回 true。
	*/
	bool Dialog::isStreaming() const {
		return d->Streaming;
	}

	/*!
		\since Visindigo 0.17.0

		返回当前已接收但尚未收尾的流式内容。
	*/
	QString Dialog::getStreamingContent() const {
		return d->StreamingBuffer;
	}

	/*!
		\since Visindigo 0.17.0

		返回最近一次生成中模型给出的思考内容，供界面在生成过程中实时展示。

		推理模型的思考过程从 \l streamDelta() 之外的通道到达，它不属于回答，
		因此不会在下一轮被重新发回服务端。生成结束后，这段内容会被写进对应的
		助手消息（见 \l{Message::getReasoning()}），历史记录里仍能查到；
		本函数只反映“当前这一次”的缓冲，在每次 \l beginAssistantMessage() 时清空。
	*/
	QString Dialog::getReasoningContent() const {
		return d->ReasoningBuffer;
	}

	/*!
		\since Visindigo 0.17.0

		给本对话挂一个技能。同名技能会覆盖 Center 上的全局同名项。

		\a skill 要挂载的技能。
	*/
	Dialog& Dialog::addSkill(const Skill& skill) {
		removeSkill(skill.getName());
		d->Skills.append(skill);
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		移除本对话上的同名技能。移除之后，Center 上的全局同名技能会重新生效。

		\a name 技能名称。
	*/
	Dialog& Dialog::removeSkill(const QString& name) {
		for (qsizetype i = d->Skills.size() - 1; i >= 0; --i) {
			if (d->Skills.at(i).getName() == name) {
				d->Skills.removeAt(i);
			}
		}
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		返回本对话挂载的技能，不含 Center 上的全局技能。
	*/
	QList<Skill> Dialog::getSkills() const {
		return d->Skills;
	}

	/*!
		\since Visindigo 0.17.0

		给本对话挂一个工具服务器配置，同名会覆盖 Center 上的全局同名项。

		\a server 要挂载的工具服务器配置。
	*/
	Dialog& Dialog::addMCP(const MCP& server) {
		removeMCP(server.getName());
		d->MCPs.append(server);
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		移除本对话上的同名工具服务器配置。

		\a name 工具服务器名称。
	*/
	Dialog& Dialog::removeMCP(const QString& name) {
		for (qsizetype i = d->MCPs.size() - 1; i >= 0; --i) {
			if (d->MCPs.at(i).getName() == name) {
				d->MCPs.removeAt(i);
			}
		}
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		返回本对话挂载的工具服务器配置。
	*/
	QList<MCP> Dialog::getMCPs() const {
		return d->MCPs;
	}

	/*!
		\since Visindigo 0.17.0

		给本对话挂一个函数，所有权随之转移给本对话。

		同一个 id 重复添加会替换旧项，旧对象被释放。传入 \c nullptr 什么也不做。

		\a function 要挂载的函数对象，所有权随之转移给本对话。
	*/
	Dialog& Dialog::addFunction(Function* function) {
		if (function == nullptr) {
			return *this;
		}
		removeFunction(function->getId());
		d->Functions.insert(function->getId(), function);
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		移除并释放本对话上的函数。移除之后，Center 上的全局同名函数会重新生效。

		\a id 函数 id。
	*/
	Dialog& Dialog::removeFunction(const QString& id) {
		auto it = d->Functions.find(id);
		if (it != d->Functions.end()) {
			delete it.value();
			d->Functions.erase(it);
		}
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		按 id 查找函数，先查本对话再查 Center。找不到时返回 \c nullptr。

		\a id 函数 id。
	*/
	Function* Dialog::getFunction(const QString& id) const {
		return d->resolveFunction(id);
	}

	/*!
		\since Visindigo 0.17.0

		返回本对话独占的函数 id，不含 Center 上的全局函数。
	*/
	QStringList Dialog::getFunctionIds() const {
		return d->Functions.keys();
	}

	/*!
		\since Visindigo 0.17.0

		给本对话挂一个提示模板，同名会覆盖 Center 上的全局同名项。

		\a prompt 要挂载的提示模板。
	*/
	Dialog& Dialog::addPrompt(const Prompt& prompt) {
		removePrompt(prompt.getName());
		d->Prompts.append(prompt);
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		移除本对话上的同名提示模板。

		\a name 模板名称。
	*/
	Dialog& Dialog::removePrompt(const QString& name) {
		for (qsizetype i = d->Prompts.size() - 1; i >= 0; --i) {
			if (d->Prompts.at(i).getName() == name) {
				d->Prompts.removeAt(i);
			}
		}
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		返回本对话挂载的提示模板。
	*/
	QList<Prompt> Dialog::getPrompts() const {
		return d->Prompts;
	}

	/*!
		\since Visindigo 0.17.0

		查找模板、渲染并追加为一条消息。模板名不存在时什么也不做。

		查找顺序是先本对话后 Center，与 \l run() 的覆盖规则一致。

		\a name 模板名称。
		\a variables 模板变量表。
	*/
	Dialog& Dialog::appendPrompt(const QString& name, const QMap<QString, QString>& variables) {
		for (const Prompt& prompt : d->Prompts) {
			if (prompt.getName() == name) {
				return appendMessage(prompt.render(variables));
			}
		}
		const Prompt global = Center::getInstance()->getPrompt(name);
		if (global.isValid()) {
			return appendMessage(global.render(variables));
		}
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		返回对话的唯一标识。它在构造时生成，之后不再变化。
	*/
	QString Dialog::getId() const {
		return d->Id;
	}

	/*!
		\since Visindigo 0.17.0

		记录本对话从哪条对话分出来。全新对话留空。

		它表达的是"这条对话取代了哪一条"，因此重新生成回答时，新对话指向被它
		取代的那条，分支关系就自然形成了，不需要额外的树结构。

		\a id 被本条对话取代的对话 id；全新对话传空串。
	*/
	Dialog& Dialog::setBranchFromID(const QString& id) {
		d->BranchFromId = id;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		返回分叉来源的 id；不是由其他对话派生而来时返回空串。
	*/
	QString Dialog::getBranchFromID() const {
		return d->BranchFromId;
	}

	/*!
		\since Visindigo 0.17.0

		指定本次对话使用的 Provider。留空时使用 \l{Center::getDefaultProvider()}。

		\a id Provider 的 id；留空表示使用 Center 的默认 Provider。
	*/
	Dialog& Dialog::setProviderId(const QString& id) {
		d->ProviderId = id;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		返回指定的 Provider id；未指定时返回空串。
	*/
	QString Dialog::getProviderId() const {
		return d->ProviderId;
	}

	/*!
		\since Visindigo 0.17.0

		指定本次对话使用的模型。留空或指定的模型不可用时，由 Provider 按能力
		要求自行挑选。

		\a id 模型 id；留空表示由 Provider 挑选。
	*/
	Dialog& Dialog::setModelId(const QString& id) {
		d->ModelId = id;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		返回指定的模型 id；未指定时返回空串。
	*/
	QString Dialog::getModelId() const {
		return d->ModelId;
	}

	/*!
		\since Visindigo 0.17.0

		设置挑选模型时的最低能力要求，默认要求文本能力。

		当一次对话需要图片输入时把它设为文本与图片的按位或，模型挑选就会自动
		跳过不支持图片的端点，而不是把图片发过去等一个 400 回来。

		\a required 最低能力要求，多个能力按位或。
	*/
	Dialog& Dialog::setCapabilityRequirement(Model::Capabilities required) {
		d->CapabilityRequirement = required;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		返回挑选模型时的最低能力要求。
	*/
	Model::Capabilities Dialog::getCapabilityRequirement() const {
		return d->CapabilityRequirement;
	}

	/*!
		\since Visindigo 0.17.0

		执行本对话。

		流程是：解析 Provider 与模型、拼装请求体（系统提示来自技能，消息来自
		消息列表，工具声明来自函数表），随后发起流式请求。响应中的文本增量通过
		\l streamDelta() 实时吐出；如果模型要求调用工具，则依次执行、把结果作为
		\l Message::Role::Tool 消息追加，然后自动再发一轮，直到模型给出不含工具
		调用的最终答复。

		结果是异步的，本函数在请求发出后就返回。流程结束会发出 \l{streamEnded()}，
		失败则发出 \l{runFailed()}。

		\note 同一时刻只允许一次执行。正在执行时再次调用会直接发出 \l{runFailed()}，
		而不会排队——把两次生成叠在一起只会让会话记录变成一堆无法解释的片段。
	*/
	void Dialog::run() {
		if (d->Streaming) {
			emit runFailed(QStringLiteral("Dialog is already running."));
			return;
		}
		d->ToolRound = 0;
		d->startRun();
	}

	/*!
		\since Visindigo 0.17.0

		序列化为 JSON 对象，包含 id、分叉来源、模型选择、能力要求、消息列表，
		以及本对话挂载的技能、工具服务器与模板。

		\note 函数对象无法序列化：它们承载的是可执行代码而不是数据。
		*/
	Visindigo::Utility::JsonConfig Dialog::toJson() const {
		Visindigo::Utility::JsonConfig config;
		config.setString("id", d->Id);
		config.setString("branchFromId", d->BranchFromId);
		config.setString("providerId", d->ProviderId);
		config.setString("modelId", d->ModelId);
		config.setInt("capabilityRequirement", d->CapabilityRequirement.toInt());
		QList<Visindigo::Utility::JsonConfig> messages;
		for (const Message& message : d->Messages) {
			messages.append(message.toJson());
		}
		config.setArray("messages", messages);
		QList<Visindigo::Utility::JsonConfig> skills;
		for (const Skill& skill : d->Skills) {
			skills.append(skill.toJson());
		}
		config.setArray("skills", skills);
		QList<Visindigo::Utility::JsonConfig> servers;
		for (const MCP& server : d->MCPs) {
			servers.append(server.toJson());
		}
		config.setArray("mcps", servers);
		QList<Visindigo::Utility::JsonConfig> prompts;
		for (const Prompt& prompt : d->Prompts) {
			prompts.append(prompt.toJson());
		}
		config.setArray("prompts", prompts);
		return config;
	}

	/*!
		\since Visindigo 0.17.0

		从 JSON 对象恢复。

		存档里的 id 会被恢复，这是 Dialog 的 id 唯一的赋值入口。没有 id 字段时
		保留当前（新生成的）id。

		\warning 函数对象不在存档里，恢复后需要重新用 \l{addFunction()} 挂上；
		否则模型请求调用工具时会收到"未知工具"的答复。

		\a json 已解析的 JSON 对象。

		return 是否恢复了存档里的 id。
	*/
	bool Dialog::fromJson(const Visindigo::Utility::JsonConfig& json) {
		bool ok = false;
		const QString id = json.getString("id", &ok);
		if (ok and not id.isEmpty()) {
			d->Id = id;
		}
		d->BranchFromId = json.getString("branchFromId");
		d->ProviderId = json.getString("providerId");
		d->ModelId = json.getString("modelId");
		if (json.contains("capabilityRequirement")) {
			d->CapabilityRequirement = Model::Capabilities::fromInt(static_cast<int>(json.getInt("capabilityRequirement")));
		}
		d->Messages.clear();
		const QList<Visindigo::Utility::JsonConfig> messages = json.getArray("messages");
		for (const Visindigo::Utility::JsonConfig& entry : messages) {
			Message message;
			message.fromJson(entry);
			d->Messages.append(message);
		}
		d->Skills.clear();
		const QList<Visindigo::Utility::JsonConfig> skills = json.getArray("skills");
		for (const Visindigo::Utility::JsonConfig& entry : skills) {
			Skill skill;
			skill.fromJson(entry);
			d->Skills.append(skill);
		}
		d->MCPs.clear();
		const QList<Visindigo::Utility::JsonConfig> servers = json.getArray("mcps");
		for (const Visindigo::Utility::JsonConfig& entry : servers) {
			MCP server;
			server.fromJson(entry);
			d->MCPs.append(server);
		}
		d->Prompts.clear();
		const QList<Visindigo::Utility::JsonConfig> prompts = json.getArray("prompts");
		for (const Visindigo::Utility::JsonConfig& entry : prompts) {
			Prompt prompt;
			prompt.fromJson(entry);
			d->Prompts.append(prompt);
		}
		return ok and not id.isEmpty();
	}

	void DialogPrivate::startRun() {
		Center* center = Center::getInstance();
		Provider provider = center->getProvider(ProviderId);
		if (not provider.isValid()) {
			provider = center->getProvider(center->getDefaultProvider());
		}
		if (not provider.isValid()) {
			failRun(QStringLiteral("No provider available."));
			return;
		}
		// 重新生成时把上一轮的中间状态清掉，而不是指望每条失败路径都记得清
		ToolCalls.clear();
		FinishReason.clear();
		ActiveModelId = center->getModel(ModelId).isValid() ? ModelId : QString();
		if (ActiveModelId.isEmpty()) {
			ActiveModelId = provider.pickFirst(CapabilityRequirement);
		}
		const Model model = center->getModel(ActiveModelId);
		if (not model.isValid()) {
			failRun(QStringLiteral("No model satisfies the capability requirement."));
			return;
		}
		ActiveModel = model;
		Visindigo::Utility::JsonConfig body;
		buildRequestBody(body);
		body.setString("model", model.getName());
		buildTools(body);
		QUrl url = model.getUrl();
		QString path = url.path();
		while (path.endsWith('/')) {
			path.chop(1);
		}
		url.setPath(path + QStringLiteral("/chat/completions"));
		Visindigo::Network::SSERequest request(url);
		request.setMethod(Visindigo::Network::HttpRequest::Method::Post);
		request.setBearerToken(model.getToken());
		request.setContentType(QStringLiteral("application/json"));
		request.setJsonBody(body);
		if (model.getTimeoutMs() > 0) {
			request.setTimeoutMs(model.getTimeoutMs());
		}
		else {
			// 模型未设总时长上限时，必须显式关闭而不是什么都不做：中心的默认值会生效，
			// 一段稍长的回答就会被拦腰截断
			request.setTimeoutMs(-1);
		}
		if (model.getIdleTimeoutMs() > 0) {
			request.setIdleTimeoutMs(model.getIdleTimeoutMs());
		}
		// 断线重连会重发整条 POST，可能产生第二次生成与第二次计费，因此关闭
		request.setAutoReconnect(false);
		request.setPriority(Visindigo::Network::HttpRequest::Priority::High);
		request.setTag(QStringLiteral("agent:") + Id);
		q->beginAssistantMessage();
		Visindigo::Network::SSEReply* reply = Visindigo::Network::HttpCenter::getInstance()->request(request);
		if (reply == nullptr) {
			failRun(QStringLiteral("Failed to submit request."));
			return;
		}
		PendingReply = reply;
		reply->setAutoDelete(true);
		reply->onFrame(q, [this](const Visindigo::Network::StreamFrame& frame) -> bool {
			return handleFrame(frame);
		});
		reply->onError(q, [this](const Visindigo::Network::HttpError& error) {
			if (error.Type == Visindigo::Network::HttpError::ErrorType::Aborted) {
				return;
			}
			failRun(error.toString());
		});
		reply->then(q, [this](const Visindigo::Network::HttpResponse& response) {
			completeRun(response);
		});
	}

	void DialogPrivate::buildRequestBody(Visindigo::Utility::JsonConfig& body) const {
		QList<Visindigo::Utility::JsonConfig> messages;
		const QString instruction = buildSystemInstruction();
		if (not instruction.isEmpty()) {
			Visindigo::Utility::JsonConfig system;
			system.setString("role", "system");
			system.setString("content", instruction);
			messages.append(system);
		}
		for (const Message& message : Messages) {
			Visindigo::Utility::JsonConfig entry;
			switch (message.getRole()) {
			case Message::Role::System: entry.setString("role", "system"); break;
			case Message::Role::Assistant: entry.setString("role", "assistant"); break;
			case Message::Role::Tool: entry.setString("role", "tool"); break;
			default: entry.setString("role", "user"); break;
			}
			if (message.getContent().isEmpty() and not message.getToolCalls().isEmpty()) {
				entry.setValue("content", QJsonValue(QJsonValue::Null));
			}
			else {
				entry.setString("content", message.getContent());
			}
			if (message.getRole() == Message::Role::Tool and not message.getToolCallID().isEmpty()) {
				entry.setString("tool_call_id", message.getToolCallID());
			}
			if (not message.getToolCalls().isEmpty()) {
				const QJsonDocument document = QJsonDocument::fromJson(message.getToolCalls().toUtf8());
				if (document.isArray()) {
					entry.setValue("tool_calls", QJsonValue(document.array()));
				}
			}
			// 思考内容不写入：它只是模型的中间产物，回传会让模型以为自己已经说过那段话
			// 思考内容此处不写入：它只是模型的中间产物，回传会让模型以为自己已经说过那段话
			messages.append(entry);
		}
		body.setArray("messages", messages);
		body.setBool("stream", true);
		const Visindigo::Utility::JsonConfig parameters = ActiveModel.getParameters();
		for (const QString& key : parameters.keys()) {
			body.setValue(key, parameters.getValue(key));
		}
	}

	void DialogPrivate::buildTools(Visindigo::Utility::JsonConfig& body) const {
		static const QRegularExpression validId(QStringLiteral("^[a-zA-Z0-9_-]{1,64}$"));
		QStringList ids = Functions.keys();
		Center* center = Center::getInstance();
		for (const QString& id : center->getFunctionIds()) {
			if (not ids.contains(id)) {
				ids.append(id);
			}
		}
		for (const Skill& skill : GlobalSkills()) {
			for (const QString& id : skill.getFunctionIds()) {
				if (not ids.contains(id)) {
					ids.append(id);
				}
			}
		}
		QList<Visindigo::Utility::JsonConfig> tools;
		for (const QString& id : ids) {
			if (not validId.match(id).hasMatch()) {
				continue;
			}
			Function* function = resolveFunction(id);
			if (function == nullptr) {
				continue;
			}
			Visindigo::Utility::JsonConfig entry;
			entry.setString("type", "function");
			Visindigo::Utility::JsonConfig declaration;
			declaration.setString("name", function->getId());
			declaration.setString("description", function->getDescription());
			declaration.setObject("parameters", function->getParameterSchema());
			entry.setObject("function", declaration);
			tools.append(entry);
		}
		if (not tools.isEmpty()) {
			body.setArray("tools", tools);
		}
	}

	QList<Skill> DialogPrivate::GlobalSkills() const {
		Center* center = Center::getInstance();
		QList<Skill> merged = Skills;
		for (const Skill& skill : center->getSkills()) {
			bool overridden = false;
			for (const Skill& own : Skills) {
				if (own.getName() == skill.getName()) {
					overridden = true;
					break;
				}
			}
			if (not overridden) {
				merged.append(skill);
			}
		}
		return merged;
	}

	QString DialogPrivate::buildSystemInstruction() const {
		QStringList blocks;
		for (const Skill& skill : GlobalSkills()) {
			if (skill.isEnabled() and skill.isValid()) {
				blocks.append(skill.getInstruction());
			}
		}
		return blocks.join(QStringLiteral("\n\n"));
	}

	Function* DialogPrivate::resolveFunction(const QString& id) const {
		auto it = Functions.constFind(id);
		if (it != Functions.constEnd()) {
			return it.value();
		}
		return Center::getInstance()->getFunction(id);
	}

	void DialogPrivate::abortPendingReply() {
		if (PendingReply == nullptr) {
			return;
		}
		Visindigo::Network::SSEReply* reply = PendingReply;
		PendingReply = nullptr;
		reply->abort();
	}

	bool DialogPrivate::handleFrame(const Visindigo::Network::StreamFrame& frame) {
		QByteArray payload = frame.Data.trimmed();
		if (payload == QByteArrayLiteral("[DONE]")) {
			return true;
		}
		Visindigo::Utility::JsonConfig chunk;
		if (chunk.parse(QString::fromUtf8(payload)).error != QJsonParseError::NoError) {
			return true;
		}
		if (chunk.contains("error")) {
			const Visindigo::Utility::JsonConfig error = chunk.getObject("error");
			return false;
		}
		const QList<Visindigo::Utility::JsonConfig> choices = chunk.getArray("choices");
		if (choices.isEmpty()) {
			return true;
		}
		const Visindigo::Utility::JsonConfig choice = choices.first();
		const Visindigo::Utility::JsonConfig delta = choice.getObject("delta");
		const QString content = delta.getString("content");
		if (not content.isEmpty()) {
			q->appendDelta(content);
		}
		// 推理模型的思考内容走单独字段，混进正文会把思考当成回答存下来
		const QString reasoning = delta.getString("reasoning_content");
		if (not reasoning.isEmpty()) {
			ReasoningBuffer += reasoning;
			q->emit streamReasoning(reasoning);
		}
		const QList<Visindigo::Utility::JsonConfig> toolCalls = delta.getArray("tool_calls");
		for (const Visindigo::Utility::JsonConfig& call : toolCalls) {
			const qint32 index = static_cast<qint32>(call.getInt("index"));
			ToolCallBuilder& builder = ToolCalls[index];
			const QString callId = call.getString("id");
			if (not callId.isEmpty()) {
				builder.Id = callId;
			}
			const Visindigo::Utility::JsonConfig function = call.getObject("function");
			builder.Name += function.getString("name");
			builder.Arguments += function.getString("arguments");
		}
		const QString finish = choice.getString("finish_reason");
		if (not finish.isEmpty()) {
			FinishReason = finish;
		}
		return true;
	}

	void DialogPrivate::completeRun(const Visindigo::Network::HttpResponse& response) {
		PendingReply = nullptr;
		if (not response.isSuccess()) {
			failRun(QStringLiteral("HTTP %1").arg(response.getStatusCode()));
			return;
		}
		if (ToolCalls.isEmpty()) {
			q->endAssistantMessage();
			return;
		}
		if (ToolRound >= MaxToolRounds) {
			ToolCalls.clear();
			q->endAssistantMessage();
			failRun(QStringLiteral("Too many tool call rounds."));
			return;
		}
		QList<ToolCallBuilder> calls = ToolCalls.values();
		ToolCalls.clear();
		QJsonArray array;
		for (const ToolCallBuilder& call : calls) {
			QJsonObject function;
			function.insert(QStringLiteral("name"), call.Name);
			function.insert(QStringLiteral("arguments"), call.Arguments);
			QJsonObject entry;
			entry.insert(QStringLiteral("id"), call.Id);
			entry.insert(QStringLiteral("type"), QStringLiteral("function"));
			entry.insert(QStringLiteral("function"), function);
			array.append(entry);
		}
		Message message(Message::Role::Assistant, StreamingBuffer);
		message.setToolCalls(QString::fromUtf8(QJsonDocument(array).toJson(QJsonDocument::Compact)));
		message.setReasoning(ReasoningBuffer);
		Messages.append(message);
		const QString content = StreamingBuffer;
		StreamingBuffer.clear();
		Streaming = false;
		q->emit messageAppended(Messages.size() - 1);
		q->emit streamEnded(content);
		runToolCalls(calls);
	}

	void DialogPrivate::runToolCalls(const QList<ToolCallBuilder>& calls) {
		ToolRound++;
		for (const ToolCallBuilder& call : calls) {
			Function* function = resolveFunction(call.Name);
			QString result;
			if (function == nullptr) {
				result = QStringLiteral("{\"error\":\"unknown tool %1\"}").arg(call.Name);
			}
			else {
				Visindigo::Utility::JsonConfig arguments;
				arguments.parse(call.Arguments);
				result = function->invoke(arguments).toString(QJsonDocument::Compact);
			}
			Message toolMessage(Message::Role::Tool, result);
			toolMessage.setToolCallID(call.Id);
			toolMessage.setName(call.Name);
			Messages.append(toolMessage);
			q->emit messageAppended(Messages.size() - 1);
		}
		startRun();
	}

	void DialogPrivate::failRun(const QString& message) {
		Visindigo::Network::SSEReply* reply = PendingReply;
		PendingReply = nullptr;
		Streaming = false;
		StreamingBuffer.clear();
		ToolCalls.clear();
		if (reply != nullptr) {
			reply->setAutoDelete(true);
			reply->abort();
		}
		q->emit runFailed(message);
	}
}
