/*
	Visindigo Project Full AI Generated Declaration

	1. This file was entirely generated by AI. There was almost no human
	   involvement in the design of its API and implementation.
	2. Provided that the usage characteristics of the program corresponding
	   to this code are not substantially changed, anyone is free to make
	   fundamental modifications to this code.
	3. This code does not guarantee implementation consistency across
	   generations; it only guarantees that the corresponding program
	   features remain basically stable.
*/
#include <functional>
#include <Utility/JsonConfig.h>
#include "Agent/Function.h"

namespace Visindigo::Agent {
	/*!
		\class Visindigo::Agent::Function
		\inheaderfile Agent/Function.h
		\since Visindigo 0.17.0
		\inmodule Visindigo
		\brief 可供模型调用的工具接口.

		继承本类并实现五个纯虚函数，即可把一个本地能力暴露给模型。Visindigo
		会把 \l getParameterSchema() 转换成请求里的工具声明，模型决定调用后
		再把参数交回 \l{invoke()}。

		\l getId() 同时充当"发给模型的工具名"，因此它必须满足模型对函数名的
		字符集限制（字母、数字、下划线、连字符，长度不超过 64），并且不含空格
		与点号。用人类可读的中文名做 id 会导致请求被服务端直接拒绝，所以
		\l getName() 与 \l getId() 是两个独立的概念：前者用于展示，后者用于协议。

		所有函数对象的所有权归 \l{Center} 或 \l{Dialog}，二者按 id 索引，因此一份
		对话不会因为函数被复制而重复执行。实现者不需要自己做单例或缓存。
	*/

	/*!
		\since Visindigo 0.17.0

		虚析构，保证通过基类指针释放子类对象是安全的。
	*/
	Function::~Function() {
	}

	/*!
		\fn QString Visindigo::Agent::Function::getId() const
		\since Visindigo 0.17.0

		返回工具名，必须匹配 \c ^[a-zA-Z0-9_-]{1,64}$。

		这个 id 会出现在模型的输出里，也会出现在随后的工具结果消息里，因此它在
		一次对话内必须保持稳定——同名工具在不同轮次指向不同实现，会让模型的行为
		变得不可预测。
	*/
	/*!
		\fn QString Visindigo::Agent::Function::getName() const
		\since Visindigo 0.17.0

		返回人类可读的名称，用于界面展示。
	*/
	/*!
		\fn QString Visindigo::Agent::Function::getDescription() const
		\since Visindigo 0.17.0

		返回工具用途说明。

		说明是模型判断"该不该调用这个工具"的唯一依据，因此应当写清楚它做什么、
		什么时候用、以及什么情况下不要用。一句话的工具几乎不会被正确调用。
	*/
	/*!
		\fn Visindigo::Utility::JsonConfig Visindigo::Agent::Function::getParameterSchema() const
		\since Visindigo 0.17.0

		返回参数的 JSON Schema 对象。

		通常是 \c {"type": "object", "properties": {...}, "required": [...]}。
		参数名应当简洁且自解释：模型的调用正确率很大程度上取决于字段名与字段描述
		是否写得明白，而不是取决于参数有多少个。
	*/
	/*!
		\fn Visindigo::Utility::JsonConfig Visindigo::Agent::Function::invoke(const Visindigo::Utility::JsonConfig& arguments)
		\since Visindigo 0.17.0

		同步执行工具，\a arguments 是模型给出的参数对象。

		返回值会被序列化成紧凑 JSON 作为工具结果文本交回模型，因此需要交互的
		自由文本应当包成一个对象，例如只放一个键。执行失败时也应当正常返回一段
		描述失败原因的结果，而不是抛出异常：模型看到"文件不存在"通常会换个路径
		重试，而一个被异常打断的对话只能从头再来。
	*/
	/*!
		\since Visindigo 0.17.0

		异步执行工具。默认实现直接调用 \l invoke() 并立即回调，等价于同步执行。

		\note 默认实现是在调用线程上完成的，因此回调会在 \l invokeAsync() 返回
		之前就被触发。需要在回调里发起新请求的实现必须覆写本函数把工作交给
		事件循环，否则会在同一个调用栈里层层嵌套。

		\a arguments 模型给出的参数对象。
		\a callback 执行完成后调用的回调。
	*/
	void Function::invokeAsync(const Visindigo::Utility::JsonConfig& arguments,
		std::function<void(const Visindigo::Utility::JsonConfig&)> callback) {
		const Visindigo::Utility::JsonConfig result = invoke(arguments);
		if (callback) {
			callback(result);
		}
	}
}
