/*
	Visindigo Project Full AI Generated Declaration

	1. This file was entirely generated by AI. There was almost no human
	   involvement in the design of its API and implementation.
	2. Provided that the usage characteristics of the program corresponding
	   to this code are not substantially changed, anyone is free to make
	   fundamental modifications to this code.
	3. This code does not guarantee implementation consistency across
	   generations; it only guarantees that the corresponding program
	   features remain basically stable.
*/
#include <QtCore/qjsonvalue.h>
#include <QtCore/qstring.h>
#include <QtCore/qstringlist.h>
#include <QtCore/qurl.h>
#include <QtCore/quuid.h>
#include <Utility/JsonConfig.h>
#include "Agent/Model.h"
#include "Agent/private/Model_p.h"

namespace Visindigo::Agent {
	/*!
		\class Visindigo::Agent::Model
		\inheaderfile Agent/Model.h
		\since Visindigo 0.17.0
		\inmodule Visindigo
		\brief 一个可被请求的模型端点.

		Model 描述"请求该发到哪里、用哪个凭据、默认参数是什么"，它不持有任何会话
		状态。会话状态属于 \l{Dialog}。

		模型用 \l getId() 返回的 UUID 作为唯一标识，并注册在
		Visindigo::Agent::Center 的模型池里；\l Provider 与 \l Dialog 都只持有
		这个 id。之所以不把 Model 直接嵌进 Provider，是因为 Model 里带着凭据：
		如果 Provider 持有 Model 的副本，那么 token 会随 Provider 的每一次拷贝、
		每一次序列化扩散到各处，轮换凭据时就必须把所有副本翻出来改。id 索引把
		凭据收敛到唯一一份。

		\l Capability 描述该端点能接受哪些类型的输入。它不是装饰性的自我声明，
		而是给 \l Provider::pickFirst() 用来筛选的：当一次对话需要图片输入，而
		当前模型只声明了 \l Capability::Text 时，正确的做法是换一个模型，而不是
		把图片发给一个不支持它的端点——后者通常会得到一句含糊的 400。

		\note 这里只描述 OpenAI 兼容的请求形态。Model 不区分厂商，凡是遵循同一套
		请求/响应结构的端点都可以用它描述。
	*/

	/*!
		\enum Visindigo::Agent::Model::Capability
		\since Visindigo 0.17.0

		模型能力位标志。取值可以按位或组合，因此它是一个 \c QFlags 而不是普通枚举。

		\value None 无任何能力。仅作为 \c 0 使用，正常情况下不应该出现。
		\value Text 接受纯文本输入。这是所有对话模型的最低要求。
		\value Image 接受图片输入（视觉模型）。
		\value Audio 接受音频输入。
		\value ToolUse 支持工具调用，即请求里的 \c tools 字段会被认真处理，
			而不是被忽略或报错。声明了工具却得不到调用，最常见的原因就是漏了这个位。
	*/

	/*!
		\since Visindigo 0.17.0

		构造一个空模型，并立即分配一个新的 UUID。

		\note id 在构造时一次性生成，之后不再由外部修改；\l fromJson() 是唯一的
		例外，它会用存档里的 id 覆盖当前值。
	*/
	Model::Model() {
		d = new ModelPrivate();
		d->Id = QUuid::createUuid().toString(QUuid::WithoutBraces);
	}

	VICopyable_Impl(Model);
	VIMoveable_Impl(Model);

	/*!
		\since Visindigo 0.17.0
	*/
	Model::~Model() {
		delete d;
	}

	/*!
		\since Visindigo 0.17.0

		设置模型名，即请求体里 \c model 字段的值，例如 \c deepseek-flash。

		名称必须与服务端的取值完全一致，写错时服务端会直接拒绝请求。它同时
		也作为界面上的展示名——模型标识本来就该是自解释的，另起一个别名只会
		让配置与错误提示对不上。

		\note 名称不参与索引，索引一律走 id；同名模型可以共存。

		\a name 模型名，即请求体里 \c model 字段的值。
	*/
	Model& Model::setName(const QString& name) {
		d->Name = name;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		设置服务基地址，例如 \c https://api.deepseek.com。

		这里应当填基地址而不是完整的对话端点：具体的 \c /chat/completions 由
		执行层在拼装请求时追加，这样同一个 Model 描述就还能用于列出模型、
		计数 token 之类的旁路请求。

		\a url 服务基地址，不带具体端点路径。
	*/
	Model& Model::setUrl(const QUrl& url) {
		d->Url = url;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		设置访问凭据，将以 \c Authorization: Bearer 头的形式发出。

		\warning 凭据是明文保存在 Model 里的，而 Model 会被序列化。把带凭据的
		配置写进版本库或随程序分发都会直接泄露它；正确做法是让配置停留在用户
		自己机器的目录下。

		\a token 访问凭据。
	*/
	Model& Model::setToken(const QString& token) {
		d->Token = token;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		设置单次请求的总时长上限，单位毫秒。\c 0 表示不限。

		\warning 对话请求通常是流式的，总时长上限会随模型输出长度自然增长。
		对流式请求应当依赖 \l setIdleTimeoutMs() 而不是这个值，否则一段较长的
		回答会在中途被整体掐断。

		\a ms 总时长上限，单位毫秒；\c 0 表示不限。
	*/
	Model& Model::setTimeoutMs(qint32 ms) {
		d->TimeoutMs = ms;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		设置两次数据到达之间的最大间隔，单位毫秒。\c 0 表示使用执行层的默认值。

		这是流式请求真正需要的超时：模型思考时可能长时间不吐字，但只要连接还活着
		就不该判定失败，而连接真断了又必须尽快发现。

		\a ms 空闲超时，单位毫秒；\c 0 表示使用执行层的默认值。
	*/
	Model& Model::setIdleTimeoutMs(qint32 ms) {
		d->IdleTimeoutMs = ms;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		整体替换能力声明。传入 \l Capability::None 相当于声明"什么都不能做"，
		该模型将无法被任何 \l Provider::pickFirst() 选中。

		\a capabilities 完整的能力位组合。
	*/
	Model& Model::setCapabilities(Capabilities capabilities) {
		d->Capabilities = capabilities;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		追加一个能力位，不影响已声明的能力。

		\a capability 要追加的能力位。
	*/
	Model& Model::addCapability(Capability capability) {
		d->Capabilities |= capability;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		设置一个原样并入请求体的模型参数，例如 \c {"frequency_penalty": 0.5}。

		\a key 支持 \c "a.b" 形式的点号路径，用于写入嵌套对象。

		这类参数不做任何校验与改名，因此当服务端新增某个采样参数时不需要改动
		Visindigo，直接在配置里写出来即可。代价是拼错的键不会被发现——服务端
		多半会静默忽略它。

		\a value 参数值，原样写入请求体。
	*/
	Model& Model::setParameter(const QString& key, const QJsonValue& value) {
		d->Parameters.insert(key, value);
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		设置 \c temperature。等价于 \l setParameter() 写入 \c "temperature"。

		这是常用的采样参数，因此单独给一个入口，省得调用方自己拼 JSON 值。

		\a value 采样温度。
	*/
	Model& Model::setTemperature(qreal value) {
		d->Parameters.insert("temperature", QJsonValue(value));
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		设置 \c top_p。等价于 \l setParameter() 写入 \c "top_p"。

		\a value top_p 取值。
	*/
	Model& Model::setTopP(qreal value) {
		d->Parameters.insert("top_p", QJsonValue(value));
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		设置单次回复的输出上限。等价于 \l setParameter() 写入 \c "max_tokens"。

		\note 这是输出上限，不是上下文上限；两者的字段名在不同服务端并不统一，
		因此这里只提供最常见的一种写法。

		\a value 输出上限（token 数）。
	*/
	Model& Model::setMaxTokens(qint32 value) {
		d->Parameters.insert("max_tokens", QJsonValue(value));
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		返回模型的唯一标识。
	*/
	QString Model::getId() const {
		return d->Id;
	}

	/*!
		\since Visindigo 0.17.0

		返回模型名。

		\note 它是服务端的模型标识，不是本地别名。见 \l{setName()}。
	*/
	QString Model::getName() const {
		return d->Name;
	}

	/*!
		\since Visindigo 0.17.0

		返回服务基地址。
	*/
	QUrl Model::getUrl() const {
		return d->Url;
	}

	/*!
		\since Visindigo 0.17.0

		返回访问凭据。

		\warning 不要把它的返回值写进日志或错误提示。
	*/
	QString Model::getToken() const {
		return d->Token;
	}

	/*!
		\since Visindigo 0.17.0

		返回请求总时长上限，单位毫秒。
	*/
	qint32 Model::getTimeoutMs() const {
		return d->TimeoutMs;
	}

	/*!
		\since Visindigo 0.17.0

		返回空闲超时，单位毫秒。
	*/
	qint32 Model::getIdleTimeoutMs() const {
		return d->IdleTimeoutMs;
	}

	/*!
		\since Visindigo 0.17.0

		返回已声明的全部能力位。
	*/
	Model::Capabilities Model::getCapabilities() const {
		return d->Capabilities;
	}

	/*!
		\since Visindigo 0.17.0

		判断是否声明了指定能力。多个位需要同时满足时，调用方应当自行用
		\c Capabilities 做整体比较，本函数只检查单个位。

		\a capability 要检查的能力位。

		return 声明了该能力位时返回 true。
	*/
	bool Model::hasCapability(Capability capability) const {
		return d->Capabilities.testFlag(capability);
	}

	/*!
		\since Visindigo 0.17.0

		把全部模型参数导出为一个 JSON 对象。点号路径的键在导出时会被还原成嵌套结构。
	*/
	Visindigo::Utility::JsonConfig Model::getParameters() const {
		Visindigo::Utility::JsonConfig config;
		for (auto it = d->Parameters.constBegin(); it != d->Parameters.constEnd(); ++it) {
			config.setValue(it.key(), it.value());
		}
		return config;
	}

	/*!
		\since Visindigo 0.17.0

		判断模型描述是否足够发起一次请求：需要非空模型名、合法的绝对 URL，
		以及非空凭据。

		\note 这里不检查 URL 是否真的可达——那属于运行期的事，配置阶段无从得知。

		return 模型名、URL 与凭据都齐全时返回 true。
	*/
	bool Model::isValid() const {
		return not d->Name.isEmpty() and d->Url.isValid() and not d->Url.scheme().isEmpty()
			and not d->Token.isEmpty();
	}

	/*!
		\since Visindigo 0.17.0

		序列化为 JSON 对象，包含 id、连接信息、能力位与全部模型参数。

		\warning 返回值里含有明文凭据，见 \l setToken() 的警告。
	*/
	Visindigo::Utility::JsonConfig Model::toJson() const {
		Visindigo::Utility::JsonConfig config;
		config.setString("id", d->Id);
		config.setString("name", d->Name);
		config.setString("url", d->Url.toString());
		config.setString("token", d->Token);
		config.setInt("timeoutMs", d->TimeoutMs);
		config.setInt("idleTimeoutMs", d->IdleTimeoutMs);
		config.setInt("capabilities", d->Capabilities.toInt());
		config.setObject("parameters", getParameters());
		return config;
	}

	/*!
		\since Visindigo 0.17.0

		从 JSON 对象恢复。

		存档里带有 id 时会一并恢复，这是 id 唯一的赋值入口；没有 id 字段时保留
		当前（新生成的）id，因而把一个只写了连接信息的手写配置文件读进来也能得到
		一个可用的模型。

		\a json 应当是 \l toJson() 的输出，或者结构相同的手写配置。

		return 读到了非空的 id 时返回 true。
	*/
	bool Model::fromJson(const Visindigo::Utility::JsonConfig& json) {
		bool ok = false;
		const QString id = json.getString("id", &ok);
		if (ok and not id.isEmpty()) {
			d->Id = id;
		}
		d->Name = json.getString("name");
		d->Url = QUrl(json.getString("url"));
		d->Token = json.getString("token");
		d->TimeoutMs = static_cast<qint32>(json.getInt("timeoutMs", nullptr));
		d->IdleTimeoutMs = static_cast<qint32>(json.getInt("idleTimeoutMs", nullptr));
		if (json.contains("capabilities")) {
			d->Capabilities = Model::Capabilities::fromInt(static_cast<int>(json.getInt("capabilities")));
		}
		d->Parameters.clear();
		const Visindigo::Utility::JsonConfig parameters = json.getObject("parameters");
		for (const QString& key : parameters.keys()) {
			d->Parameters.insert(key, parameters.getValue(key));
		}
		return ok and not id.isEmpty();
	}
}
