import sys
import os
import re
import datetime

AutoVersionFilePath = "\\Visindigo\\General\\private\\AUTO_VERSION.h"
VersionMacroFilePath = "\\Visindigo\\General\\private\\VersionMacro.h"
VersionNickName = "EA TP1"

def getCommitCount():
    gitCommitsCount = os.popen("git log --oneline | find /v /c \"\"").read()
    gitCommitsCount = int(gitCommitsCount)+1
    print("git commits count now is : "+ str(gitCommitsCount))
    return gitCommitsCount

def readVersionMacros(path):
    """从 VersionMacro.h 读取主/次/修订版本号，保证版本号单一来源。"""
    macros = {"MAJOR": "0", "MINOR": "0", "PATCH": "0"}
    macroPath = path + VersionMacroFilePath
    if not os.path.exists(macroPath):
        print("warning: VersionMacro.h not found: " + macroPath)
        return macros
    with open(macroPath, "r", encoding="utf-8-sig") as versionMacroFile:
        content = versionMacroFile.read()
    for name in ("MAJOR", "MINOR", "PATCH"):
        match = re.search(r"#define\s+Visindigo_VERSION_"+name+r"\s+(\d+)", content)
        if match:
            macros[name] = match.group(1)
    return macros

def spawnHeadFile(path):
    if os.path.exists(path+AutoVersionFilePath):
        os.remove(path+AutoVersionFilePath)
    versionFile = open(path+AutoVersionFilePath, "w", encoding="utf-8-sig")
    versionFile.write("#pragma execution_character_set(\"utf-8\")\n")
    versionFile.write("#ifndef Visindigo_General_AUTO_VERSION_h\n")
    versionFile.write("#define Visindigo_General_AUTO_VERSION_h\n\n")
    versionFile.write("// This file is auto generated by Visindigo/pytools/AutoVersionFromGIT.py\n")
    versionFile.write("// Do not modify this file manually\n")
    versionMacros = readVersionMacros(path)
    build = getCommitCount()
    versionString = versionMacros["MAJOR"]+"."+versionMacros["MINOR"]+"."+versionMacros["PATCH"]+"."+str(build)
    versionFile.write("#define Visindigo_VERSION_BUILD "+str(build)+"\n")
    versionFile.write("#define Visindigo_VERSION_STRING \""+versionString+"\"\n")
    versionFile.write("#define Visindigo_VERSION_BUILD_DATE \""+datetime.date.today().strftime("%Y-%m-%d")+"\"\n")
    versionFile.write("#define Visindigo_VERSION_BUILD_TIME \""+datetime.datetime.now().strftime("%H:%M:%S")+"\"\n")
    versionFile.write("#define Visindigo_VERSION_NICKNAME \""+VersionNickName+"\"\n")
    versionFile.write("\n#endif // Visindigo_General_AUTO_VERSION_h\n")
    versionFile.close()


if __name__ == "__main__":
    path:str = sys.path[0]
    print(path)
    os.chdir(path+"/../../")
    path = os.getcwd()
    spawnHeadFile(path)


