/*
	Visindigo Project Full AI Generated Declaration

	1. This file was entirely generated by AI. There was almost no human
	   involvement in the design of its API and implementation.
	2. Provided that the usage characteristics of the program corresponding
	   to this code are not substantially changed, anyone is free to make
	   fundamental modifications to this code.
	3. This code does not guarantee implementation consistency across
	   generations; it only guarantees that the corresponding program
	   features remain basically stable.
*/
#include <QtCore/qstring.h>
#include <functional>
#include <memory>
#include "Network/HttpRequest.h"
#include "Network/HttpTypes.h"
#include "Network/SSERequest.h"

namespace Visindigo::Network {
	class SSEReplyPrivate {
	public:
		QString LastEventId;
	};

	SSEReply::SSEReply() {
		d = new SSEReplyPrivate();
		// 记录服务端给出的最近一次事件标识，它既是续传的起点，
		// 也是调用方判断"流推进到哪了"的唯一依据。
		QObject::connect(this, &HttpReply::frameReceived, this, [this](const StreamFrame& frame) {
			if (!frame.Id.isEmpty()) {
				d->LastEventId = frame.Id;
			}
		});
	}

	SSEReply::~SSEReply() {
		delete d;
	}

	/*!
		\class Visindigo::Network::SSEReply
		\inheaderfile Network/SSERequest.h
		\since Visindigo 0.17.0
		\inmodule Visindigo
		\brief SSE 请求的句柄.

		本类继承自 Visindigo::Network::HttpReply，因此状态机、进度、错误、中止与
		生命周期绑定等能力全部复用，只额外提供按事件名或谓词分派的帧路由。

		\note 流式请求下 \l HttpReply::then 表示"流正常结束"，而不是"取到了完整
		内容"。事件应当通过 \l when 或 \l HttpReply::onFrame 消费。

		\sa Visindigo::Network::SSERequest
		\sa Visindigo::Network::HttpReply
	*/

	/*!
		\fn void Visindigo::Network::SSEReply::reconnecting(qint32 attempt, qint32 delayMs)
		\since Visindigo 0.17.0

		断线后正在等待重连。\a attempt 是第几次尝试，\a delayMs 是即将等待的毫秒数。

		\note 重连会带上最近的事件标识（Last-Event-ID）续传，但服务端并不保证一定
		接受它。无法续传时这一段推送就是真的丢了，消费方不应假定事件连续。
	*/

	/*!
		\since Visindigo 0.17.0

		按事件名注册处理器：只有 \c{Event} 与该名字相等的事件才会进入处理器。
		同名事件会多次触发，处理器返回 \c false 表示中止整个流。

		按事件名分派是 SSE 最自然的用法，因为服务端通常用它区分
		\c message、\c ping、\c error 等不同种类的推送。

		\a eventName 要监听的事件名。
		\a context 接收回调的对象；传 \c nullptr 表示使用本对象。
		\a handler 处理器，返回 \c false 表示中止整个流。
	*/
	SSEReply& SSEReply::when(const QString& eventName, QObject* context,
		std::function<bool(const StreamFrame&)> handler) {
		QObject* target = context != nullptr ? context : this;
		QObject::connect(this, &HttpReply::frameReceived, target,
			[this, eventName, handler](const StreamFrame& frame) {
				if (frame.Event != eventName) {
					return;
				}
				if (!handler(frame)) {
					abort();
				}
			});
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		按谓词注册处理器，适用于不带 \c event 字段的流——很多服务端只发
		\c data，此时无法按事件名分派，只能按内容特征判断。谓词返回 \c true
		表示命中，随后调用处理器。

		\a predicate 命中判定谓词，返回 \c true 表示该帧需要交给处理器。
		\a context 接收回调的对象；传 \c nullptr 表示使用本对象。
		\a handler 处理器，返回 \c false 表示中止整个流。
	*/
	SSEReply& SSEReply::when(std::function<bool(const StreamFrame&)> predicate, QObject* context,
		std::function<bool(const StreamFrame&)> handler) {
		QObject* target = context != nullptr ? context : this;
		QObject::connect(this, &HttpReply::frameReceived, target,
			[this, predicate, handler](const StreamFrame& frame) {
				if (!predicate(frame)) {
					return;
				}
				if (!handler(frame)) {
					abort();
				}
			});
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		与 \l when 相同，但只在首次命中时触发一次。适用于"只关心第一次出现的
		某个事件"的场景，例如服务端在流开始时推送的一次性元信息。

		\a eventName 要监听的事件名。
		\a context 接收回调的对象；传 \c nullptr 表示使用本对象。
		\a handler 处理器，返回 \c false 表示中止整个流。
	*/
	SSEReply& SSEReply::whenOnce(const QString& eventName, QObject* context,
		std::function<bool(const StreamFrame&)> handler) {
		auto fired = std::make_shared<bool>(false);
		QObject* target = context != nullptr ? context : this;
		QObject::connect(this, &HttpReply::frameReceived, target,
			[this, eventName, handler, fired](const StreamFrame& frame) {
				if (*fired || frame.Event != eventName) {
					return;
				}
				*fired = true;
				if (!handler(frame)) {
					abort();
				}
			});
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		谓词版的一次性处理器：首次命中 \a predicate 时触发一次，之后不再触发。
		常用于“只关心出现的第一个数据帧”这类场景。

		\note “只触发一次”的判定建立在谓词命中之上，而不是建立在处理器返回 true 之上。
		即使处理器返回 \c false（要求中止流），本处理器也不会再次被调用。

		\a predicate 命中判定谓词。
		\a context 接收回调的对象；传 \c nullptr 表示使用本对象。
		\a handler 处理器，返回 \c false 表示中止整个流。
	*/
	SSEReply& SSEReply::whenOnce(std::function<bool(const StreamFrame&)> predicate, QObject* context,
		std::function<bool(const StreamFrame&)> handler) {
		auto fired = std::make_shared<bool>(false);
		QObject* target = context != nullptr ? context : this;
		QObject::connect(this, &HttpReply::frameReceived, target,
			[this, predicate, handler, fired](const StreamFrame& frame) {
				if (*fired || !predicate(frame)) {
					return;
				}
				*fired = true;
				if (!handler(frame)) {
					abort();
				}
			});
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		不带 context 的便利重载，等价于传入 \c nullptr。

		\note 此时连接的生命周期跟随句柄本身：句柄销毁时连接自动断开，因此不会
		造成悬垂指针；但反过来说，句柄存活期间连接也一直存在。带捕获的表达式
		建议改用带 context 的重载，以便宿主对象销毁时及时断开。

		\a eventName 要监听的事件名。
		\a handler 处理器，返回 \c false 表示中止整个流。
	*/
	SSEReply& SSEReply::when(const QString& eventName, std::function<bool(const StreamFrame&)> handler) {
		return when(eventName, nullptr, handler);
	}

	/*!
		\since Visindigo 0.17.0

		返回最近一次服务端给出的事件标识。断线后可用它作为
		Visindigo::Network::SSERequest::setLastEventId() 的入参，从断点继续接收。
	*/
	QString SSEReply::getLastEventId() const {
		return d->LastEventId;
	}
}
