/*
	Visindigo Project Full AI Generated Declaration

	1. This file was entirely generated by AI. There was almost no human
	   involvement in the design of its API and implementation.
	2. Provided that the usage characteristics of the program corresponding
	   to this code are not substantially changed, anyone is free to make
	   fundamental modifications to this code.
	3. This code does not guarantee implementation consistency across
	   generations; it only guarantees that the corresponding program
	   features remain basically stable.
*/
#include <QtCore/qbytearray.h>
#include <QtCore/qlist.h>
#include <QtCore/qmap.h>
#include <QtCore/qmimetype.h>
#include <QtCore/qstring.h>
#include <QtCore/qurl.h>
#include <memory>
#include "Network/HttpRequest.h"
#include "Network/HttpTypes.h"
#include "Network/SSERequest.h"

namespace Visindigo::Network {
	class SseDecoderPrivate {
	public:
		QByteArray Buffer;
		QString PendingEvent;
		QByteArray PendingData;
		QString LastEventId;
		qint32 PendingRetryMs = -1;
		qint64 MaxFrameBytes = 1024 * 1024;
	};

	class SSERequestPrivate {
	public:
		HttpRequest Inner;
		QString LastEventId;
		bool AutoReconnect = true;
		qint32 MaxReconnectAttempts = 5;
	};

	/*!
		\class Visindigo::Network::SseDecoder
		\inheaderfile Network/SSERequest.h
		\since Visindigo 0.17.0
		\inmodule Visindigo
		\brief SSE（W3C text/event-stream）流解码器.

		按 W3C 的 Server-Sent Events 规范把字节流切成事件帧：

		\list
		\li 以空行作为一次事件的结束标记；连续的空行不产生事件。
		\li 行结束符接受 \c LF、\c CR 与 \c CRLF 三种写法。
		\li \c data 字段可以出现多次，其值以换行连接；单个 \c data 行开头的
			一个空格会被剥除。
		\li \c event 字段给出事件名，缺省时事件名为空串。
		\li \c id 字段更新最近一次事件标识，用于断线续传；含空字符的值按规范忽略。
		\li \c retry 字段给出服务端建议的重连间隔（毫秒）。
		\li 以冒号开头的行是注释，直接丢弃——它常用于保活心跳。
		\endlist

		\note 本实现不含任何厂商语义。诸如 \c "data: [DONE]" 这样的结束约定由上层
		协议实现自行判断；这样做是为了让本模块对各家服务保持中立，厂家专属的
		约定应当写在使用它们的地方，而不是沉到通用解码器里。

		\note 关于流结束（finish）时的行为，本实现对规范做了一处放宽：规范要求
		丢弃尚未以空行结束的残余事件，而这里会把它补发出去。原因是一些服务端
		在发出最后一个事件后直接断开，若严格丢弃就会丢掉末尾数据。
	*/

	SseDecoder::SseDecoder() {
		d = new SseDecoderPrivate();
	}

	SseDecoder::~SseDecoder() {
		delete d;
	}

	/*!
		\since Visindigo 0.17.0

		清空缓冲与未完成的事件。重试或重定向后由中心调用。
	*/
	void SseDecoder::reset() {
		d->Buffer.clear();
		d->PendingEvent.clear();
		d->PendingData.clear();
		d->PendingRetryMs = -1;
	}

	/*!
		\since Visindigo 0.17.0

		送入新增字节并返回本次能够完整切出的事件帧。跨包的半个事件会被保留到
		后续调用，因此调用方不必关心网络分包边界。

		\a chunk 新到达的字节，其边界没有任何语义。
	*/
	QList<StreamFrame> SseDecoder::feed(const QByteArray& chunk) {
		QList<StreamFrame> frames;
		d->Buffer.append(chunk);
		qsizetype pos = 0;
		while (pos < d->Buffer.size()) {
			qsizetype lineEnd = -1;
			qsizetype nextLine = -1;
			for (qsizetype i = pos; i < d->Buffer.size(); ++i) {
				const char current = d->Buffer.at(i);
				if (current == '\n') {
					lineEnd = i;
					nextLine = i + 1;
					break;
				}
				if (current == '\r') {
					lineEnd = i;
					if (i + 1 >= d->Buffer.size()) {
						// 可能是 CRLF 的前半，等下一个字节到达再判定
						nextLine = -1;
					}
					else {
						nextLine = d->Buffer.at(i + 1) == '\n' ? i + 2 : i + 1;
					}
					break;
				}
			}
			if (lineEnd < 0 || nextLine < 0) {
				break;
			}
			const QByteArray line = d->Buffer.mid(pos, lineEnd - pos);
			pos = nextLine;

			if (line.isEmpty()) {
				// 空行即派发。规范规定 data 缓冲为空时不产生事件。
				if (!d->PendingData.isEmpty()) {
					StreamFrame frame;
					frame.Event = d->PendingEvent;
					QByteArray data = d->PendingData;
					if (data.endsWith('\n')) {
						data.chop(1);
					}
					frame.Data = data;
					frame.Id = d->LastEventId;
					frame.RetryMs = d->PendingRetryMs;
					frames.append(frame);
				}
				d->PendingEvent.clear();
				d->PendingData.clear();
				d->PendingRetryMs = -1;
				continue;
			}
			if (line.startsWith(':')) {
				continue;
			}
			const qsizetype colon = line.indexOf(':');
			const QByteArray field = colon < 0 ? line : line.left(colon);
			QByteArray value = colon < 0 ? QByteArray() : line.mid(colon + 1);
			if (value.startsWith(' ')) {
				value.remove(0, 1);
			}
			if (field == QByteArrayLiteral("event")) {
				d->PendingEvent = QString::fromUtf8(value);
			}
			else if (field == QByteArrayLiteral("data")) {
				d->PendingData += value;
				d->PendingData += '\n';
			}
			else if (field == QByteArrayLiteral("id")) {
				if (!value.contains('\0')) {
					d->LastEventId = QString::fromUtf8(value);
				}
			}
			else if (field == QByteArrayLiteral("retry")) {
				bool ok = false;
				const qint32 parsed = value.toInt(&ok);
				if (ok && parsed >= 0) {
					d->PendingRetryMs = parsed;
				}
			}
		}
		d->Buffer.remove(0, pos);
		if (d->MaxFrameBytes > 0 && d->Buffer.size() > d->MaxFrameBytes) {
			// 长期收不到换行说明对端可能根本不发换行，继续累积只会耗尽内存。
			d->Buffer.clear();
		}
		return frames;
	}

	/*!
		\since Visindigo 0.17.0

		流结束时调用，补发尚未以空行结束的残余事件。详见类说明中的行为解释。
	*/
	QList<StreamFrame> SseDecoder::finish() {
		QList<StreamFrame> frames;
		if (!d->PendingData.isEmpty()) {
			StreamFrame frame;
			frame.Event = d->PendingEvent;
			QByteArray data = d->PendingData;
			if (data.endsWith('\n')) {
				data.chop(1);
			}
			frame.Data = data;
			frame.Id = d->LastEventId;
			frame.RetryMs = d->PendingRetryMs;
			frames.append(frame);
		}
		d->PendingEvent.clear();
		d->PendingData.clear();
		d->PendingRetryMs = -1;
		d->Buffer.clear();
		return frames;
	}

	/*!
		\since Visindigo 0.17.0

		返回尚未构成完整事件的字节数。
	*/
	qint64 SseDecoder::getBufferedBytes() const {
		return d->Buffer.size();
	}

	/*!
		\since Visindigo 0.17.0

		设置单帧缓冲上限，默认 1 MiB。

		\a bytes 单帧缓冲上限，单位为字节。
	*/
	void SseDecoder::setMaxFrameBytes(qint64 bytes) {
		d->MaxFrameBytes = bytes;
	}

	/*!
		\since Visindigo 0.17.0

		返回当前的单帧缓冲上限。
	*/
	qint64 SseDecoder::getMaxFrameBytes() const {
		return d->MaxFrameBytes;
	}

	/*!
		\class Visindigo::Network::SSERequest
		\inheaderfile Network/SSERequest.h
		\since Visindigo 0.17.0
		\inmodule Visindigo
		\brief SSE 请求描述对象.

		SSERequest 与 Visindigo::Network::HttpRequest 是组合关系而非继承关系：
		内层持有一个 HttpRequest，本类把它对外的接口逐项转发一遍，并额外提供
		SSE 专属的设置项。

		转发的接口与 HttpRequest 保持分类与顺序一致，便于对照维护，但对 SSE 无意义
		的落盘与内存缓存相关接口不予提供——中心对 SSE 强制按流式交付，即便提供
		也会被忽略，不如不给。

		提交时中心会自动挂载 Visindigo::Network::SseDecoder 并按流式交付，
		事件经 Visindigo::Network::SSEReply::frameReceived 与
		Visindigo::Network::SSEReply::when() 送达。

		\note 本类上那批转发接口（setUrl、setHeader、setRetryPolicy……）与
		Visindigo::Network::HttpRequest 上的同名方法语义完全相同，只是把返回值
		由 \c HttpRequest& 换成了 \c SSERequest& 以保持链式书写。它们的详细说明
		请参见 HttpRequest 上的对应方法，此处不再重述——同一段语义只保留一个
		出处，避免两边描述日久失配。

		其中三个方法的语义与 HttpRequest 上的同名者并不完全一致，已在本类上
		单独说明：\l{setTimeoutMs}（长连接不应使用）、\l{setStreamDecoder}
		（默认已挂载 SseDecoder）与 \l{setMaxFrameBytes}。

		\sa Visindigo::Network::SSEReply
	*/

	SSERequest::SSERequest() {
		d = new SSERequestPrivate();
	}

	SSERequest::SSERequest(const QUrl& url) {
		d = new SSERequestPrivate();
		d->Inner.setUrl(url);
	}

	/*!
		\since Visindigo 0.17.0

		以已有的通用请求初始化内层配置。标记为 explicit 是为了避免 HttpRequest
		隐式转换成本类型——若允许隐式转换，中心那两个重载的解析会变得难以预测。
	*/
	SSERequest::SSERequest(const HttpRequest& request) {
		d = new SSERequestPrivate();
		d->Inner = request;
	}

	VICopyable_Impl(SSERequest);
	VIMoveable_Impl(SSERequest);

	SSERequest::~SSERequest() {
		delete d;
	}

	/*!
		\since Visindigo 0.17.0

		返回内层请求的引用。它主要作为"逃生舱"存在：需要把配置交给某个接受
		HttpRequest 的接口时使用，日常设置请直接调用本类的转发接口。
	*/
	HttpRequest& SSERequest::getRequest() {
		return d->Inner;
	}

	const HttpRequest& SSERequest::getRequest() const {
		return d->Inner;
	}

	/*!
		\since Visindigo 0.17.0

		整体替换内层请求配置。

		\a request 新的内层请求。
	*/
	SSERequest& SSERequest::setRequest(const HttpRequest& request) {
		d->Inner = request;
		return *this;
	}

	SSERequest& SSERequest::setMethod(Method method) {
		d->Inner.setMethod(method);
		return *this;
	}

	SSERequest& SSERequest::setCustomMethod(const QByteArray& verb) {
		d->Inner.setCustomMethod(verb);
		return *this;
	}

	QByteArray SSERequest::getCustomMethod() const {
		return d->Inner.getCustomMethod();
	}

	SSERequest& SSERequest::setUrl(const QUrl& url) {
		d->Inner.setUrl(url);
		return *this;
	}

	SSERequest& SSERequest::setUrl(const QString& url) {
		d->Inner.setUrl(url);
		return *this;
	}

	SSERequest& SSERequest::setPath(const QString& relativePath) {
		d->Inner.setPath(relativePath);
		return *this;
	}

	SSERequest& SSERequest::setQuery(const QString& key, const QString& value) {
		d->Inner.setQuery(key, value);
		return *this;
	}

	SSERequest& SSERequest::setQuery(const QMap<QString, QString>& params) {
		d->Inner.setQuery(params);
		return *this;
	}

	SSERequest& SSERequest::setHeader(const QString& key, const QString& value) {
		d->Inner.setHeader(key, value);
		return *this;
	}

	SSERequest& SSERequest::setHeader(const QMap<QString, QString>& headers) {
		d->Inner.setHeader(headers);
		return *this;
	}

	SSERequest& SSERequest::setContentType(const QString& mime) {
		d->Inner.setContentType(mime);
		return *this;
	}

	SSERequest& SSERequest::setContentType(const QMimeType& mime) {
		d->Inner.setContentType(mime);
		return *this;
	}

	SSERequest& SSERequest::setAccept(const QString& mime) {
		d->Inner.setAccept(mime);
		return *this;
	}

	SSERequest& SSERequest::setAccept(const QMimeType& mime) {
		d->Inner.setAccept(mime);
		return *this;
	}

	SSERequest& SSERequest::setUserAgent(const QString& userAgent) {
		d->Inner.setUserAgent(userAgent);
		return *this;
	}

	SSERequest& SSERequest::setBearerToken(const QString& token) {
		d->Inner.setBearerToken(token);
		return *this;
	}

	SSERequest& SSERequest::setBasicAuth(const QString& user, const QString& password) {
		d->Inner.setBasicAuth(user, password);
		return *this;
	}

	SSERequest& SSERequest::setJsonBody(const Visindigo::Utility::JsonConfig& json) {
		d->Inner.setJsonBody(json);
		return *this;
	}

	SSERequest& SSERequest::setJsonBody(const QByteArray& rawJson) {
		d->Inner.setJsonBody(rawJson);
		return *this;
	}

	SSERequest& SSERequest::setRawBody(const QByteArray& body) {
		d->Inner.setRawBody(body);
		return *this;
	}

	SSERequest& SSERequest::setFormBody(const QMap<QString, QString>& fields) {
		d->Inner.setFormBody(fields);
		return *this;
	}

	SSERequest& SSERequest::addMultipartField(const QString& name, const QString& value) {
		d->Inner.addMultipartField(name, value);
		return *this;
	}

	SSERequest& SSERequest::addMultipartFile(const QString& name, const QString& filePath) {
		d->Inner.addMultipartFile(name, filePath);
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		替换流帧解码器。

		\note 与 HttpRequest 不同：SSE 请求提交时中心会自动挂载 SseDecoder，
		通常不需要调用本函数。只有在服务端发的并不是标准 SSE、需要自定切分规则时
		才用得上；此时务必确认自定解码器能处理 \c event / \c data 字段，
		否则 \l SSEReply::when() 就无从匹配。

		\a decoder 自定义解码器。
	*/
	SSERequest& SSERequest::setStreamDecoder(std::shared_ptr<IStreamDecoder> decoder) {
		d->Inner.setStreamDecoder(decoder);
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		设置单帧上限，默认 1 MiB。语义与 HttpRequest 上的同名方法一致，
		无需单独说明；这里把它列出来只是为了提醒：服务端如果持续发送空白行
		（保活心跳），帧长度会保持在很低的水平，本项对它是无效的防御。

		\a bytes 单帧上限，单位为字节。
	*/
	SSERequest& SSERequest::setMaxFrameBytes(qint64 bytes) {
		d->Inner.setMaxFrameBytes(bytes);
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		设置总超时毫秒数。

		\warning 本项对 SSE 是危险的。流式连接本来就会持续很久，总超时到达后
		中心会直接掰断连接，表现为“流每隔一段时间就断”。应当使用
		\c{setIdleTimeoutMs()} 控制空闲超时，它能在“对端确实挂了”与“对端只是
		暂时没话说”之间做出正确区分。

		\a ms 总超时毫秒数。
	*/
	SSERequest& SSERequest::setTimeoutMs(qint32 ms) {
		d->Inner.setTimeoutMs(ms);
		return *this;
	}

	SSERequest& SSERequest::setIdleTimeoutMs(qint32 ms) {
		d->Inner.setIdleTimeoutMs(ms);
		return *this;
	}

	SSERequest& SSERequest::setRetryPolicy(const RetryPolicy& policy) {
		d->Inner.setRetryPolicy(policy);
		return *this;
	}

	SSERequest& SSERequest::setRedirectPolicy(RedirectPolicy policy) {
		d->Inner.setRedirectPolicy(policy);
		return *this;
	}

	SSERequest& SSERequest::setFollowRedirectsMax(qint32 count) {
		d->Inner.setFollowRedirectsMax(count);
		return *this;
	}

	SSERequest& SSERequest::setPriority(Priority priority) {
		d->Inner.setPriority(priority);
		return *this;
	}

	SSERequest& SSERequest::setTag(const QString& tag) {
		d->Inner.setTag(tag);
		return *this;
	}

	SSERequest& SSERequest::setProxyOverride(const QUrl& proxy) {
		d->Inner.setProxyOverride(proxy);
		return *this;
	}

	SSERequest& SSERequest::setVerifyTls(bool verify) {
		d->Inner.setVerifyTls(verify);
		return *this;
	}

	SSERequest::Method SSERequest::getMethod() const {
		return d->Inner.getMethod();
	}

	QUrl SSERequest::getUrl() const {
		return d->Inner.getUrl();
	}

	QString SSERequest::getTag() const {
		return d->Inner.getTag();
	}

	/*!
		\since Visindigo 0.17.0

		设置断线续传的起点。提交后它会以 Last-Event-ID 请求头发送，服务端据此
		从该标识之后继续推送，从而避免重连时重复收到已经处理过的事件。

		\a id 续传起点的事件标识。
	*/
	SSERequest& SSERequest::setLastEventId(const QString& id) {
		d->LastEventId = id;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		设置断开后是否自动重连，以及最多重连几次。默认开启，最多 5 次。

		重连时会自动带上最近一次收到的事件标识，因此上层逻辑通常无需关心重连
		过程，只有确实断线时才会感知到。

		\a enabled 是否自动重连。
		\a maxAttempts 最多重连次数。
	*/
	SSERequest& SSERequest::setAutoReconnect(bool enabled, qint32 maxAttempts) {
		d->AutoReconnect = enabled;
		d->MaxReconnectAttempts = maxAttempts;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		返回已设置的续传起点。
	*/
	QString SSERequest::getLastEventId() const {
		return d->LastEventId;
	}

	/*!
		\since Visindigo 0.17.0

		返回是否启用了自动重连。

		return 启用时返回 true。
	*/
	bool SSERequest::isAutoReconnectEnabled() const {
		return d->AutoReconnect;
	}
}
