/*
	Visindigo Project Full AI Generated Declaration

	1. This file was entirely generated by AI. There was almost no human
	   involvement in the design of its API and implementation.
	2. Provided that the usage characteristics of the program corresponding
	   to this code are not substantially changed, anyone is free to make
	   fundamental modifications to this code.
	3. This code does not guarantee implementation consistency across
	   generations; it only guarantees that the corresponding program
	   features remain basically stable.
*/
#include <QtCore/qbytearray.h>
#include <QtCore/qmap.h>
#include <QtCore/qobject.h>
#include <QtCore/qrandom.h>
#include <QtCore/qstring.h>
#include <QtCore/qstringlist.h>
#include <QtCore/qtimer.h>
#include <QtCore/qurl.h>
#include <QtNetwork/qnetworkrequest.h>
#include <QtNetwork/qsslconfiguration.h>
#include <QtWebSockets/qwebsocket.h>
#include "General/Log.h"
#include "Network/HttpTypes.h"
#include "Network/WebSocketRequest.h"
#include "Network/private/WebSocketRequest_p.h"

namespace {
	QString webSocketErrorName(QWebSocketProtocol::CloseCode code) {
		return QString::number(static_cast<int>(code));
	}
}

namespace Visindigo::Network {

	/*!
		\class Visindigo::Network::WebSocketRequest
		\inheaderfile Network/WebSocketRequest.h
		\since Visindigo 0.17.0
		\inmodule Visindigo
		\brief WebSocket 连接描述对象。

		协议栈仍然由 Qt 的 QWebSocket 承担，本类只承载连接参数与重连策略，
		因此它和 HTTP 请求一样是纯值类型，可以自由拷贝。

		\note WebSocket 握手完成后就不再是 HTTP 协议，因此本类不继承
		Visindigo::Network::HttpRequest。两者共享的只有"发起之前"的那一小段
		握手请求，强行拉平继承关系反而会带来一批对 WebSocket 毫无意义的接口。
	*/

	WebSocketRequest::WebSocketRequest() {
		d = new WebSocketRequestPrivate();
	}

	WebSocketRequest::WebSocketRequest(const QUrl& url) {
		d = new WebSocketRequestPrivate();
		d->Url = url;
	}

	VICopyable_Impl(WebSocketRequest);
	VIMoveable_Impl(WebSocketRequest);

	WebSocketRequest::~WebSocketRequest() {
		delete d;
	}

	/*!
		\since Visindigo 0.17.0

		设置连接地址。scheme 应为 ws 或 wss，wss 表示加密连接。
	*/
	WebSocketRequest& WebSocketRequest::setUrl(const QUrl& url) {
		d->Url = url;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		设置握手请求携带的头部，常用于传递认证信息。
	*/
	WebSocketRequest& WebSocketRequest::setHeader(const QString& key, const QString& value) {
		d->Headers.insert(key, value);
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		设置子协议名，会在握手时以 Sec-WebSocket-Protocol 发送。
	*/
	WebSocketRequest& WebSocketRequest::setSubProtocol(const QString& protocol) {
		d->SubProtocol = protocol;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		设置心跳间隔毫秒数，0 表示不发送心跳。

		心跳的价值在于让中间设备保持连接：很多反向代理会静默回收长时间没有数据
		的 TCP 连接，而 WebSocket 空闲时并不产生任何流量。定期发送 ping 可以让
		连接在链路上始终表现为"活跃"。
	*/
	WebSocketRequest& WebSocketRequest::setHeartbeatMs(qint32 ms) {
		d->HeartbeatMs = ms;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		设置意外断开后是否自动重连，以及最多尝试次数。
		调用 close() 主动关闭不会触发重连。
	*/
	WebSocketRequest& WebSocketRequest::setAutoReconnect(bool enabled, qint32 maxAttempts) {
		d->AutoReconnect = enabled;
		d->MaxReconnectAttempts = maxAttempts;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		设置单条消息的字节上限，0 表示不限。超限的消息会被丢弃并触发错误，
		避免单个恶意帧耗尽内存。
	*/
	WebSocketRequest& WebSocketRequest::setMaxMessageBytes(qint64 bytes) {
		d->MaxMessageBytes = bytes;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		设置是否校验证书，默认 \c true。

		\warning 关闭校验等同于放弃中间人防护，仅在明确受控的场景下使用。
	*/
	WebSocketRequest& WebSocketRequest::setVerifyTls(bool verify) {
		d->VerifyTls = verify;
		return *this;
	}

	/*!
		\class Visindigo::Network::WebSocketSession
		\inheaderfile Network/WebSocketRequest.h
		\since Visindigo 0.17.0
		\inmodule Visindigo
		\brief WebSocket 会话句柄。

		相对裸用 QWebSocket，本类补齐的是工程上真正需要的部分：心跳保活、
		指数退避重连、统一的错误类型、消息大小限制，以及把会话纳入请求中心的
		统一取消与统计。

		\note 与 HTTP 句柄不同，会话默认不会自动销毁：WebSocket 是长连接，
		没有"请求结束"的时刻可以触发销毁。请在确定不再需要时调用
		Visindigo::Network::WebSocketSession::close() 或释放对象。
	*/

	/*!
		\fn void Visindigo::Network::WebSocketSession::connected()
		\since Visindigo 0.17.0

		握手完成，连接可用。重连成功后也会再次发出。
	*/

	/*!
		\fn void Visindigo::Network::WebSocketSession::textMessageReceived(const QString& message)
		\since Visindigo 0.17.0

		收到文本消息，\a message 已按 UTF-8 解码。
	*/

	/*!
		\fn void Visindigo::Network::WebSocketSession::binaryMessageReceived(const QByteArray& message)
		\since Visindigo 0.17.0

		收到二进制消息，原样交付、不做任何解释。
	*/

	/*!
		\fn void Visindigo::Network::WebSocketSession::pingReceived(const QByteArray& payload)
		\since Visindigo 0.17.0

		收到对端心跳帧。底层会自动回应 pong，这里只是通知，一般不需要处理。
	*/

	/*!
		\fn void Visindigo::Network::WebSocketSession::reconnecting(qint32 attempt, qint32 delayMs)
		\since Visindigo 0.17.0

		连接断开后正在等待重连。\a attempt 是第几次尝试，\a delayMs 是即将等待的毫秒数。
	*/

	/*!
		\fn void Visindigo::Network::WebSocketSession::disconnected(quint16 closeCode, const QString& reason)
		\since Visindigo 0.17.0

		连接关闭。\a closeCode 是关闭码，\a reason 是对方给出的原因文本，可能为空。

		\note 走到这里说明会话已经停止尝试，不会再自行恢复：重连是断开之前的动作。
	*/

	/*!
		\fn void Visindigo::Network::WebSocketSession::errorOccurred(const HttpError& error)
		\since Visindigo 0.17.0

		发生错误。错误分类与 HTTP 侧共用同一套 \l HttpError，处理逻辑可以直接复用。

		\note 它不表示会话已经结束：开启了自动重连时会话会继续尝试，最终的结局仍然
		由 \l disconnected 或 \l connected 给出。
	*/

	WebSocketSession::WebSocketSession() {
		d = new WebSocketSessionPrivate();
		d->Q = this;
	}

	WebSocketSession::~WebSocketSession() {
		if (d->Socket != nullptr) {
			d->ManualClose = true;
			d->Socket->abort();
		}
		delete d;
	}

	/*!
		\since Visindigo 0.17.0

		返回会话编号，进程内唯一，可用于日志关联。
	*/
	quint64 WebSocketSession::getId() const {
		return d->Id;
	}

	/*!
		\since Visindigo 0.17.0

		判断当前是否处于已连接状态。
	*/
	bool WebSocketSession::isConnected() const {
		return d->Socket != nullptr
			&& d->Socket->state() == QAbstractSocket::ConnectedState;
	}

	/*!
		\since Visindigo 0.17.0

		发送文本消息。未连接时调用不会有任何效果，也不会缓存待发——
		重连后自动补发会带来语义上的不确定性，应交由上层决定。
	*/
	void WebSocketSession::sendText(const QString& text) {
		if (isConnected()) {
			d->Socket->sendTextMessage(text);
		}
	}

	/*!
		\since Visindigo 0.17.0

		发送二进制消息。
	*/
	void WebSocketSession::sendBinary(const QByteArray& data) {
		if (isConnected()) {
			d->Socket->sendBinaryMessage(data);
		}
	}

	/*!
		\since Visindigo 0.17.0

		发送 ping 帧。对端应当回以 pong，后者经 \l pingReceived 信号通知。
	*/
	void WebSocketSession::sendPing(const QByteArray& payload) {
		if (isConnected()) {
			d->Socket->ping(payload);
		}
	}

	/*!
		\since Visindigo 0.17.0

		正常关闭连接。主动关闭会抑制自动重连，因为"调用方想关"与"连接掉了"
		是两种完全不同的情况。
	*/
	void WebSocketSession::close(quint16 code, const QString& reason) {
		d->ManualClose = true;
		if (d->HeartbeatTimer != nullptr) {
			d->HeartbeatTimer->stop();
		}
		if (d->ReconnectTimer != nullptr) {
			d->ReconnectTimer->stop();
		}
		if (d->Socket != nullptr) {
			d->Socket->close(static_cast<QWebSocketProtocol::CloseCode>(code), reason);
		}
	}

	/*!
		\since Visindigo 0.17.0

		立即中断连接，不进行关闭握手。用于对象即将销毁或需要立刻切断的场景。
	*/
	void WebSocketSession::abort() {
		d->ManualClose = true;
		if (d->HeartbeatTimer != nullptr) {
			d->HeartbeatTimer->stop();
		}
		if (d->ReconnectTimer != nullptr) {
			d->ReconnectTimer->stop();
		}
		if (d->Socket != nullptr) {
			d->Socket->abort();
		}
	}

	/*!
		\since Visindigo 0.17.0

		把会话的生命周期绑定到另一个对象：该对象销毁时会话自动关闭。

		这对 WebSocket 尤其必要——长连接不会自己结束，若界面已经销毁而会话仍在，
		就会持续占用连接并接收无人处理的消息。
	*/
	WebSocketSession& WebSocketSession::bindLifecycleTo(QObject* context) {
		if (context != nullptr) {
			QObject::connect(context, &QObject::destroyed, this, [this]() {
				abort();
			});
		}
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		彻底拆掉当前的 QWebSocket。重连之前必须先把旧对象清理干净，否则回调会
		继续从已经失效的连接上送达，造成状态错乱。
	*/
	void WebSocketSessionPrivate::teardownSocket() {
		if (HeartbeatTimer != nullptr) {
			HeartbeatTimer->stop();
		}
		if (Socket != nullptr) {
			QWebSocket* socket = Socket;
			Socket = nullptr;
			socket->disconnect(Q);
			socket->abort();
			socket->deleteLater();
		}
	}

	/*!
		\since Visindigo 0.17.0

		建立连接。首次连接与自动重连走同一条路径，两者的差别只在于是否已在
		重连流程中，因此不单独开一条分支。
	*/
	void WebSocketSessionPrivate::start() {
		if (Request.d->Url.isEmpty()) {
			return;
		}
		ManualClose = false;
		teardownSocket();
		CurrentUrl = Request.d->Url;

		QWebSocket* socket = new QWebSocket(QString(), QWebSocketProtocol::VersionLatest, Q);
		Socket = socket;

		QNetworkRequest handshake(CurrentUrl);
		for (auto it = Request.d->Headers.constBegin(); it != Request.d->Headers.constEnd(); ++it) {
			handshake.setRawHeader(it.key().toUtf8(), it.value().toUtf8());
		}
		if (!Request.d->SubProtocol.isEmpty()) {
			handshake.setRawHeader(QByteArrayLiteral("Sec-WebSocket-Protocol"),
				Request.d->SubProtocol.toUtf8());
		}
		if (!Request.d->VerifyTls) {
			QSslConfiguration configuration = handshake.sslConfiguration();
			configuration.setPeerVerifyMode(QSslSocket::VerifyNone);
			handshake.setSslConfiguration(configuration);
		}

		QObject::connect(socket, &QWebSocket::connected, Q, [this]() {
			// 成功连上之后才把重连计数归零，否则一次失败的握手会把之前的退避
			// 进度白白扔掉，导致每轮都从头开始等。
			ReconnectAttempt = 0;
			emit Q->connected();
			if (Request.d->HeartbeatMs > 0) {
				if (HeartbeatTimer == nullptr) {
					HeartbeatTimer = new QTimer(Q);
					QObject::connect(HeartbeatTimer, &QTimer::timeout, Q, [this]() {
						if (Socket != nullptr && Socket->state() == QAbstractSocket::ConnectedState) {
							Socket->ping();
						}
					});
				}
				HeartbeatTimer->start(Request.d->HeartbeatMs);
			}
		});

		QObject::connect(socket, &QWebSocket::textMessageReceived, Q, [this](const QString& message) {
			if (Request.d->MaxMessageBytes > 0
				&& message.toUtf8().size() > Request.d->MaxMessageBytes) {
				HttpError error;
				error.Type = HttpError::ErrorType::ResponseTooLarge;
				error.Message = QStringLiteral("Received message exceeded the configured size limit");
				emit Q->errorOccurred(error);
				return;
			}
			emit Q->textMessageReceived(message);
		});

		QObject::connect(socket, &QWebSocket::binaryMessageReceived, Q,
			[this](const QByteArray& message) {
				if (Request.d->MaxMessageBytes > 0 && message.size() > Request.d->MaxMessageBytes) {
					HttpError error;
					error.Type = HttpError::ErrorType::ResponseTooLarge;
					error.Message = QStringLiteral("Received message exceeded the configured size limit");
					emit Q->errorOccurred(error);
					return;
				}
				emit Q->binaryMessageReceived(message);
			});

		// QWebSocket 没有独立的 pong 信号，只有带往返耗时的 pong()，
		// 这里把它作为心跳应答转发出去。
		QObject::connect(socket, &QWebSocket::pong, Q,
			[this](quint64, const QByteArray& payload) {
				emit Q->pingReceived(payload);
			});

		QObject::connect(socket, &QWebSocket::errorOccurred, Q,
			[this](QAbstractSocket::SocketError) {
				if (Socket == nullptr) {
					return;
				}
				HttpError error;
				error.Type = HttpError::ErrorType::NetworkUnreachable;
				error.Message = Socket->errorString();
				error.Retryable = Request.d->AutoReconnect;
				emit Q->errorOccurred(error);
			});

		QObject::connect(socket, &QWebSocket::disconnected, Q, [this]() {
			if (HeartbeatTimer != nullptr) {
				HeartbeatTimer->stop();
			}
			emit Q->disconnected(0, QString());
			if (!ManualClose && Request.d->AutoReconnect) {
				scheduleReconnect();
			}
		});

		socket->open(handshake);
		Started = true;
	}

	/*!
		\since Visindigo 0.17.0

		安排一次重连。退避与 HTTP 重试保持同一套思路：指数增长、设上限、叠加抖动，
		使一批同时掉线的客户端不会在同一瞬间一起回来。
	*/
	void WebSocketSessionPrivate::scheduleReconnect() {
		if (ReconnectAttempt >= Request.d->MaxReconnectAttempts) {
			HttpError error;
			error.Type = HttpError::ErrorType::NetworkUnreachable;
			error.Message = QStringLiteral("WebSocket reconnect attempts exhausted");
			emit Q->errorOccurred(error);
			return;
		}
		ReconnectAttempt += 1;
		const qint32 base = 500 * (1 << qMin<qint32>(ReconnectAttempt - 1, 6));
		const qint32 delay = static_cast<qint32>(base * (0.5 + QRandomGenerator::global()->generateDouble() * 0.5));

		if (ReconnectTimer == nullptr) {
			ReconnectTimer = new QTimer(Q);
			ReconnectTimer->setSingleShot(true);
			QObject::connect(ReconnectTimer, &QTimer::timeout, Q, [this]() {
				if (!ManualClose) {
					start();
				}
			});
		}
		teardownSocket();
		emit Q->reconnecting(ReconnectAttempt, delay);
		ReconnectTimer->start(delay);
	}
}
