/*
	Visindigo Project Full AI Generated Declaration

	1. This file was entirely generated by AI. There was almost no human
	   involvement in the design of its API and implementation.
	2. Provided that the usage characteristics of the program corresponding
	   to this code are not substantially changed, anyone is free to make
	   fundamental modifications to this code.
	3. This code does not guarantee implementation consistency across
	   generations; it only guarantees that the corresponding program
	   features remain basically stable.
*/
#include "FileTemplate/SimpleFileTemplate.h"
#include <General/TranslationHost.h>
#include <Utility/FileUtility.h>
#include <QtWidgets/qboxlayout.h>
#include <QtWidgets/qlineedit.h>
#include <QtWidgets/qpushbutton.h>
#include <QtWidgets/qlabel.h>
#include <QtWidgets/qmessagebox.h>

namespace YSSFileExt {
	class SimpleFileTemplateInitWidgetPrivate {
		friend class SimpleFileTemplateInitWidget;
	protected:
		QString Extension;
		QString InitFolder;
		QLineEdit* NameLineEdit = nullptr;
		QLabel* WhereLabel = nullptr;
		QPushButton* CreateButton = nullptr;
	};

	SimpleFileTemplateInitWidget::SimpleFileTemplateInitWidget(const QString& initFolder, const QString& extension, QWidget* parent)
		: YSSCore::Editor::FileTemplateInitWidget(initFolder, parent) {
		d = new SimpleFileTemplateInitWidgetPrivate;
		d->Extension = extension;
		d->InitFolder = initFolder;
		setMinimumWidth(480);
		setWindowTitle(VITR("YSSFileExt::fileProvider.window.title"));

		auto* layout = new QVBoxLayout(this);
		layout->setContentsMargins(12, 12, 12, 12);
		layout->setSpacing(8);

		// 文件名输入
		auto* nameTitleLabel = new QLabel(VITR("YSSFileExt::fileProvider.file.name.title"), this);
		nameTitleLabel->setToolTip(VITR("YSSFileExt::fileProvider.file.name.text").arg(d->Extension));
		d->NameLineEdit = new QLineEdit(this);
		d->NameLineEdit->setPlaceholderText(VITR("YSSFileExt::fileProvider.file.name.title"));
		layout->addWidget(nameTitleLabel);
		layout->addWidget(d->NameLineEdit);

		// 目标路径预览
		d->WhereLabel = new QLabel(this);
		d->WhereLabel->setWordWrap(true);
		layout->addWidget(d->WhereLabel);

		// 创建按钮
		auto* buttonLayout = new QHBoxLayout();
		buttonLayout->addStretch(1);
		d->CreateButton = new QPushButton(VITR("YSSFileExt::fileProvider.window.create"), this);
		d->CreateButton->setMinimumWidth(120);
		d->CreateButton->setEnabled(false);
		buttonLayout->addWidget(d->CreateButton);
		layout->addLayout(buttonLayout);

		auto refresh = [this]() {
			const QString name = d->NameLineEdit->text().trimmed();
			const QString completePath = d->InitFolder + "/" +
				Visindigo::Utility::FileUtility::toLegalFileName(name) + "." + d->Extension;
			if (name.isEmpty()) {
				d->WhereLabel->setText(VITR("YSSFileExt::fileProvider.window.where").arg(completePath));
				d->CreateButton->setEnabled(false);
			}
			else if (!Visindigo::Utility::FileUtility::isFileExist(completePath)) {
				d->WhereLabel->setText(VITR("YSSFileExt::fileProvider.window.where").arg(completePath));
				d->CreateButton->setEnabled(true);
			}
			else {
				d->WhereLabel->setText(VITR("YSSFileExt::fileProvider.window.exists").arg(completePath));
				d->CreateButton->setEnabled(false);
			}
		};
		connect(d->NameLineEdit, &QLineEdit::textChanged, this, refresh);
		connect(d->CreateButton, &QPushButton::clicked, this, [this]() {
			const QString name = d->NameLineEdit->text().trimmed();
			const QString completePath = d->InitFolder + "/" +
				Visindigo::Utility::FileUtility::toLegalFileName(name) + "." + d->Extension;
			if (name.isEmpty() || Visindigo::Utility::FileUtility::isFileExist(completePath)) {
				QMessageBox::warning(this, VITR("YSSFileExt::fileProvider.failed.title"),
					VITR("YSSFileExt::fileProvider.failed.text"));
				return;
			}
			// 创建空文件
			Visindigo::Utility::FileUtility::saveLines(completePath, QStringList());
			emit filePrepared(completePath);
			close();
		});
		refresh();
	}

	SimpleFileTemplateInitWidget::~SimpleFileTemplateInitWidget() {
		delete d;
	}

	SimpleFileTemplateProvider::SimpleFileTemplateProvider(YSSCore::Editor::EditorPlugin* plugin,
		const QString& name, const QString& id, const QString& templateID,
		const QString& templateName, const QString& description, const QStringList& tags, const QString& extension) :
		FileTemplateProvider(name, id, plugin), Extension(extension) {
		setTemplateIconPath(":/resource/cn.yxgeneral.weavestudio.yssfileext/icon.png");
		setTemplateID(templateID);
		setTemplateName(templateName);
		setTemplateDescription(description);
		setTemplateTags(tags);
	}

	YSSCore::Editor::FileTemplateInitWidget* SimpleFileTemplateProvider::fileInitWidget(const QString& initPath) {
		return new SimpleFileTemplateInitWidget(initPath, Extension);
	}
}
