/*
	Visindigo Project Full AI Generated Declaration

	1. This file was entirely generated by AI. There was almost no human
	   involvement in the design of its API and implementation.
	2. Provided that the usage characteristics of the program corresponding
	   to this code are not substantially changed, anyone is free to make
	   fundamental modifications to this code.
	3. This code does not guarantee implementation consistency across
	   generations; it only guarantees that the corresponding program
	   features remain basically stable.
*/
#include "LangServer/IniLangServer.h"
#include <QtCore/qset.h>
#include <QtCore/qlist.h>

namespace YSSFileExt {
	enum class IniTokenType {
		Comment,   // ; 或 # 注释
		Section,   // [name]
		Key,       // 键（= 前）
		Equals,    // =
		Value,     // 值
		Plain,     // 其它
	};

	struct IniToken {
		IniTokenType type = IniTokenType::Plain;
		QString text;
		qint32 line = 0;
		qint32 column = 0;
		qint32 length = 0;
	};

	// 对一行 INI 文本进行词法分析（供着色与诊断共用）。
	static QList<IniToken> lexIniLine(const QString& line, qint32 baseLine, QList<YSSLangDiagnosticData>* diagnostics) {
		QList<IniToken> tokens;
		auto addDiag = [&](const QString& msg, qint32 col, qint32 len, YSSLangDiagnosticData::Severity sev) {
			if (diagnostics) {
				diagnostics->append(YSSLangDiagnosticData(msg, baseLine, col, len, sev));
			}
		};
		auto makeTok = [&](IniTokenType type, qint32 col, qint32 len) {
			IniToken t;
			t.type = type;
			t.line = baseLine;
			t.column = col;
			t.length = len;
			t.text = line.mid(col, len);
			return t;
		};

		const qint32 n = line.length();
		qint32 i = 0;
		while (i < n && line.at(i).isSpace()) ++i;
		if (i >= n) return tokens;

		// 注释
		if (line.at(i) == QLatin1Char(';') || line.at(i) == QLatin1Char('#')) {
			tokens.append(makeTok(IniTokenType::Comment, i, n - i));
			return tokens;
		}
		// 节
		if (line.at(i) == QLatin1Char('[')) {
			const int end = line.indexOf(QLatin1Char(']'), i);
			if (end < 0) {
				addDiag(QStringLiteral("节未闭合（缺少 ]）"), i, n - i, YSSLangDiagnosticData::Severity::Error);
				tokens.append(makeTok(IniTokenType::Section, i, n - i));
				return tokens;
			}
			tokens.append(makeTok(IniTokenType::Section, i, end - i + 1));
			int j = end + 1;
			while (j < n && line.at(j).isSpace()) ++j;
			if (j < n && (line.at(j) == QLatin1Char(';') || line.at(j) == QLatin1Char('#'))) {
				tokens.append(makeTok(IniTokenType::Comment, j, n - j));
			}
			else if (j < n) {
				addDiag(QStringLiteral("节标题后不应有其他内容"), j, n - j, YSSLangDiagnosticData::Severity::Error);
			}
			return tokens;
		}
		// 键 = 值
		const int eq = line.indexOf(QLatin1Char('='), i);
		if (eq < 0) {
			tokens.append(makeTok(IniTokenType::Plain, i, n - i));
			addDiag(QStringLiteral("缺少 '=' 分隔符（应为 键=值）"), i, n - i,
				YSSLangDiagnosticData::Severity::Warning);
			return tokens;
		}
		int keyEnd = eq;
		while (keyEnd > i && line.at(keyEnd - 1).isSpace()) --keyEnd;
		if (keyEnd <= i) {
			addDiag(QStringLiteral("键名不能为空"), i, eq - i, YSSLangDiagnosticData::Severity::Error);
		}
		tokens.append(makeTok(IniTokenType::Key, i, keyEnd - i));
		tokens.append(makeTok(IniTokenType::Equals, eq, 1));
		int vs = eq + 1;
		while (vs < n && line.at(vs).isSpace()) ++vs;
		if (vs < n && (line.at(vs) == QLatin1Char(';') || line.at(vs) == QLatin1Char('#'))) {
			tokens.append(makeTok(IniTokenType::Comment, vs, n - vs));
		}
		else {
			tokens.append(makeTok(IniTokenType::Value, vs, n - vs));
		}
		return tokens;
	}

	// ---------------------------------------------------------------------------
	// INI 全文档分析
	// ---------------------------------------------------------------------------
	static void analyzeIniLines(const QStringList& lines, QList<YSSLangDiagnosticData>* diags) {
		if (!diags) return;
		QSet<QString> seenSections;
		QMap<QString, QSet<QString>> sectionKeys;
		QString currentSection;
		for (qint32 i = 0; i < lines.size(); ++i) {
			const QString& line = lines.at(i);
			const QList<IniToken> tokens = lexIniLine(line, i, diags);
			if (tokens.isEmpty()) continue;
			const IniToken& first = tokens.first();
			if (first.type == IniTokenType::Section) {
				QString name = first.text.mid(1);
				if (name.endsWith(QLatin1Char(']'))) name.chop(1);
				name = name.trimmed();
				if (name.length() >= 2 && name.startsWith(QLatin1Char('"')) && name.endsWith(QLatin1Char('"'))) {
					name = name.mid(1, name.length() - 2);
				}
				if (seenSections.contains(name)) {
					diags->append(YSSLangDiagnosticData(QStringLiteral("节 \"%1\" 重复定义").arg(name),
						i, first.column, qMax<qint32>(first.length, 1),
						YSSLangDiagnosticData::Severity::Warning, QStringLiteral("INI-DUP-SECTION")));
				}
				else {
					seenSections.insert(name);
				}
				currentSection = name;
			}
			else if (first.type == IniTokenType::Key) {
				QString key = first.text.trimmed();
				if (key.length() >= 2
					&& ((key.startsWith(QLatin1Char('"')) && key.endsWith(QLatin1Char('"')))
						|| (key.startsWith(QLatin1Char('\'')) && key.endsWith(QLatin1Char('\''))))) {
					key = key.mid(1, key.length() - 2);
				}
				if (key.isEmpty()) continue;
				if (sectionKeys[currentSection].contains(key)) {
					diags->append(YSSLangDiagnosticData(QStringLiteral("节 %1 中键 \"%2\" 重复").arg(
						currentSection.isEmpty() ? QStringLiteral("顶层") : currentSection, key),
						i, first.column, qMax<qint32>(key.length(), 1),
						YSSLangDiagnosticData::Severity::Warning, QStringLiteral("INI-DUP-KEY")));
				}
				else {
					sectionKeys[currentSection].insert(key);
				}
			}
		}
	}

	// ---------------------------------------------------------------------------
	// 着色
	// ---------------------------------------------------------------------------
	static void colorIniLine(YSSConfigLangHighlighter* highlighter, const QString& text) {
		if (text.isEmpty()) return;
		highlighter->setFormatWithColorKey(0, text.length(), "PlainText");
		const QList<IniToken> tokens = lexIniLine(text, 0, nullptr);
		for (const IniToken& t : tokens) {
			switch (t.type) {
			case IniTokenType::Comment:
				highlighter->setFormatWithColorKey(t.column, t.length, "Comment");
				break;
			case IniTokenType::Section:
				highlighter->setFormatWithColorKey(t.column, t.length, "Section");
				break;
			case IniTokenType::Key:
				highlighter->setFormatWithColorKey(t.column, t.length, "Key");
				break;
			case IniTokenType::Value:
				highlighter->setFormatWithColorKey(t.column, t.length, "String");
				break;
			default:
				break; // Equals / Plain 保持 PlainText
			}
		}
	}

	// ---------------------------------------------------------------------------
	// IniLangServer
	// ---------------------------------------------------------------------------
	/*!
		\class YSSFileExt::IniLangServer
		\brief INI 语言服务器.
		\since YSS 0.17.0
		\inmodule YSSFileExt

		主题加载、跟随程序主题、样式样本与高亮器创建都由 YSSConfigLangServer 完成，
		这里只给出本语言的分析函数与着色函数。
	*/
	IniLangServer::IniLangServer(YSSCore::Editor::EditorPlugin* plugin) :
		YSSConfigLangServer(plugin,
			"YSS File Extension INI Language Server", "YSSFileExt_Ini", "Ini", { "ini" },
			{
				":/resource/cn.yxgeneral.yayinstorystudio.plugin.yssfileext/syntaxColorTheme/ini_dark_2024.json",
				":/resource/cn.yxgeneral.yayinstorystudio.plugin.yssfileext/syntaxColorTheme/ini_light_2024.json"
			},
			":/resource/cn.yxgeneral.yayinstorystudio.plugin.yssfileext/syntaxColorTheme/templateIni.ini",
			&analyzeIniLines, &colorIniLine) {
	}
}
