/*
	Visindigo Project Full AI Generated Declaration

	1. This file was entirely generated by AI. There was almost no human
	   involvement in the design of its API and implementation.
	2. Provided that the usage characteristics of the program corresponding
	   to this code are not substantially changed, anyone is free to make
	   fundamental modifications to this code.
	3. This code does not guarantee implementation consistency across
	   generations; it only guarantees that the corresponding program
	   features remain basically stable.
*/
#include "LangServer/JsonLangServer.h"
#include "LangServer/JsonDocument.h"
#include <Editor/TextEdit.h>
#include <Editor/FileEditWidget.h>
#include <Editor/ColorThemeProvider.h>
#include <Widgets/ThemeManager.h>
#include <Utility/FileUtility.h>
#include <QtGui/qfont.h>
#include <QtCore/qurl.h>
#include <QtCore/qmap.h>

namespace YSSFileExt {
	class JsonLangServerPrivate {
		friend class JsonLangServer;
	protected:
		static QMap<QString, JsonLangDocument*> DocumentMap;
	};
	QMap<QString, JsonLangDocument*> JsonLangServerPrivate::DocumentMap;

	/*!
		\since YSS 0.16.0
		\a plugin 所属编辑器插件。

		构造函数：注册 Visindigo 2024（Dark/Light）静态颜色主题，并跟随程序主题自动切换；
		设置默认当前主题（浅色程序主题 -> Visindigo Light 2024，否则 Dark）。
	*/
	JsonLangServer::JsonLangServer(YSSCore::Editor::EditorPlugin* plugin) :
		YSSCore::Editor::LangServer("YSS File Extension Json Language Server",
			"YSSFileExt_Json", plugin, "Json", { "json", "yssp" }) {
		connect(VISTM, &Visindigo::Widgets::ThemeManager::programThemeChanged, this, [this]() {
			if (VISTM->getCurrentColorTheme() == "Dark") {
				if (getColorThemeProvider()->getCurrentTheme() == "Visindigo Light 2024") {
					getColorThemeProvider()->setCurrentTheme("Visindigo Dark 2024");
				}
			}
			else if (VISTM->getCurrentColorTheme() == "Light") {
				if (getColorThemeProvider()->getCurrentTheme() == "Visindigo Dark 2024") {
					getColorThemeProvider()->setCurrentTheme("Visindigo Light 2024");
				}
			}
			});
		getColorThemeProvider()->parseStaticThemeFrom(
			Visindigo::Utility::FileUtility::readAll(
				":/resource/cn.yxgeneral.weavestudio.yssfileext/syntaxColorTheme/visindigo_dark_2024.json"));
		getColorThemeProvider()->parseStaticThemeFrom(
			Visindigo::Utility::FileUtility::readAll(
				":/resource/cn.yxgeneral.weavestudio.yssfileext/syntaxColorTheme/visindigo_light_2024.json"));
		// 样式样本：用于颜色主题设置页的预览编辑器展示全部着色元素
		getColorThemeProvider()->setTemplateTextPath(
			":/resource/cn.yxgeneral.weavestudio.yssfileext/syntaxColorTheme/templateFile.json");
		if (getPlugin()->getPluginConfig()->getString("_yss_auto_.LangServer." + getModuleID() + ".CurrentTheme").isEmpty()) {
			getPlugin()->getPluginConfig()->setString("_yss_auto_.LangServer." + getModuleID() + ".CurrentTheme",
				VISTM->getCurrentColorTheme() == "Light" ? "Visindigo Light 2024" : "Visindigo Dark 2024");
			getPlugin()->savePluginConfig();
		}
	}

	YSSCore::Editor::SyntaxHighlighter* JsonLangServer::createHighlighter(YSSCore::Editor::TextEdit* doc) {
		return new JsonLangHighlighter(doc);
	}

	void JsonLangServer::setJsonDocument(const QString& filePath, JsonLangDocument* doc) {
		JsonLangServerPrivate::DocumentMap.insert(filePath, doc);
	}
	void JsonLangServer::deleteJsonDocument(const QString& filePath) {
		JsonLangDocument* doc = JsonLangServerPrivate::DocumentMap.value(filePath, nullptr);
		if (doc) {
			delete doc;
		}
		JsonLangServerPrivate::DocumentMap.remove(filePath);
	}
	void JsonLangServer::renameJsonDocument(const QString& oldFilePath, const QString& newFilePath) {
		JsonLangDocument* doc = JsonLangServerPrivate::DocumentMap.value(oldFilePath, nullptr);
		if (doc) {
			JsonLangServerPrivate::DocumentMap.remove(oldFilePath);
			JsonLangServerPrivate::DocumentMap.insert(newFilePath, doc);
		}
	}
	JsonLangDocument* JsonLangServer::getJsonDocument(const QString& filePath) {
		return JsonLangServerPrivate::DocumentMap.value(filePath, nullptr);
	}

	// ---------------------------------------------------------------------------
	// JsonLangHighlighter
	// ---------------------------------------------------------------------------
	class JsonLangHighlighterPrivate {
		friend class JsonLangHighlighter;
	protected:
		QString FilePath;
		JsonLangDocument* Document = nullptr;
		QMap<QString, YSSCore::Editor::StyleData> CurrentTheme;
	};

	JsonLangHighlighter::JsonLangHighlighter(YSSCore::Editor::TextEdit* parent) : SyntaxHighlighter(parent) {
		d = new JsonLangHighlighterPrivate();
		d->FilePath = parent->getFilePath();
		JsonLangDocument* doc = new JsonLangDocument();
		JsonLangServer::setJsonDocument(parent->getFilePath(), doc);
		d->Document = JsonLangServer::getJsonDocument(d->FilePath);
		connect(d->Document, &JsonLangDocument::contentChanged, this, &JsonLangHighlighter::rehighlight_s);
		connect(parent, &YSSCore::Editor::FileEditWidget::fileRenamed, this, [this](const QString& oldPath, const QString& newPath) {
			JsonLangServer::renameJsonDocument(oldPath, newPath);
			d->FilePath = newPath;
			});
	}

	JsonLangHighlighter::~JsonLangHighlighter() {
		JsonLangServer::deleteJsonDocument(d->FilePath);
		delete d;
	}

	void JsonLangHighlighter::onThemeChanged(const QMap<QString, YSSCore::Editor::StyleData>& theme) {
		d->CurrentTheme = theme;
	}

	void JsonLangHighlighter::onBlockAdded(qint32 startBlockNumber, qint32 count) {
		if (d->Document) {
			d->Document->onLinesAdded(startBlockNumber, count);
		}
	}

	void JsonLangHighlighter::onBlockRemoved(qint32 startBlockNumber, qint32 count) {
		if (d->Document) {
			d->Document->onLinesRemoved(startBlockNumber, count);
		}
	}

	void JsonLangHighlighter::setFormatWithColorKey(int start, int count, const QString& styleKey) {
		YSSCore::Editor::StyleData styleData = d->CurrentTheme.value(styleKey, YSSCore::Editor::StyleData());
		QTextCharFormat format;
		format.setForeground(styleData.getTextColor());
		if (styleData.isBgColorEnabled()) {
			format.setBackground(styleData.getBgColor());
		}
		if (styleData.getUnderlineType() != YSSCore::Editor::StyleData::UnderlineType::NoUnderline) {
			format.setUnderlineColor(styleData.getLineColor());
			format.setUnderlineStyle(QTextCharFormat::UnderlineStyle(styleData.getUnderlineType()));
		}
		format.setFontWeight(styleData.isBold() ? QFont::Bold : QFont::Normal);
		format.setFontItalic(styleData.isItalic());
		setFormat(start, count, format);
	}

	// 着色逻辑：字符串值 -> String，对象键 -> SpecialString，数字 -> Number，true/false/null -> Keyword，
	// 结构符号（{}[]: 等）保持 PlainText。与 Visindigo 2024 主题的样式键一一对应。
	static void colorLine(JsonLangHighlighter* highlighter, const QString& text) {
		if (text.isEmpty()) return;
		highlighter->setFormatWithColorKey(0, text.length(), "PlainText");
		const QList<JsonToken> tokens = lexJsonLine(text, 0, nullptr);
		for (qint32 i = 0; i < tokens.size(); ++i) {
			const JsonToken& t = tokens.at(i);
			switch (t.type) {
			case JsonTokenType::String: {
				// 键：其后（忽略空白）紧跟 ':' 的字符串视作对象键
				bool isKey = (i + 1 < tokens.size() && tokens.at(i + 1).type == JsonTokenType::Colon);
				highlighter->setFormatWithColorKey(t.column, t.length, isKey ? "SpecialString" : "String");
				break;
			}
			case JsonTokenType::Number:
				highlighter->setFormatWithColorKey(t.column, t.length, "Number");
				break;
			case JsonTokenType::True:
			case JsonTokenType::False:
			case JsonTokenType::Null:
				highlighter->setFormatWithColorKey(t.column, t.length, "Keyword");
				break;
			default:
				break; // 结构符号保持 PlainText
			}
		}
	}

	void JsonLangHighlighter::onBlockChanged(const QString& text, int blockNumber) {
		if (!d->Document) return;
		d->Document->onSyntaxHighlighter(text, blockNumber);
		colorLine(this, text);
		const QList<JsonLangDiagnosticData> diagnostics = d->Document->getDiagnostics(blockNumber);
		for (const JsonLangDiagnosticData& diagnostic : diagnostics) {
			DiagnosticTransform(diagnostic);
		}
	}

	void JsonLangHighlighter::DiagnosticTransform(const JsonLangDiagnosticData& diagnostic) {
		const int column = diagnostic.getColumn();
		const int length = qMax(diagnostic.getLength(), 1);
		if (column < 0) return;
		const QString code = QString("JSON-%1").arg(QString::number((qint32)diagnostic.getType(), 16).toUpper());
		if (diagnostic.getType() >= JsonLangDiagnosticData::UnknownWarning) {
			createWarningMessage(diagnostic.getMessage(), column, length, code, QUrl(), diagnostic.getFixAdvice());
		}
		else if (diagnostic.getType() >= JsonLangDiagnosticData::UnknownError) {
			createErrorMessage(diagnostic.getMessage(), column, length, code, QUrl(), diagnostic.getFixAdvice());
		}
		else {
			createInfoMessage(diagnostic.getMessage(), column, length, code, QUrl(), diagnostic.getFixAdvice());
		}
	}
}