/*
	Visindigo Project Full AI Generated Declaration

	1. This file was entirely generated by AI. There was almost no human
	   involvement in the design of its API and implementation.
	2. Provided that the usage characteristics of the program corresponding
	   to this code are not substantially changed, anyone is free to make
	   fundamental modifications to this code.
	3. This code does not guarantee implementation consistency across
	   generations; it only guarantees that the corresponding program
	   features remain basically stable.
*/
#include "LangServer/JsonDocument.h"
#include <QtCore/qhash.h>
#include <QtCore/qset.h>

namespace YSSFileExt {
	// ---------------------------------------------------------------------------
	// JsonLangDiagnosticData
	// ---------------------------------------------------------------------------
	JsonLangDiagnosticData::JsonLangDiagnosticData() {}
	JsonLangDiagnosticData::JsonLangDiagnosticData(const QString& message, qint32 line, qint32 column, qint32 length,
		DiagnosticType type, const QString& fixAdvice) :
		message(message), line(line), column(column), length(length), type(type), fixAdvice(fixAdvice) {}
	QString JsonLangDiagnosticData::getMessage() const { return message; }
	qint32 JsonLangDiagnosticData::getLine() const { return line; }
	qint32 JsonLangDiagnosticData::getColumn() const { return column; }
	qint32 JsonLangDiagnosticData::getLength() const { return length; }
	QString JsonLangDiagnosticData::getFixAdvice() const { return fixAdvice; }
	JsonLangDiagnosticData::DiagnosticType JsonLangDiagnosticData::getType() const { return type; }

	// ---------------------------------------------------------------------------
	// 词法分析
	// ---------------------------------------------------------------------------
	static bool isDigitChar(QChar c) { return c >= QLatin1Char('0') && c <= QLatin1Char('9'); }
	static bool isHexChar(QChar c) {
		return (c >= QLatin1Char('0') && c <= QLatin1Char('9'))
			|| (c >= QLatin1Char('a') && c <= QLatin1Char('f'))
			|| (c >= QLatin1Char('A') && c <= QLatin1Char('F'));
	}

	QList<JsonToken> lexJsonLine(const QString& line, qint32 baseLine, QList<JsonLangDiagnosticData>* diagnostics) {
		QList<JsonToken> tokens;
		auto addDiag = [&](const QString& msg, qint32 col, qint32 len, JsonLangDiagnosticData::DiagnosticType type) {
			if (diagnostics) {
				diagnostics->append(JsonLangDiagnosticData(msg, baseLine, col, len, type));
			}
		};
		auto makePunct = [&](JsonTokenType type, qint32 col) {
			JsonToken t;
			t.type = type;
			t.line = baseLine;
			t.column = col;
			t.length = 1;
			t.text = line.mid(col, 1);
			return t;
		};

		const qint32 n = line.length();
		qint32 i = 0;
		while (i < n) {
			const QChar ch = line.at(i);
			if (ch.isSpace()) { ++i; continue; } // 空格 / 制表 / 回车等

			const qint32 start = i;
			if (ch == QLatin1Char('"')) {
				// 字符串
				++i;
				bool terminated = false;
				bool escapeError = false;
				while (i < n) {
					const QChar c = line.at(i);
					if (c == QLatin1Char('\\')) {
						if (i + 1 >= n) { // 行尾孤立反斜杠 -> 未闭合
							break;
						}
						const QChar e = line.at(i + 1);
						if (e == QLatin1Char('u')) {
							if (i + 5 >= n || !isHexChar(line.at(i + 2)) || !isHexChar(line.at(i + 3))
								|| !isHexChar(line.at(i + 4)) || !isHexChar(line.at(i + 5))) {
								addDiag(QStringLiteral("无效的 Unicode 转义（\\u 后应为 4 位十六进制数字）"),
									i, qMin<qint32>(6, n - i), JsonLangDiagnosticData::InvalidEscape);
								escapeError = true;
								i += 2;
								continue;
							}
							i += 6;
							continue;
						}
						switch (e.unicode()) {
						case '"': case '\\': case '/': case 'b': case 'f': case 'n': case 'r': case 't':
							i += 2;
							continue;
						default:
							addDiag(QStringLiteral("无效的转义字符 '\\%1'").arg(e),
								i, 2, JsonLangDiagnosticData::InvalidEscape);
							escapeError = true;
							i += 2;
							continue;
						}
					}
					if (c == QLatin1Char('"')) {
						terminated = true;
						++i;
						break;
					}
					if (c.unicode() < 0x20) { // JSON 字符串内不允许原始控制字符
						addDiag(QStringLiteral("字符串内不允许出现控制字符"),
							i, 1, JsonLangDiagnosticData::UnexpectedToken);
					}
					++i;
				}
				JsonToken t;
				t.type = JsonTokenType::String;
				t.line = baseLine;
				t.column = start;
				t.length = i - start;
				t.text = line.mid(start, i - start);
				if (!terminated && !escapeError) {
					addDiag(QStringLiteral("字符串未闭合（缺少结尾引号）"),
						start, t.length, JsonLangDiagnosticData::UnterminatedString);
				}
				tokens.append(t);
				continue;
			}

			if (ch == QLatin1Char('{')) { tokens.append(makePunct(JsonTokenType::LBrace, start)); ++i; continue; }
			if (ch == QLatin1Char('}')) { tokens.append(makePunct(JsonTokenType::RBrace, start)); ++i; continue; }
			if (ch == QLatin1Char('[')) { tokens.append(makePunct(JsonTokenType::LBracket, start)); ++i; continue; }
			if (ch == QLatin1Char(']')) { tokens.append(makePunct(JsonTokenType::RBracket, start)); ++i; continue; }
			if (ch == QLatin1Char(':')) { tokens.append(makePunct(JsonTokenType::Colon, start)); ++i; continue; }
			if (ch == QLatin1Char(',')) { tokens.append(makePunct(JsonTokenType::Comma, start)); ++i; continue; }

			if (ch == QLatin1Char('-') || isDigitChar(ch)) {
				// 数字
				bool ok = true;
				qint32 p = i;
				// 可选的负号
				if (line.at(p) == QLatin1Char('-')) {
					++p;
					if (p >= n || !isDigitChar(line.at(p))) ok = false;
				}
				// 整数部分
				if (ok) {
					if (line.at(p) == QLatin1Char('0')) {
						++p; // 消费 '0'
						if (p < n && isDigitChar(line.at(p))) {
							ok = false; // 前导零 0123
							while (p < n && isDigitChar(line.at(p))) ++p;
						}
					}
					else {
						while (p < n && isDigitChar(line.at(p))) ++p;
					}
				}
				// 小数部分
				if (ok && p < n && line.at(p) == QLatin1Char('.')) {
					++p;
					if (p >= n || !isDigitChar(line.at(p))) ok = false;
					else while (p < n && isDigitChar(line.at(p))) ++p;
				}
				// 指数部分
				if (ok && p < n && (line.at(p) == QLatin1Char('e') || line.at(p) == QLatin1Char('E'))) {
					++p;
					if (p < n && (line.at(p) == QLatin1Char('+') || line.at(p) == QLatin1Char('-'))) ++p;
					if (p >= n || !isDigitChar(line.at(p))) ok = false;
					else while (p < n && isDigitChar(line.at(p))) ++p;
				}
				// 紧跟字母或多余点号，如 12abc / 1.2.3
				if (p < n && (line.at(p).isLetter() || line.at(p) == QLatin1Char('.'))) {
					while (p < n && (line.at(p).isLetterOrNumber() || line.at(p) == QLatin1Char('.')
						|| line.at(p) == QLatin1Char('_') || line.at(p) == QLatin1Char('+') || line.at(p) == QLatin1Char('-'))) {
						++p;
					}
					ok = false;
				}
				i = p;
				JsonToken t;
				t.line = baseLine;
				t.column = start;
				t.length = i - start;
				t.text = line.mid(start, i - start);
				if (ok) {
					t.type = JsonTokenType::Number;
				}
				else {
					t.type = JsonTokenType::Unexpected;
					addDiag(QStringLiteral("无效的数字 '%1'").arg(t.text),
						start, t.length, JsonLangDiagnosticData::InvalidNumber);
				}
				tokens.append(t);
				continue;
			}

			if (ch == QLatin1Char('t') || ch == QLatin1Char('f') || ch == QLatin1Char('n')) {
				// 字面量 true / false / null
				QString literal;
				JsonTokenType literalType = JsonTokenType::Unexpected;
				if (ch == QLatin1Char('t') && line.mid(i, 4) == QStringLiteral("true")) {
					literal = QStringLiteral("true"); literalType = JsonTokenType::True;
				}
				else if (ch == QLatin1Char('f') && line.mid(i, 5) == QStringLiteral("false")) {
					literal = QStringLiteral("false"); literalType = JsonTokenType::False;
				}
				else if (ch == QLatin1Char('n') && line.mid(i, 4) == QStringLiteral("null")) {
					literal = QStringLiteral("null"); literalType = JsonTokenType::Null;
				}
				if (!literal.isEmpty()) {
					JsonToken t;
					t.type = literalType;
					t.line = baseLine;
					t.column = start;
					t.length = literal.length();
					t.text = literal;
					tokens.append(t);
					i += literal.length();
					continue;
				}
				while (i < n && line.at(i).isLetter()) ++i;
				JsonToken t;
				t.type = JsonTokenType::Unexpected;
				t.line = baseLine;
				t.column = start;
				t.length = i - start;
				t.text = line.mid(start, i - start);
				addDiag(QStringLiteral("无效的字面量 '%1'").arg(t.text),
					start, t.length, JsonLangDiagnosticData::UnexpectedToken);
				tokens.append(t);
				continue;
			}

			// 其它意外字符
			JsonToken t;
			t.type = JsonTokenType::Unexpected;
			t.line = baseLine;
			t.column = start;
			t.length = 1;
			t.text = line.mid(start, 1);
			addDiag(QStringLiteral("意外的字符 '%1'").arg(t.text),
				start, 1, JsonLangDiagnosticData::UnexpectedToken);
			tokens.append(t);
			++i;
		}
		return tokens;
	}

	// ---------------------------------------------------------------------------
	// 语法分析（递归下降）
	// ---------------------------------------------------------------------------
	namespace {
		struct JsonParseContext {
			const QList<JsonToken>* tokens;
			qint32 pos = 0;
			QList<JsonLangDiagnosticData>* diagnostics;
		};

		inline const JsonToken& peekToken(const JsonParseContext& ctx) {
			return ctx.tokens->at(qMin<qint32>(ctx.pos, ctx.tokens->size() - 1));
		}
		inline void advanceToken(JsonParseContext& ctx) {
			if (ctx.pos < ctx.tokens->size() - 1) ++ctx.pos;
		}

		QString describeToken(const JsonToken& t) {
			switch (t.type) {
			case JsonTokenType::LBrace: return QStringLiteral("'{'");
			case JsonTokenType::RBrace: return QStringLiteral("'}'");
			case JsonTokenType::LBracket: return QStringLiteral("'['");
			case JsonTokenType::RBracket: return QStringLiteral("']'");
			case JsonTokenType::Colon: return QStringLiteral("':'");
			case JsonTokenType::Comma: return QStringLiteral("','");
			case JsonTokenType::EndOfFile: return QStringLiteral("文件结束");
			case JsonTokenType::String: return QStringLiteral("字符串");
			case JsonTokenType::Number: return QStringLiteral("数字");
			case JsonTokenType::True: case JsonTokenType::False: case JsonTokenType::Null:
				return QStringLiteral("字面量");
			default:
				return QStringLiteral("'%1'").arg(t.text.isEmpty() ? QStringLiteral("?") : t.text.left(8));
			}
		}

		void diagAt(JsonParseContext& ctx, JsonLangDiagnosticData::DiagnosticType type,
			const QString& message, const JsonToken& at, const QString& fixAdvice = QString()) {
			ctx.diagnostics->append(JsonLangDiagnosticData(
				message, at.line, at.column, qMax<qint32>(at.length, 1), type, fixAdvice));
		}

		void parseValue(JsonParseContext& ctx);
		void parseObject(JsonParseContext& ctx, const JsonToken& open);
		void parseArray(JsonParseContext& ctx, const JsonToken& open);

		void parseValue(JsonParseContext& ctx) {
			const JsonToken& t = peekToken(ctx);
			switch (t.type) {
			case JsonTokenType::LBrace:
				parseObject(ctx, t);
				return;
			case JsonTokenType::LBracket:
				parseArray(ctx, t);
				return;
			case JsonTokenType::String:
			case JsonTokenType::Number:
			case JsonTokenType::True:
			case JsonTokenType::False:
			case JsonTokenType::Null:
				advanceToken(ctx);
				return;
			case JsonTokenType::Unexpected:
				// 词法层已报告，这里仅消费，避免连环报错
				advanceToken(ctx);
				return;
			case JsonTokenType::EndOfFile:
				// 不消费；由括号平衡检查报告“未闭合”
				return;
			default:
				// '}' ']' ',' ':' 出现在值位置：报告后消费，保证解析前进
				diagAt(ctx, JsonLangDiagnosticData::ExpectedValue,
					QStringLiteral("期望一个值，但遇到 %1").arg(describeToken(t)), t,
					QStringLiteral("请提供一个合法的 JSON 值（字符串、数字、true/false/null、对象或数组）"));
				advanceToken(ctx);
				return;
			}
		}

		void parseObject(JsonParseContext& ctx, const JsonToken& open) {
			Q_UNUSED(open);
			advanceToken(ctx); // 消费 '{'
			QHash<QString, bool> seenKeys;
			bool expectComma = false;
			while (true) {
				const JsonToken& t = peekToken(ctx);
				if (t.type == JsonTokenType::EndOfFile) return; // 由括号平衡检查报告
				if (t.type == JsonTokenType::RBrace) { advanceToken(ctx); return; }
				if (t.type == JsonTokenType::RBracket) {
					diagAt(ctx, JsonLangDiagnosticData::UnexpectedToken,
						QStringLiteral("期望 '}' 但遇到 ']'"), t);
					advanceToken(ctx);
					return;
				}
				if (expectComma) {
					if (t.type == JsonTokenType::Comma) {
						advanceToken(ctx);
						const JsonToken& nxt = peekToken(ctx);
						if (nxt.type == JsonTokenType::RBrace || nxt.type == JsonTokenType::RBracket
							|| nxt.type == JsonTokenType::EndOfFile) {
							diagAt(ctx, JsonLangDiagnosticData::TrailingComma,
								QStringLiteral("多余的逗号"), t, QStringLiteral("请删除此逗号"));
						}
						expectComma = false;
						continue;
					}
					diagAt(ctx, JsonLangDiagnosticData::ExpectedComma,
						QStringLiteral("期望 ',' 但遇到 %1").arg(describeToken(t)), t,
						QStringLiteral("请在两个成员之间添加 ','"));
					expectComma = false;
					continue;
				}
				// 期望键名
				if (t.type == JsonTokenType::String) {
					QString keyText = t.text;
					if (keyText.length() >= 2 && keyText.startsWith(QLatin1Char('"')) && keyText.endsWith(QLatin1Char('"'))) {
						keyText = keyText.mid(1, keyText.length() - 2);
					}
					if (seenKeys.contains(t.text)) {
						diagAt(ctx, JsonLangDiagnosticData::DuplicateKey,
							QStringLiteral("重复的键名 \"%1\"").arg(keyText), t,
							QStringLiteral("请为其中一个键使用不同的名称"));
					}
					else {
						seenKeys.insert(t.text, true);
					}
					advanceToken(ctx);
					const JsonToken& c = peekToken(ctx);
					if (c.type == JsonTokenType::Colon) {
						advanceToken(ctx);
						parseValue(ctx);
					}
					else if (c.type == JsonTokenType::EndOfFile) {
						return; // 由括号平衡检查报告
					}
					else {
						diagAt(ctx, JsonLangDiagnosticData::ExpectedColon,
							QStringLiteral("期望 ':' 但遇到 %1").arg(describeToken(c)), c,
							QStringLiteral("请在键名后添加 ':'"));
						advanceToken(ctx);
						// 宽松恢复：跳到逗号/右括号/结束
						while (true) {
							const JsonToken& s = peekToken(ctx);
							if (s.type == JsonTokenType::Comma || s.type == JsonTokenType::RBrace
								|| s.type == JsonTokenType::RBracket || s.type == JsonTokenType::EndOfFile) break;
							advanceToken(ctx);
						}
					}
					expectComma = true;
					continue;
				}
				// 键名位置出现其它单元
				diagAt(ctx, JsonLangDiagnosticData::ExpectedKey,
					QStringLiteral("期望键名（字符串）但遇到 %1").arg(describeToken(t)), t,
					QStringLiteral("对象键名必须是字符串"));
				advanceToken(ctx);
			}
		}

		void parseArray(JsonParseContext& ctx, const JsonToken& open) {
			Q_UNUSED(open);
			advanceToken(ctx); // 消费 '['
			bool expectComma = false;
			while (true) {
				const JsonToken& t = peekToken(ctx);
				if (t.type == JsonTokenType::EndOfFile) return; // 由括号平衡检查报告
				if (t.type == JsonTokenType::RBracket) { advanceToken(ctx); return; }
				if (t.type == JsonTokenType::RBrace) {
					diagAt(ctx, JsonLangDiagnosticData::UnexpectedToken,
						QStringLiteral("期望 ']' 但遇到 '}'"), t);
					advanceToken(ctx);
					return;
				}
				if (expectComma) {
					if (t.type == JsonTokenType::Comma) {
						advanceToken(ctx);
						const JsonToken& nxt = peekToken(ctx);
						if (nxt.type == JsonTokenType::RBracket || nxt.type == JsonTokenType::RBrace
							|| nxt.type == JsonTokenType::EndOfFile) {
							diagAt(ctx, JsonLangDiagnosticData::TrailingComma,
								QStringLiteral("多余的逗号"), t, QStringLiteral("请删除此逗号"));
						}
						expectComma = false;
						continue;
					}
					diagAt(ctx, JsonLangDiagnosticData::ExpectedComma,
						QStringLiteral("期望 ',' 但遇到 %1").arg(describeToken(t)), t,
						QStringLiteral("请在两个元素之间添加 ','"));
					expectComma = false;
					continue;
				}
				parseValue(ctx);
				expectComma = true;
			}
		}

		void checkBracketBalance(const QList<JsonToken>& tokens, QList<JsonLangDiagnosticData>& diagnostics) {
			struct Open { JsonTokenType type; const JsonToken* tok; };
			QList<Open> stack;
			for (const JsonToken& t : tokens) {
				if (t.type == JsonTokenType::LBrace || t.type == JsonTokenType::LBracket) {
					stack.append({ t.type, &t });
				}
				else if (t.type == JsonTokenType::RBrace) {
					if (!stack.isEmpty() && stack.last().type == JsonTokenType::LBrace) {
						stack.removeLast();
					}
					else {
						diagnostics.append(JsonLangDiagnosticData(
							QStringLiteral("意外的 '}'，没有匹配的 '{'"),
							t.line, t.column, 1, JsonLangDiagnosticData::UnexpectedToken));
					}
				}
				else if (t.type == JsonTokenType::RBracket) {
					if (!stack.isEmpty() && stack.last().type == JsonTokenType::LBracket) {
						stack.removeLast();
					}
					else {
						diagnostics.append(JsonLangDiagnosticData(
							QStringLiteral("意外的 ']'，没有匹配的 '['"),
							t.line, t.column, 1, JsonLangDiagnosticData::UnexpectedToken));
					}
				}
			}
			for (const Open& o : stack) {
				const QString want = o.type == JsonTokenType::LBrace ? QStringLiteral("'}'") : QStringLiteral("']'");
				const QString openCh = o.type == JsonTokenType::LBrace ? QStringLiteral("'{'") : QStringLiteral("'['");
				diagnostics.append(JsonLangDiagnosticData(
					QStringLiteral("未闭合的括号 %1，缺少对应的 %2").arg(openCh, want),
					o.tok->line, o.tok->column, 1, JsonLangDiagnosticData::UnclosedBracket,
					QStringLiteral("请在适当位置补上 %1").arg(want)));
			}
		}

		void parseJsonTokens(const QList<JsonToken>& tokens, QList<JsonLangDiagnosticData>& diagnostics) {
			if (tokens.size() <= 1) return; // 空文档（仅 EOF）
			JsonParseContext ctx;
			ctx.tokens = &tokens;
			ctx.diagnostics = &diagnostics;
			parseValue(ctx);
			const JsonToken& t = peekToken(ctx);
			if (t.type != JsonTokenType::EndOfFile) {
				diagAt(ctx, JsonLangDiagnosticData::UnexpectedContent,
					QStringLiteral("多余的内容：%1").arg(describeToken(t)), t,
					QStringLiteral("JSON 顶层只能有一个值"));
			}
			checkBracketBalance(tokens, diagnostics);
		}
	}

	// ---------------------------------------------------------------------------
	// JsonLangDocument
	// ---------------------------------------------------------------------------
	class JsonLangDocumentPrivate {
		friend class JsonLangDocument;
	protected:
		JsonLangDocument* q;
		QTimer DebounceTimer;
		QStringList Lines;
		QList<QList<JsonLangDiagnosticData>> DiagnosticsCache;
		bool Analyzed = false;

		void scheduleAnalyze() {
			DebounceTimer.start(0);
		}
	};

	JsonLangDocument::JsonLangDocument(QObject* parent) : QObject(parent) {
		d = new JsonLangDocumentPrivate();
		d->q = this;
		d->DebounceTimer.setSingleShot(true);
		connect(&d->DebounceTimer, &QTimer::timeout, this, &JsonLangDocument::analyze);
	}

	JsonLangDocument::~JsonLangDocument() {
		delete d;
	}

	void JsonLangDocument::onSyntaxHighlighter(const QString& text, qint32 lineIndex) {
		if (lineIndex < 0) return;
		while (d->Lines.size() <= lineIndex) {
			d->Lines.append(QString());
		}
		if (d->Lines[lineIndex] == text && d->Analyzed) {
			return; // 内容未变，无需重新分析
		}
		d->Lines[lineIndex] = text;
		d->scheduleAnalyze();
	}

	void JsonLangDocument::onLinesAdded(qint32 startLine, qint32 count) {
		if (startLine < 0 || count <= 0) return;
		// 补齐起始行之前的缺口（理论上不应出现）
		while (d->Lines.size() < startLine) {
			d->Lines.append(QString());
		}
		for (qint32 i = 0; i < count; ++i) {
			if (startLine >= d->Lines.size()) {
				d->Lines.append(QString());
			}
			else {
				d->Lines.insert(startLine, QString());
			}
		}
		d->Analyzed = false;
		d->scheduleAnalyze();
	}

	void JsonLangDocument::onLinesRemoved(qint32 startLine, qint32 count) {
		if (startLine < 0 || count <= 0) return;
		for (qint32 i = 0; i < count; ++i) {
			if (startLine < d->Lines.size()) {
				d->Lines.removeAt(startLine);
			}
		}
		d->Analyzed = false;
		d->scheduleAnalyze();
	}

	void JsonLangDocument::analyze() {
		QList<JsonLangDiagnosticData> allDiags;
		QList<JsonToken> allTokens;
		const qint32 lineCount = d->Lines.size();
		for (qint32 i = 0; i < lineCount; ++i) {
			allTokens += lexJsonLine(d->Lines.at(i), i, &allDiags);
		}
		// 追加文档结束标记
		JsonToken eof;
		eof.type = JsonTokenType::EndOfFile;
		eof.line = qMax<qint32>(lineCount - 1, 0);
		eof.column = lineCount > 0 ? d->Lines.last().length() : 0;
		eof.length = 0;
		allTokens.append(eof);

		parseJsonTokens(allTokens, allDiags);

		d->DiagnosticsCache.clear();
		for (qint32 i = 0; i < lineCount; ++i) {
			d->DiagnosticsCache.append(QList<JsonLangDiagnosticData>());
		}
		for (const JsonLangDiagnosticData& diag : allDiags) {
			const qint32 l = diag.getLine();
			if (l >= 0 && l < d->DiagnosticsCache.size()) {
				d->DiagnosticsCache[l].append(diag);
			}
		}
		d->Analyzed = true;
		emit contentChanged();
	}

	QList<JsonLangDiagnosticData> JsonLangDocument::getDiagnostics(qint32 lineNumber) const {
		if (lineNumber < 0 || lineNumber >= d->DiagnosticsCache.size()) {
			return QList<JsonLangDiagnosticData>();
		}
		return d->DiagnosticsCache[lineNumber];
	}

	QList<JsonLangDiagnosticData> JsonLangDocument::getAllDiagnostics() const {
		QList<JsonLangDiagnosticData> result;
		for (const QList<JsonLangDiagnosticData>& list : d->DiagnosticsCache) {
			result += list;
		}
		return result;
	}
}
