/*
	Visindigo Project Full AI Generated Declaration

	1. This file was entirely generated by AI. There was almost no human
	   involvement in the design of its API and implementation.
	2. Provided that the usage characteristics of the program corresponding
	   to this code are not substantially changed, anyone is free to make
	   fundamental modifications to this code.
	3. This code does not guarantee implementation consistency across
	   generations; it only guarantees that the corresponding program
	   features remain basically stable.
*/
#include "LangServer/TomlLangServer.h"
#include <Editor/TextEdit.h>
#include <Editor/ColorThemeProvider.h>
#include <Widgets/ThemeManager.h>
#include <Utility/FileUtility.h>
#include <QtCore/qset.h>
#include <QtCore/qlist.h>
#include <QtCore/qregularexpression.h>

namespace YSSFileExt {
	enum class TomlTokenType {
		Comment,   // #
		Header,    // [table] / [[array-table]]
		String,    // "..." / '...' / """...""" / '''...'''
		Number,    // 数字
		Boolean,   // true / false
		Date,      // 日期时间
		Equals,    // =
		Comma,     // ,
		LBracket, RBracket, LBrace, RBrace,
		Plain,     // 其它（裸串等）
	};

	struct TomlToken {
		TomlTokenType type = TomlTokenType::Plain;
		QString text;
		qint32 line = 0;
		qint32 column = 0;
		qint32 length = 0;
	};

	static bool isTomlNumber(const QString& s) {
		if (s == QStringLiteral("inf") || s == QStringLiteral("+inf") || s == QStringLiteral("-inf")
			|| s == QStringLiteral("nan") || s == QStringLiteral("+nan") || s == QStringLiteral("-nan")) {
			return true;
		}
		QString t = s;
		if (t.startsWith(QLatin1Char('+')) || t.startsWith(QLatin1Char('-'))) t = t.mid(1);
		if (t.isEmpty()) return false;
		// 十六进制 / 八进制 / 二进制
		if (t.length() > 2 && (t.startsWith(QStringLiteral("0x")) || t.startsWith(QStringLiteral("0o"))
			|| t.startsWith(QStringLiteral("0b")))) {
			QString digits = t.mid(2);
			if (digits.isEmpty()) return false;
			for (int k = 0; k < digits.length(); ++k) {
				const QChar c = digits.at(k);
				if (c == QLatin1Char('_')) {
					if (k == 0 || k == digits.length() - 1) return false;
					continue;
				}
				if (!c.isDigit() && !(t.startsWith(QStringLiteral("0x"))
					&& ((c >= QLatin1Char('a') && c <= QLatin1Char('f')) || (c >= QLatin1Char('A') && c <= QLatin1Char('F'))))) {
					return false;
				}
			}
			return true;
		}
		// 十进制（整数 / 小数 / 指数），允许下划线分隔
		bool hasDigit = false, hasDot = false, hasExp = false;
		for (int k = 0; k < t.length(); ++k) {
			const QChar c = t.at(k);
			if (c.isDigit()) hasDigit = true;
			else if (c == QLatin1Char('_')) {
				if (k == 0 || k == t.length() - 1) return false;
			}
			else if (c == QLatin1Char('.') && !hasDot && !hasExp) hasDot = true;
			else if ((c == QLatin1Char('e') || c == QLatin1Char('E')) && hasDigit && !hasExp) hasExp = true;
			else if ((c == QLatin1Char('+') || c == QLatin1Char('-')) && hasExp) { /* 指数符号 */ }
			else return false;
		}
		return hasDigit;
	}

	// 匹配 TOML 日期时间（含本地日期 / 本地时间 / 偏移时间）
	static bool isTomlDate(const QString& s) {
		static const QRegularExpression re(
			QStringLiteral("^\\d{4}-\\d{2}-\\d{2}([Tt ]\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?([Zz]|[+-]\\d{2}:\\d{2})?)?$")
			+ QStringLiteral("|^\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?([Zz]|[+-]\\d{2}:\\d{2})?$"));
		return re.match(s).hasMatch();
	}

	// 对一行 TOML 文本进行词法分析（供着色与诊断共用）。
	static QList<TomlToken> lexTomlLine(const QString& line, qint32 baseLine, QList<YSSLangDiagnosticData>* diagnostics) {
		QList<TomlToken> tokens;
		auto addDiag = [&](const QString& msg, qint32 col, qint32 len) {
			if (diagnostics) {
				diagnostics->append(YSSLangDiagnosticData(msg, baseLine, col, len,
					YSSLangDiagnosticData::Severity::Error));
			}
		};
		auto makeTok = [&](TomlTokenType type, qint32 col, qint32 len) {
			TomlToken t;
			t.type = type;
			t.line = baseLine;
			t.column = col;
			t.length = len;
			t.text = line.mid(col, len);
			return t;
		};

		const qint32 n = line.length();
		qint32 i = 0;
		while (i < n && line.at(i).isSpace()) ++i;
		const bool atLineStart = (i == 0 || line.left(i).trimmed().isEmpty());
		if (i >= n) return tokens;

		// 注释行
		if (line.at(i) == QLatin1Char('#')) {
			tokens.append(makeTok(TomlTokenType::Comment, i, n - i));
			return tokens;
		}
		// 表头（仅行首的 '['）
		if (atLineStart && line.at(i) == QLatin1Char('[')) {
			const qint32 start = i;
			bool arr = false;
			if (i + 1 < n && line.at(i + 1) == QLatin1Char('[')) { arr = true; i += 2; }
			else ++i;
			bool closed = false;
			while (i < n) {
				if (line.at(i) == QLatin1Char(']')) {
					++i;
					if (arr) {
						if (i < n && line.at(i) == QLatin1Char(']')) ++i;
						else addDiag(QStringLiteral("数组表头未闭合（缺少 ]]）"), start, i - start);
					}
					closed = true;
					break;
				}
				if (line.at(i) == QLatin1Char('"') || line.at(i) == QLatin1Char('\'')) {
					const QChar q = line.at(i);
					++i;
					while (i < n && line.at(i) != q) ++i;
					if (i < n) ++i;
				}
				else ++i;
			}
			if (!closed) addDiag(QStringLiteral("表头未闭合（缺少 ]）"), start, n - start);
			tokens.append(makeTok(TomlTokenType::Header, start, i - start));
			while (i < n && line.at(i).isSpace()) ++i;
			if (i < n && line.at(i) == QLatin1Char('#')) {
				tokens.append(makeTok(TomlTokenType::Comment, i, n - i));
			}
			return tokens;
		}

		// 普通行：键 = 值 / 数组 / 内联表
		while (i < n) {
			const QChar ch = line.at(i);
			if (ch.isSpace()) { ++i; continue; }
			if (ch == QLatin1Char('#')) { tokens.append(makeTok(TomlTokenType::Comment, i, n - i)); break; }
			if (ch == QLatin1Char('=')) { tokens.append(makeTok(TomlTokenType::Equals, i, 1)); ++i; continue; }
			if (ch == QLatin1Char(',')) { tokens.append(makeTok(TomlTokenType::Comma, i, 1)); ++i; continue; }
			if (ch == QLatin1Char('[')) { tokens.append(makeTok(TomlTokenType::LBracket, i, 1)); ++i; continue; }
			if (ch == QLatin1Char(']')) { tokens.append(makeTok(TomlTokenType::RBracket, i, 1)); ++i; continue; }
			if (ch == QLatin1Char('{')) { tokens.append(makeTok(TomlTokenType::LBrace, i, 1)); ++i; continue; }
			if (ch == QLatin1Char('}')) { tokens.append(makeTok(TomlTokenType::RBrace, i, 1)); ++i; continue; }
			if (ch == QLatin1Char('"') || ch == QLatin1Char('\'')) {
				// 字符串（含多行）
				const qint32 start = i;
				const QChar q = ch;
				const bool multiline = (i + 2 < n && line.at(i + 1) == q && line.at(i + 2) == q);
				if (multiline) i += 3; else ++i;
				bool terminated = false;
				while (i < n) {
					if (q == QLatin1Char('"') && line.at(i) == QLatin1Char('\\')) { i += 2; continue; }
					if (line.at(i) == q) {
						if (multiline) {
							if (i + 2 < n && line.at(i + 1) == q && line.at(i + 2) == q) { i += 3; terminated = true; break; }
						}
						else { ++i; terminated = true; break; }
					}
					++i;
				}
				if (!terminated) addDiag(QStringLiteral("字符串未闭合"), start, i - start);
				tokens.append(makeTok(TomlTokenType::String, start, i - start));
				continue;
			}
			// 标量（数字 / 布尔 / 日期 / 裸串）
			{
				const qint32 start = i;
				while (i < n && !line.at(i).isSpace() && line.at(i) != QLatin1Char('=')
					&& line.at(i) != QLatin1Char(',') && line.at(i) != QLatin1Char('[')
					&& line.at(i) != QLatin1Char(']') && line.at(i) != QLatin1Char('{')
					&& line.at(i) != QLatin1Char('}') && line.at(i) != QLatin1Char('#')) {
					++i;
				}
				const QString s = line.mid(start, i - start);
				TomlTokenType tt = TomlTokenType::Plain;
				if (s == QStringLiteral("true") || s == QStringLiteral("false")) tt = TomlTokenType::Boolean;
				else if (isTomlNumber(s)) tt = TomlTokenType::Number;
				else if (isTomlDate(s)) tt = TomlTokenType::Date;
				tokens.append(makeTok(tt, start, i - start));
			}
		}
		return tokens;
	}

	// 规范化表路径（去除引号与空白，仅用于重复表判定）
	static QString normalizeTomlPath(const QString& path) {
		QString out;
		for (const QChar c : path) {
			if (c == QLatin1Char('"') || c == QLatin1Char('\'')) continue;
			out.append(c);
		}
		return out.trimmed();
	}

	// 查找第一个赋值用的 '='（跳过引号内与比较运算符）
	static int findTomlEquals(const QString& s) {
		bool inStr = false;
		QChar strQ;
		for (int i = 0; i < s.length(); ++i) {
			const QChar c = s.at(i);
			if (inStr) {
				if (c == strQ) inStr = false;
				continue;
			}
			if (c == QLatin1Char('"') || c == QLatin1Char('\'')) { inStr = true; strQ = c; continue; }
			if (c == QLatin1Char('=')) {
				if (i + 1 < s.length() && (s.at(i + 1) == QLatin1Char('=') || s.at(i + 1) == QLatin1Char('>')
					|| s.at(i + 1) == QLatin1Char('<') || s.at(i + 1) == QLatin1Char('!'))) continue;
				if (i > 0 && (s.at(i - 1) == QLatin1Char('!') || s.at(i - 1) == QLatin1Char('>')
					|| s.at(i - 1) == QLatin1Char('<'))) continue;
				return i;
			}
		}
		return -1;
	}

	static QString unquoteTomlKey(const QString& key) {
		QString k = key.trimmed();
		if (k.length() >= 2
			&& ((k.startsWith(QLatin1Char('"')) && k.endsWith(QLatin1Char('"')))
				|| (k.startsWith(QLatin1Char('\'')) && k.endsWith(QLatin1Char('\''))))) {
			return k.mid(1, k.length() - 2);
		}
		return k;
	}

	// ---------------------------------------------------------------------------
	// TOML 全文档分析
	// ---------------------------------------------------------------------------
	static void analyzeTomlLines(const QStringList& lines, QList<YSSLangDiagnosticData>* diags) {
		if (!diags) return;
		QSet<QString> definedTables;
		QSet<QString> definedArrayTables;
		QMap<QString, QSet<QString>> tableKeys;
		QString currentTable;
		auto diag = [&](const QString& msg, qint32 line, qint32 col, qint32 len,
			YSSLangDiagnosticData::Severity sev = YSSLangDiagnosticData::Severity::Error, const QString& code = QStringLiteral("TOML")) {
			diags->append(YSSLangDiagnosticData(msg, line, col, qMax<qint32>(len, 1), sev, code));
		};
		for (qint32 i = 0; i < lines.size(); ++i) {
			const QString& line = lines.at(i);
			// 词法诊断
			lexTomlLine(line, i, diags);
			const QString trimmed = line.trimmed();
			if (trimmed.isEmpty() || trimmed.startsWith(QLatin1Char('#'))) continue;
			const int indentCol = line.indexOf(trimmed.at(0));
			// 数组表头
			if (trimmed.startsWith(QStringLiteral("[["))) {
				const int end = trimmed.indexOf(QStringLiteral("]]"));
				if (end < 0) {
					diag(QStringLiteral("数组表头未闭合（缺少 ]]）"), i, indentCol, 2);
					continue;
				}
				const QString path = trimmed.mid(2, end - 2).trimmed();
				const QString pathKey = normalizeTomlPath(path);
				if (pathKey.isEmpty()) {
					diag(QStringLiteral("表名不能为空"), i, indentCol, 2);
					continue;
				}
				if (definedTables.contains(pathKey)) {
					diag(QStringLiteral("表 %1 已定义为普通表，不能再用 [[...]] 定义为数组表").arg(path),
						i, indentCol, 2, YSSLangDiagnosticData::Severity::Error);
				}
				definedArrayTables.insert(pathKey);
				currentTable = pathKey;
				tableKeys[currentTable].clear(); // 新数组元素，重置键集
				continue;
			}
			// 普通表头
			if (trimmed.startsWith(QLatin1Char('['))) {
				const int end = trimmed.indexOf(QLatin1Char(']'));
				if (end < 0) {
					diag(QStringLiteral("表头未闭合（缺少 ]）"), i, indentCol, 1);
					continue;
				}
				const QString path = trimmed.mid(1, end - 1).trimmed();
				const QString pathKey = normalizeTomlPath(path);
				if (pathKey.isEmpty()) {
					diag(QStringLiteral("表名不能为空"), i, indentCol, 1);
					continue;
				}
				if (definedArrayTables.contains(pathKey)) {
					diag(QStringLiteral("表 %1 已定义为数组表，不能再用 [...] 定义").arg(path),
						i, indentCol, 1, YSSLangDiagnosticData::Severity::Error);
				}
				if (definedTables.contains(pathKey)) {
					diag(QStringLiteral("表 %1 重复定义").arg(path), i, indentCol, 1,
						YSSLangDiagnosticData::Severity::Warning);
				}
				definedTables.insert(pathKey);
				currentTable = pathKey;
				continue;
			}
			// 键 = 值
			const int eq = findTomlEquals(trimmed);
			if (eq < 0) {
				diag(QStringLiteral("无效的 TOML 语句（应为「键 = 值」或表头）"), i, indentCol,
					trimmed.length(), YSSLangDiagnosticData::Severity::Error);
				continue;
			}
			const QString key = unquoteTomlKey(trimmed.left(eq));
			if (key.isEmpty()) {
				diag(QStringLiteral("键名不能为空"), i, indentCol, eq);
				continue;
			}
			QString value = trimmed.mid(eq + 1).trimmed();
			if (value.isEmpty() || value.startsWith(QLatin1Char('#'))) {
				diag(QStringLiteral("键 \"%1\" 缺少值").arg(key), i, indentCol + eq, 1,
					YSSLangDiagnosticData::Severity::Error);
				continue;
			}
			if (tableKeys[currentTable].contains(key)) {
				diag(QStringLiteral("表 %1 中键 \"%2\" 重复").arg(
					currentTable.isEmpty() ? QStringLiteral("顶层") : currentTable, key),
					i, indentCol, key.length(), YSSLangDiagnosticData::Severity::Warning);
			}
			else {
				tableKeys[currentTable].insert(key);
			}
		}
	}

	// ---------------------------------------------------------------------------
	// TomlLangHighlighter
	// ---------------------------------------------------------------------------
	TomlLangHighlighter::TomlLangHighlighter(YSSCore::Editor::TextEdit* parent) :
		YSSLangHighlighter(parent, &analyzeTomlLines) {}

	void TomlLangHighlighter::colorLine(const QString& text) {
		if (text.isEmpty()) return;
		setFormatWithColorKey(0, text.length(), "PlainText");
		const QList<TomlToken> tokens = lexTomlLine(text, 0, nullptr);
		for (qint32 i = 0; i < tokens.size(); ++i) {
			const TomlToken& t = tokens.at(i);
			switch (t.type) {
			case TomlTokenType::Comment:
				setFormatWithColorKey(t.column, t.length, "Comment");
				break;
			case TomlTokenType::Header:
				setFormatWithColorKey(t.column, t.length, "Header");
				break;
			case TomlTokenType::String: {
				const bool isKey = (i + 1 < tokens.size() && tokens.at(i + 1).type == TomlTokenType::Equals);
				setFormatWithColorKey(t.column, t.length, isKey ? "Key" : "String");
				break;
			}
			case TomlTokenType::Number:
			case TomlTokenType::Date:
				setFormatWithColorKey(t.column, t.length, "Number");
				break;
			case TomlTokenType::Boolean:
				setFormatWithColorKey(t.column, t.length, "Boolean");
				break;
			case TomlTokenType::Plain: {
				const bool isKey = (i + 1 < tokens.size() && tokens.at(i + 1).type == TomlTokenType::Equals);
				if (isKey) {
					setFormatWithColorKey(t.column, t.length, "Key");
				}
				break;
			}
			default:
				break; // 结构符号保持 PlainText
			}
		}
	}

	// ---------------------------------------------------------------------------
	// TomlLangServer
	// ---------------------------------------------------------------------------
	TomlLangServer::TomlLangServer(YSSCore::Editor::EditorPlugin* plugin) :
		YSSCore::Editor::LangServer("YSS File Extension TOML Language Server",
			"YSSFileExt_Toml", plugin, "Toml", { "toml" }) {
		connect(VISTM, &Visindigo::Widgets::ThemeManager::programThemeChanged, this, [this]() {
			if (VISTM->getCurrentColorTheme() == "Dark") {
				if (getColorThemeProvider()->getCurrentTheme() == "Visindigo Light 2024") {
					getColorThemeProvider()->setCurrentTheme("Visindigo Dark 2024");
				}
			}
			else if (VISTM->getCurrentColorTheme() == "Light") {
				if (getColorThemeProvider()->getCurrentTheme() == "Visindigo Dark 2024") {
					getColorThemeProvider()->setCurrentTheme("Visindigo Light 2024");
				}
			}
			});
		getColorThemeProvider()->parseStaticThemeFrom(
			Visindigo::Utility::FileUtility::readAll(
				":/resource/cn.yxgeneral.weavestudio.yssfileext/syntaxColorTheme/toml_dark_2024.json"));
		getColorThemeProvider()->parseStaticThemeFrom(
			Visindigo::Utility::FileUtility::readAll(
				":/resource/cn.yxgeneral.weavestudio.yssfileext/syntaxColorTheme/toml_light_2024.json"));
		// 样式样本：用于颜色主题设置页的预览编辑器展示全部着色元素
		getColorThemeProvider()->setTemplateTextPath(
			":/resource/cn.yxgeneral.weavestudio.yssfileext/syntaxColorTheme/templateToml.toml");
		if (getPlugin()->getPluginConfig()->getString("_yss_auto_.LangServer." + getModuleID() + ".CurrentTheme").isEmpty()) {
			getPlugin()->getPluginConfig()->setString("_yss_auto_.LangServer." + getModuleID() + ".CurrentTheme",
				VISTM->getCurrentColorTheme() == "Light" ? "Visindigo Light 2024" : "Visindigo Dark 2024");
			getPlugin()->savePluginConfig();
		}
	}

	YSSCore::Editor::SyntaxHighlighter* TomlLangServer::createHighlighter(YSSCore::Editor::TextEdit* doc) {
		return new TomlLangHighlighter(doc);
	}
}
