/*
	Visindigo Project Full AI Generated Declaration

	1. This file was entirely generated by AI. There was almost no human
	   involvement in the design of its API and implementation.
	2. Provided that the usage characteristics of the program corresponding
	   to this code are not substantially changed, anyone is free to make
	   fundamental modifications to this code.
	3. This code does not guarantee implementation consistency across
	   generations; it only guarantees that the corresponding program
	   features remain basically stable.
*/
#include "LangServer/XmlLangServer.h"
#include <Editor/TextEdit.h>
#include <Editor/ColorThemeProvider.h>
#include <Widgets/ThemeManager.h>
#include <Utility/FileUtility.h>
#include <QtCore/qset.h>
#include <QtCore/qlist.h>

namespace YSSFileExt {
	// 颜色块状态（用于跨行着色：注释 / CDATA / 标签可跨多行）
	enum class XmlColorState {
		Normal = 0,
		InComment,
		InCDATA,
		InProlog,
		InDoctype,
		InTag,          // 标签内（尚未读到标签名）
		InTagAfterName, // 标签内（已读到标签名，后续名字为属性名）
		InAttrString,   // 属性值字符串未闭合（"）——跨行延续
		InAttrStringSingle, // 属性值字符串未闭合（'）——跨行延续
	};

	// ---------------------------------------------------------------------------
	// XML 全文档分析
	// ---------------------------------------------------------------------------
	static void analyzeXmlLines(const QStringList& lines, QList<YSSLangDiagnosticData>* diags) {
		if (!diags) return;
		enum class S { Normal, Comment, CDATA, Tag, Prolog, Doctype };
		S state = S::Normal;
		bool inClosingTag = false;
		bool tagIsSelfClosing = false;
		bool inAttrString = false;
		QChar attrStringQuote;
		QSet<QString> currentAttrs;
		QString currentTagName;
		qint32 tagStartLine = -1, tagStartCol = -1;
		qint32 blockStartLine = -1, blockStartCol = -1; // 注释 / CDATA / 声明起始

		struct OpenTag { QString name; qint32 line; qint32 col; };
		QList<OpenTag> openTags;

		auto diag = [&](const QString& msg, qint32 line, qint32 col, qint32 len,
			YSSLangDiagnosticData::Severity sev = YSSLangDiagnosticData::Severity::Error, const QString& code = QStringLiteral("XML")) {
			diags->append(YSSLangDiagnosticData(msg, line, col, qMax<qint32>(len, 1), sev, code));
		};

		for (qint32 li = 0; li < lines.size(); ++li) {
			const QString& line = lines.at(li);
			const qint32 n = line.length();
			qint32 i = 0;
			while (i < n) {
				const QChar ch = line.at(i);
				switch (state) {
				case S::Normal: {
					if (ch == QLatin1Char('<')) {
						if (i + 1 >= n) {
							diag(QStringLiteral("'<' 后缺少标签名"), li, i, 1);
							++i;
							break;
						}
						const QChar nxt = line.at(i + 1);
						if (nxt == QLatin1Char('!')) {
							if (line.mid(i, 4) == QStringLiteral("<!--")) {
								state = S::Comment; blockStartLine = li; blockStartCol = i;
								i += 4;
							}
							else if (line.mid(i, 9) == QStringLiteral("<![CDATA[")) {
								state = S::CDATA; blockStartLine = li; blockStartCol = i;
								i += 9;
							}
							else if (line.mid(i, 2) == QStringLiteral("<!")) {
								state = S::Doctype; blockStartLine = li; blockStartCol = i;
								i += 2;
							}
							else {
								diag(QStringLiteral("无法识别的声明 '<!'"), li, i, 2);
								++i;
							}
						}
						else if (nxt == QLatin1Char('?')) {
							state = S::Prolog; blockStartLine = li; blockStartCol = i;
							i += 2;
						}
						else if (nxt == QLatin1Char('/')) {
							inClosingTag = true;
							tagIsSelfClosing = false;
							currentTagName.clear();
							currentAttrs.clear();
							tagStartLine = li; tagStartCol = i;
							state = S::Tag;
							i += 2;
						}
						else {
							inClosingTag = false;
							tagIsSelfClosing = false;
							currentTagName.clear();
							currentAttrs.clear();
							tagStartLine = li; tagStartCol = i;
							state = S::Tag;
							++i;
						}
					}
					else if (ch == QLatin1Char('&')) {
						// 实体引用检查
						const int semi = line.indexOf(QLatin1Char(';'), i);
						bool validEntity = false;
						if (semi > i && semi - i <= 9) {
							const QString ename = line.mid(i + 1, semi - i - 1);
							if (ename == QStringLiteral("amp") || ename == QStringLiteral("lt")
								|| ename == QStringLiteral("gt") || ename == QStringLiteral("quot")
								|| ename == QStringLiteral("apos")) {
								validEntity = true;
							}
							else if (ename.startsWith(QLatin1Char('#')) && ename.length() > 1) {
								validEntity = true;
								for (int k = 1; k < ename.length(); ++k) {
									const QChar cc = ename.at(k);
									if (k == 1 && (cc == QLatin1Char('x') || cc == QLatin1Char('X'))) continue;
									if (!cc.isDigit() && !(cc >= QLatin1Char('a') && cc <= QLatin1Char('f'))
										&& !(cc >= QLatin1Char('A') && cc <= QLatin1Char('F'))) {
										validEntity = false;
										break;
									}
								}
							}
						}
						if (!validEntity) {
							diag(QStringLiteral("文本中的 '&' 应转义为 &amp;"), li, i, 1,
								YSSLangDiagnosticData::Severity::Warning);
						}
						++i;
					}
					else {
						++i;
					}
					break;
				}
				case S::Comment: {
					const int end = line.indexOf(QStringLiteral("-->"), i);
					if (end >= 0) { state = S::Normal; i = end + 3; }
					else i = n;
					break;
				}
				case S::CDATA: {
					const int end = line.indexOf(QStringLiteral("]]>"), i);
					if (end >= 0) { state = S::Normal; i = end + 3; }
					else i = n;
					break;
				}
				case S::Prolog: {
					const int end = line.indexOf(QStringLiteral("?>"), i);
					if (end >= 0) { state = S::Normal; i = end + 2; }
					else i = n;
					break;
				}
				case S::Doctype: {
					const int end = line.indexOf(QLatin1Char('>'), i);
					if (end >= 0) { state = S::Normal; i = end + 1; }
					else i = n;
					break;
				}
				case S::Tag: {
					if (inAttrString) {
						if (ch == attrStringQuote) { inAttrString = false; ++i; }
						else ++i;
						break;
					}
					if (ch == QLatin1Char('"') || ch == QLatin1Char('\'')) {
						inAttrString = true;
						attrStringQuote = ch;
						++i;
						break;
					}
					if (ch == QLatin1Char('>')) {
						if (!currentTagName.isEmpty()) {
							if (inClosingTag) {
								if (openTags.isEmpty()) {
									diag(QStringLiteral("意外的结束标签 </%1>，没有匹配的开始标签").arg(currentTagName),
										tagStartLine, tagStartCol, currentTagName.length() + 3);
								}
								else if (openTags.last().name == currentTagName) {
									openTags.removeLast();
								}
								else {
									diag(QStringLiteral("结束标签 </%1> 与开始标签 <%2> 不匹配").arg(currentTagName, openTags.last().name),
										tagStartLine, tagStartCol, currentTagName.length() + 3);
									openTags.removeLast();
								}
							}
							else if (!tagIsSelfClosing) {
								OpenTag ot;
								ot.name = currentTagName;
								ot.line = tagStartLine;
								ot.col = tagStartCol;
								openTags.append(ot);
							}
						}
						state = S::Normal;
						inClosingTag = false;
						tagIsSelfClosing = false;
						currentTagName.clear();
						++i;
						break;
					}
					if (ch == QLatin1Char('/')) {
						// 自闭合标签：'/' 后紧跟 '>' 则标记为自闭合，不再压入标签栈
						if (i + 1 < n && line.at(i + 1) == QLatin1Char('>')) {
							tagIsSelfClosing = true;
							++i;
							break;
						}
						++i;
						break;
					}
					if (ch.isLetter() || ch == QLatin1Char('_') || ch == QLatin1Char(':') || ch == QLatin1Char('-')) {
						const int start = i;
						while (i < n && (line.at(i).isLetterOrNumber() || line.at(i) == QLatin1Char('_')
							|| line.at(i) == QLatin1Char(':') || line.at(i) == QLatin1Char('-')
							|| line.at(i) == QLatin1Char('.'))) {
							++i;
						}
						const QString name = line.mid(start, i - start);
						if (inClosingTag) {
							currentTagName = name;
						}
						else if (currentTagName.isEmpty()) {
							currentTagName = name;
						}
						else {
							if (currentAttrs.contains(name)) {
								diag(QStringLiteral("标签 <%1> 中属性 \"%2\" 重复").arg(currentTagName, name),
									li, start, name.length(), YSSLangDiagnosticData::Severity::Warning);
							}
							currentAttrs.insert(name);
						}
						break;
					}
					++i;
					break;
				}
				}
			}
		}

		// 文档结束检查
		if (state == S::Comment) {
			diag(QStringLiteral("注释未闭合（缺少 -->）"), blockStartLine, blockStartCol, 1);
		}
		else if (state == S::CDATA) {
			diag(QStringLiteral("CDATA 段未闭合（缺少 ]]>）"), blockStartLine, blockStartCol, 1);
		}
		else if (state == S::Prolog) {
			diag(QStringLiteral("XML 声明未闭合（缺少 ?>）"), blockStartLine, blockStartCol, 1);
		}
		else if (state == S::Doctype) {
			diag(QStringLiteral("DOCTYPE 声明未闭合（缺少 >）"), blockStartLine, blockStartCol, 1);
		}
		else if (state == S::Tag) {
			diag(QStringLiteral("标签未闭合（缺少 >）"), tagStartLine, tagStartCol, 1);
		}
		for (const OpenTag& ot : openTags) {
			diag(QStringLiteral("标签 <%1> 未闭合").arg(ot.name), ot.line, ot.col, ot.name.length() + 2);
		}
	}

	// ---------------------------------------------------------------------------
	// XmlLangHighlighter
	// ---------------------------------------------------------------------------
	XmlLangHighlighter::XmlLangHighlighter(YSSCore::Editor::TextEdit* parent) :
		YSSLangHighlighter(parent, &analyzeXmlLines) {}

	void XmlLangHighlighter::colorLine(const QString& text) {
		if (text.isEmpty()) {
			setCurrentBlockState(previousBlockState() < 0 ? (int)XmlColorState::Normal : previousBlockState());
			return;
		}
		setFormatWithColorKey(0, text.length(), "PlainText");
		int state = previousBlockState();
		if (state < 0) state = (int)XmlColorState::Normal;

		auto apply = [&](qint32 start, qint32 len, const QString& key) {
			if (len > 0) setFormatWithColorKey(start, len, key);
		};

		const qint32 n = text.length();
		qint32 i = 0;
		while (i < n) {
			switch ((XmlColorState)state) {
			case XmlColorState::Normal: {
				qint32 next = i;
				while (next < n && text.at(next) != QLatin1Char('<') && text.at(next) != QLatin1Char('&')) ++next;
				if (next >= n) { i = n; break; }
				if (text.at(next) == QLatin1Char('&')) {
					const int semi = text.indexOf(QLatin1Char(';'), next);
					if (semi >= 0 && semi - next <= 9) {
						apply(next, semi - next + 1, "Entity");
						i = semi + 1;
					}
					else { ++i; }
					break;
				}
				if (text.mid(next, 4) == QStringLiteral("<!--")) {
					apply(next, 4, "Comment"); i = next + 4; state = (int)XmlColorState::InComment;
				}
				else if (text.mid(next, 9) == QStringLiteral("<![CDATA[")) {
					apply(next, 9, "CData"); i = next + 9; state = (int)XmlColorState::InCDATA;
				}
				else if (text.mid(next, 2) == QStringLiteral("<?")) {
					apply(next, 2, "Keyword"); i = next + 2; state = (int)XmlColorState::InProlog;
				}
				else if (text.mid(next, 2) == QStringLiteral("<!")) {
					apply(next, 2, "Keyword"); i = next + 2; state = (int)XmlColorState::InDoctype;
				}
				else if (text.mid(next, 2) == QStringLiteral("</")) {
					apply(next, 2, "XmlTag"); i = next + 2; state = (int)XmlColorState::InTag;
				}
				else {
					// 普通 '<'：跳到 '<' 之后。必须用 next+1，而不是 ++i——
					// 当 '<' 不在行首（i<next）时 ++i 会回退，把 '<' 前的文本误着色为标签名。
					apply(next, 1, "XmlTag"); i = next + 1; state = (int)XmlColorState::InTag;
				}
				break;
			}
			case XmlColorState::InComment: {
				const int end = text.indexOf(QStringLiteral("-->"), i);
				if (end >= 0) { apply(i, end - i + 3, "Comment"); i = end + 3; state = (int)XmlColorState::Normal; }
				else { apply(i, n - i, "Comment"); i = n; }
				break;
			}
			case XmlColorState::InCDATA: {
				const int end = text.indexOf(QStringLiteral("]]>"), i);
				if (end >= 0) { apply(i, end - i + 3, "CData"); i = end + 3; state = (int)XmlColorState::Normal; }
				else { apply(i, n - i, "CData"); i = n; }
				break;
			}
			case XmlColorState::InProlog: {
				const int end = text.indexOf(QStringLiteral("?>"), i);
				if (end >= 0) { apply(i, end - i + 2, "Keyword"); i = end + 2; state = (int)XmlColorState::Normal; }
				else { apply(i, n - i, "Keyword"); i = n; }
				break;
			}
			case XmlColorState::InDoctype: {
				const int end = text.indexOf(QLatin1Char('>'), i);
				if (end >= 0) { apply(i, end - i + 1, "Keyword"); i = end + 1; state = (int)XmlColorState::Normal; }
				else { apply(i, n - i, "Keyword"); i = n; }
				break;
			}
			case XmlColorState::InTag:
			case XmlColorState::InTagAfterName: {
				while (i < n && text.at(i).isSpace()) ++i;
				if (i >= n) { i = n; break; }
				const QChar ch = text.at(i);
				if (ch == QLatin1Char('>')) {
					apply(i, 1, "XmlTag"); ++i; state = (int)XmlColorState::Normal; break;
				}
				if (ch == QLatin1Char('/')) {
					if (i + 1 < n && text.at(i + 1) == QLatin1Char('>')) {
						apply(i, 2, "XmlTag"); i += 2; state = (int)XmlColorState::Normal; break;
					}
					++i; break;
				}
				if (ch == QLatin1Char('=')) { ++i; break; }
				if (ch == QLatin1Char('"') || ch == QLatin1Char('\'')) {
					const QChar quote = ch;
					const qint32 start = i;
					++i;
					while (i < n && text.at(i) != quote) ++i;
					if (i < n) {
						++i; // 本行内闭合
						state = (int)XmlColorState::InTagAfterName;
					}
					else {
						// 属性值跨行：进入 InAttrString 状态延续到下一行
						state = (quote == QLatin1Char('"'))
							? (int)XmlColorState::InAttrString
							: (int)XmlColorState::InAttrStringSingle;
					}
					apply(start, i - start, "String");
					break;
				}
				if (ch.isLetter() || ch == QLatin1Char('_') || ch == QLatin1Char(':') || ch == QLatin1Char('-')) {
					const qint32 start = i;
					while (i < n && (text.at(i).isLetterOrNumber() || text.at(i) == QLatin1Char('_')
						|| text.at(i) == QLatin1Char(':') || text.at(i) == QLatin1Char('-')
						|| text.at(i) == QLatin1Char('.'))) {
						++i;
					}
					if (state == (int)XmlColorState::InTag) {
						apply(start, i - start, "XmlTag");
						state = (int)XmlColorState::InTagAfterName;
					}
					else {
						apply(start, i - start, "Attribute");
					}
					break;
				}
				++i;
				break;
			}
			case XmlColorState::InAttrString:
			case XmlColorState::InAttrStringSingle: {
				// 属性值字符串跨行延续：整行（到闭合引号为止）视为字符串
				const QChar quote = (state == (int)XmlColorState::InAttrString)
					? QLatin1Char('"') : QLatin1Char('\'');
				qint32 p = 0;
				while (p < n && text.at(p) != quote) ++p;
				if (p < n) {
					++p; // 本行闭合
					state = (int)XmlColorState::InTagAfterName;
				}
				apply(0, p, "String");
				i = p;
				break;
			}
			}
		}
		setCurrentBlockState(state);
	}

	// ---------------------------------------------------------------------------
	// XmlLangServer
	// ---------------------------------------------------------------------------
	XmlLangServer::XmlLangServer(YSSCore::Editor::EditorPlugin* plugin) :
		YSSCore::Editor::LangServer("YSS File Extension XML Language Server",
			"YSSFileExt_Xml", plugin, "Xml", { "xml" }) {
		connect(VISTM, &Visindigo::Widgets::ThemeManager::programThemeChanged, this, [this]() {
			if (VISTM->getCurrentColorTheme() == "Dark") {
				if (getColorThemeProvider()->getCurrentTheme() == "Visindigo Light 2024") {
					getColorThemeProvider()->setCurrentTheme("Visindigo Dark 2024");
				}
			}
			else if (VISTM->getCurrentColorTheme() == "Light") {
				if (getColorThemeProvider()->getCurrentTheme() == "Visindigo Dark 2024") {
					getColorThemeProvider()->setCurrentTheme("Visindigo Light 2024");
				}
			}
			});
		getColorThemeProvider()->parseStaticThemeFrom(
			Visindigo::Utility::FileUtility::readAll(
				":/resource/cn.yxgeneral.weavestudio.yssfileext/syntaxColorTheme/xml_dark_2024.json"));
		getColorThemeProvider()->parseStaticThemeFrom(
			Visindigo::Utility::FileUtility::readAll(
				":/resource/cn.yxgeneral.weavestudio.yssfileext/syntaxColorTheme/xml_light_2024.json"));
		// 样式样本：用于颜色主题设置页的预览编辑器展示全部着色元素
		getColorThemeProvider()->setTemplateTextPath(
			":/resource/cn.yxgeneral.weavestudio.yssfileext/syntaxColorTheme/templateXml.xml");
		if (getPlugin()->getPluginConfig()->getString("_yss_auto_.LangServer." + getModuleID() + ".CurrentTheme").isEmpty()) {
			getPlugin()->getPluginConfig()->setString("_yss_auto_.LangServer." + getModuleID() + ".CurrentTheme",
				VISTM->getCurrentColorTheme() == "Light" ? "Visindigo Light 2024" : "Visindigo Dark 2024");
			getPlugin()->savePluginConfig();
		}
	}

	YSSCore::Editor::SyntaxHighlighter* XmlLangServer::createHighlighter(YSSCore::Editor::TextEdit* doc) {
		return new XmlLangHighlighter(doc);
	}
}
