/*
	Visindigo Project Full AI Generated Declaration

	1. This file was entirely generated by AI. There was almost no human
	   involvement in the design of its API and implementation.
	2. Provided that the usage characteristics of the program corresponding
	   to this code are not substantially changed, anyone is free to make
	   fundamental modifications to this code.
	3. This code does not guarantee implementation consistency across
	   generations; it only guarantees that the corresponding program
	   features remain basically stable.
*/
#include "LangServer/YamlLangServer.h"
#include <Editor/TextEdit.h>
#include <Editor/ColorThemeProvider.h>
#include <Widgets/ThemeManager.h>
#include <Utility/FileUtility.h>
#include <QtCore/qset.h>
#include <QtCore/qlist.h>

namespace YSSFileExt {
	// ---------------------------------------------------------------------------
	// YAML 词法分析
	// ---------------------------------------------------------------------------
	enum class YamlTokenType {
		Comment,       // # 注释
		Key,           // 映射键（由 colorLine 依据其后 ':' 判定）
		String,        // "..." / '...' 引号字符串
		Number,        // 数字标量
		Boolean,       // true/false/yes/no/on/off
		Null,          // null / ~
		Anchor,        // &锚点 / *别名
		Tag,           // !!tag / !tag
		DocumentStart, // ---
		DocumentEnd,   // ...
		BlockScalar,   // | / >
		Colon,         // :
		Comma,         // ,
		Hyphen,        // -（列表项）
		LBracket, RBracket, LBrace, RBrace,
		Plain,         // 其它普通标量
	};

	struct YamlToken {
		YamlTokenType type = YamlTokenType::Plain;
		QString text;
		qint32 line = 0;    // 0-based
		qint32 column = 0;  // 0-based，行内列号
		qint32 length = 0;
	};

	// 对一行 YAML 文本进行词法分析（供着色与诊断共用）。
	static QList<YamlToken> lexYamlLine(const QString& line, qint32 baseLine, QList<YSSLangDiagnosticData>* diagnostics) {
		QList<YamlToken> tokens;
		auto addDiag = [&](const QString& msg, qint32 col, qint32 len, YSSLangDiagnosticData::Severity sev) {
			if (diagnostics) {
				diagnostics->append(YSSLangDiagnosticData(msg, baseLine, col, len, sev));
			}
		};
		auto makeTok = [&](YamlTokenType type, qint32 col, qint32 len) {
			YamlToken t;
			t.type = type;
			t.line = baseLine;
			t.column = col;
			t.length = len;
			t.text = line.mid(col, len);
			return t;
		};

		const qint32 n = line.length();
		qint32 i = 0;
		while (i < n && line.at(i).isSpace()) ++i;

		// 文档开始 / 结束标记（须位于行首且后随空白或行尾）
		if (i + 3 <= n && line.mid(i, 3) == QStringLiteral("---") && (i + 3 == n || line.at(i + 3).isSpace())) {
			tokens.append(makeTok(YamlTokenType::DocumentStart, i, 3));
			i += 3;
		}
		else if (i + 3 <= n && line.mid(i, 3) == QStringLiteral("...") && (i + 3 == n || line.at(i + 3).isSpace())) {
			tokens.append(makeTok(YamlTokenType::DocumentEnd, i, 3));
			i += 3;
		}

		while (i < n) {
			const QChar ch = line.at(i);
			// 跳过空白（空格 / 制表 / 回车等），避免零长度 token 导致死循环
			if (ch.isSpace()) { ++i; continue; }
			// 注释：'#' 位于行首或前有空白
			if (ch == QLatin1Char('#') && (i == 0 || line.at(i - 1).isSpace())) {
				tokens.append(makeTok(YamlTokenType::Comment, i, n - i));
				i = n;
				break;
			}
			// 锚点 / 别名
			if (ch == QLatin1Char('&') || ch == QLatin1Char('*')) {
				const qint32 start = i;
				++i;
				const qint32 nameStart = i;
				while (i < n && !line.at(i).isSpace() && line.at(i) != QLatin1Char(',')
					&& line.at(i) != QLatin1Char('[') && line.at(i) != QLatin1Char(']')
					&& line.at(i) != QLatin1Char('{') && line.at(i) != QLatin1Char('}')
					&& line.at(i) != QLatin1Char('#')) {
					++i;
				}
				if (i == nameStart) {
					addDiag(ch == QLatin1Char('&') ? QStringLiteral("锚点名称不能为空") : QStringLiteral("别名名称不能为空"),
						start, 1, YSSLangDiagnosticData::Severity::Error);
				}
				tokens.append(makeTok(YamlTokenType::Anchor, start, i - start));
				continue;
			}
			// 标签
			if (ch == QLatin1Char('!')) {
				const qint32 start = i;
				++i;
				if (i < n && line.at(i) == QLatin1Char('!')) ++i;
				while (i < n && !line.at(i).isSpace() && line.at(i) != QLatin1Char(',')
					&& line.at(i) != QLatin1Char('[') && line.at(i) != QLatin1Char(']')
					&& line.at(i) != QLatin1Char('{') && line.at(i) != QLatin1Char('}')) {
					++i;
				}
				if (i == start + 1) {
					addDiag(QStringLiteral("无效的标签 '!'"), start, 1, YSSLangDiagnosticData::Severity::Error);
				}
				tokens.append(makeTok(YamlTokenType::Tag, start, i - start));
				continue;
			}
			// 引号字符串
			if (ch == QLatin1Char('"') || ch == QLatin1Char('\'')) {
				const qint32 start = i;
				const QChar quote = ch;
				++i;
				bool terminated = false;
				while (i < n) {
					const QChar c = line.at(i);
					if (quote == QLatin1Char('"') && c == QLatin1Char('\\')) {
						i += 2; // 转义序列（可能越过行尾）
						continue;
					}
					if (c == quote) {
						if (quote == QLatin1Char('\'') && i + 1 < n && line.at(i + 1) == QLatin1Char('\'')) {
							i += 2; // 单引号字符串内的 '' 表示字面单引号
							continue;
						}
						terminated = true;
						++i;
						break;
					}
					++i;
				}
				if (!terminated) {
					addDiag(QStringLiteral("字符串未闭合（缺少结尾引号）"),
						start, i - start, YSSLangDiagnosticData::Severity::Error);
				}
				tokens.append(makeTok(YamlTokenType::String, start, i - start));
				continue;
			}
			// 块标量指示符
			if (ch == QLatin1Char('|') || ch == QLatin1Char('>')) {
				const qint32 start = i;
				++i;
				if (i < n && (line.at(i) == QLatin1Char('+') || line.at(i) == QLatin1Char('-'))) ++i;
				tokens.append(makeTok(YamlTokenType::BlockScalar, start, i - start));
				continue;
			}
			// 标点
			if (ch == QLatin1Char(':')) { tokens.append(makeTok(YamlTokenType::Colon, i, 1)); ++i; continue; }
			if (ch == QLatin1Char(',')) { tokens.append(makeTok(YamlTokenType::Comma, i, 1)); ++i; continue; }
			if (ch == QLatin1Char('[')) { tokens.append(makeTok(YamlTokenType::LBracket, i, 1)); ++i; continue; }
			if (ch == QLatin1Char(']')) { tokens.append(makeTok(YamlTokenType::RBracket, i, 1)); ++i; continue; }
			if (ch == QLatin1Char('{')) { tokens.append(makeTok(YamlTokenType::LBrace, i, 1)); ++i; continue; }
			if (ch == QLatin1Char('}')) { tokens.append(makeTok(YamlTokenType::RBrace, i, 1)); ++i; continue; }
			if (ch == QLatin1Char('-')) {
				// '-' 后随空白/行尾为列表项标记，否则为普通标量（如负数）
				if (i + 1 >= n || line.at(i + 1).isSpace()) {
					tokens.append(makeTok(YamlTokenType::Hyphen, i, 1));
					++i;
				}
				else {
					const qint32 start = i;
					++i;
					while (i < n && !line.at(i).isSpace() && line.at(i) != QLatin1Char(',')
						&& line.at(i) != QLatin1Char('[') && line.at(i) != QLatin1Char(']')
						&& line.at(i) != QLatin1Char('{') && line.at(i) != QLatin1Char('}')) {
						++i;
					}
					tokens.append(makeTok(YamlTokenType::Number, start, i - start));
				}
				continue;
			}

			// 普通标量
			{
				const qint32 start = i;
				while (i < n && !line.at(i).isSpace()
					&& line.at(i) != QLatin1Char(':') && line.at(i) != QLatin1Char(',')
					&& line.at(i) != QLatin1Char('[') && line.at(i) != QLatin1Char(']')
					&& line.at(i) != QLatin1Char('{') && line.at(i) != QLatin1Char('}')
					&& line.at(i) != QLatin1Char('&') && line.at(i) != QLatin1Char('*')
					&& line.at(i) != QLatin1Char('!')) {
					// '#' 在标量内部视为标量内容（注释需前有空白）
					if (line.at(i) == QLatin1Char('#')) {
						++i;
						continue;
					}
					++i;
				}
				const QString text = line.mid(start, i - start);
				YamlTokenType tt = YamlTokenType::Plain;
				// 数字判断（整数 / 小数 / 指数）
				{
					const QString& s = text;
					QString digits = s;
					if (digits.startsWith(QLatin1Char('-')) || digits.startsWith(QLatin1Char('+'))) {
						digits = digits.mid(1);
					}
					if (!digits.isEmpty()) {
						bool ok = true;
						bool hasDigit = false, hasDot = false, hasExp = false;
						for (int k = 0; k < digits.length(); ++k) {
							const QChar cc = digits.at(k);
							if (cc.isDigit()) hasDigit = true;
							else if (cc == QLatin1Char('.') && !hasDot && !hasExp) hasDot = true;
							else if ((cc == QLatin1Char('e') || cc == QLatin1Char('E')) && hasDigit && !hasExp) hasExp = true;
							else { ok = false; break; }
						}
						if (ok && hasDigit) tt = YamlTokenType::Number;
					}
				}
				if (tt == YamlTokenType::Plain) {
					const QString lower = text.toLower();
					if (lower == QStringLiteral("true") || lower == QStringLiteral("false")
						|| lower == QStringLiteral("yes") || lower == QStringLiteral("no")
						|| lower == QStringLiteral("on") || lower == QStringLiteral("off")) {
						tt = YamlTokenType::Boolean;
					}
					else if (lower == QStringLiteral("null") || text == QStringLiteral("~")) {
						tt = YamlTokenType::Null;
					}
				}
				tokens.append(makeTok(tt, start, i - start));
			}
		}
		return tokens;
	}

	// 判定字符串是否为块标量指示符（| 、> 及带 + / - 修饰符）
	static bool isBlockScalarIndicator(const QString& s) {
		QString t = s.trimmed();
		if (t.isEmpty()) return false;
		if (t.at(0) != QLatin1Char('|') && t.at(0) != QLatin1Char('>')) return false;
		const QString rest = t.mid(1);
		return rest.isEmpty() || rest == QStringLiteral("+") || rest == QStringLiteral("-");
	}

	// 从映射条目文本中提取键名；若该行不是映射键行则返回空串。
	// 仅当冒号后为空白或行尾时视为映射分隔符（避免把 URL 等误判为键）。
	static QString extractYamlKey(const QString& s) {
		const int colon = s.indexOf(QLatin1Char(':'));
		if (colon < 0) return QString();
		if (colon + 1 < s.length() && !s.at(colon + 1).isSpace()) return QString();
		QString key = s.left(colon).trimmed();
		if (key.length() >= 2
			&& ((key.startsWith(QLatin1Char('"')) && key.endsWith(QLatin1Char('"')))
				|| (key.startsWith(QLatin1Char('\'')) && key.endsWith(QLatin1Char('\''))))) {
			key = key.mid(1, key.length() - 2);
		}
		return key;
	}

	// ---------------------------------------------------------------------------
	// YAML 全文档分析
	// ---------------------------------------------------------------------------
	static void analyzeYamlLines(const QStringList& lines, QList<YSSLangDiagnosticData>* diags) {
		if (!diags) return;
		// 词法诊断（未闭合字符串、无效标签/锚点）
		for (qint32 i = 0; i < lines.size(); ++i) {
			lexYamlLine(lines.at(i), i, diags);
		}
		struct Level { int indent; QSet<QString> keys; };
		QList<Level> stack;
		int blockScalarIndent = -1; // 当前块标量内容的缩进；-1 表示不在块标量中
		for (qint32 i = 0; i < lines.size(); ++i) {
			const QString& line = lines.at(i);
			// 计算缩进并检测制表符
			int indent = 0;
			bool tabInIndent = false;
			while (indent < line.length() && (line.at(indent) == QLatin1Char(' ') || line.at(indent) == QLatin1Char('\t'))) {
				if (line.at(indent) == QLatin1Char('\t')) tabInIndent = true;
				++indent;
			}
			if (tabInIndent) {
				diags->append(YSSLangDiagnosticData(
					QStringLiteral("缩进不能使用制表符，请改用空格"), i, 0, 1,
					YSSLangDiagnosticData::Severity::Error, QStringLiteral("YAML-TAB")));
			}
			const QString trimmed = line.mid(indent).trimmed();
			if (trimmed.isEmpty()) continue;                                  // 空行
			if (trimmed.startsWith(QLatin1Char('#'))) continue;               // 注释行
			if (trimmed == QStringLiteral("---") || trimmed == QStringLiteral("...")) continue; // 文档标记
			if (blockScalarIndent >= 0) {
				if (indent > blockScalarIndent) continue; // 块标量内容
				blockScalarIndent = -1;
			}
			// 列表项
			bool isSeqItem = false;
			QString entry;
			int effIndent = indent;
			if (trimmed.startsWith(QLatin1Char('-')) && (trimmed.length() == 1 || trimmed.at(1).isSpace())) {
				isSeqItem = true;
				entry = trimmed.mid(1).trimmed();
				effIndent = indent + 1;
			}
			else {
				entry = trimmed;
			}
			if (entry.isEmpty()) continue;
			// 块标量指示符：进入块标量内容状态
			const QString keyText = extractYamlKey(entry);
			if (!keyText.isEmpty()) {
				// 检查值部分是否为块标量指示符
				const int colon = entry.indexOf(QLatin1Char(':'));
				const QString valuePart = entry.mid(colon + 1).trimmed();
				if (isBlockScalarIndicator(valuePart)) {
					blockScalarIndent = indent;
				}
				// 栈式重复键检测
				if (isSeqItem) {
					while (!stack.isEmpty() && stack.last().indent >= effIndent) stack.removeLast();
				}
				else {
					while (!stack.isEmpty() && stack.last().indent > effIndent) stack.removeLast();
				}
				if (!stack.isEmpty() && stack.last().indent == effIndent) {
					if (stack.last().keys.contains(keyText)) {
						diags->append(YSSLangDiagnosticData(
							QStringLiteral("同一映射中出现重复的键 \"%1\"").arg(keyText), i, indent,
							qMax<qint32>(keyText.length(), 1), YSSLangDiagnosticData::Severity::Warning,
							QStringLiteral("YAML-DUP")));
					}
					else {
						stack.last().keys.insert(keyText);
					}
				}
				else {
					Level lv;
					lv.indent = effIndent;
					lv.keys.insert(keyText);
					stack.append(lv);
				}
			}
		}
	}

	// ---------------------------------------------------------------------------
	// YamlLangHighlighter
	// ---------------------------------------------------------------------------
	YamlLangHighlighter::YamlLangHighlighter(YSSCore::Editor::TextEdit* parent) :
		YSSLangHighlighter(parent, &analyzeYamlLines) {}

	void YamlLangHighlighter::colorLine(const QString& text) {
		if (text.isEmpty()) return;
		setFormatWithColorKey(0, text.length(), "PlainText");
		const QList<YamlToken> tokens = lexYamlLine(text, 0, nullptr);
		for (qint32 i = 0; i < tokens.size(); ++i) {
			const YamlToken& t = tokens.at(i);
			switch (t.type) {
			case YamlTokenType::Comment:
				setFormatWithColorKey(t.column, t.length, "Comment");
				break;
			case YamlTokenType::String:
				setFormatWithColorKey(t.column, t.length, "String");
				break;
			case YamlTokenType::Number:
				setFormatWithColorKey(t.column, t.length, "Number");
				break;
			case YamlTokenType::Boolean:
			case YamlTokenType::Null:
				setFormatWithColorKey(t.column, t.length, "Keyword");
				break;
			case YamlTokenType::Anchor:
				setFormatWithColorKey(t.column, t.length, "Anchor");
				break;
			case YamlTokenType::Tag:
			case YamlTokenType::BlockScalar:
				setFormatWithColorKey(t.column, t.length, "YamlTag");
				break;
			case YamlTokenType::DocumentStart:
			case YamlTokenType::DocumentEnd:
				setFormatWithColorKey(t.column, t.length, "Keyword");
				break;
			case YamlTokenType::Plain: {
				// 映射键：其后（忽略空白）紧跟 ':' 且冒号后为空白/行尾
				bool isKey = false;
				if (i + 1 < tokens.size() && tokens.at(i + 1).type == YamlTokenType::Colon) {
					const int colAfter = tokens.at(i + 1).column + 1;
					isKey = (colAfter >= text.length() || text.at(colAfter).isSpace());
				}
				if (isKey) {
					setFormatWithColorKey(t.column, t.length, "Key");
				}
				break;
			}
			default:
				break; // 结构符号保持 PlainText
			}
		}
	}

	// ---------------------------------------------------------------------------
	// YamlLangServer
	// ---------------------------------------------------------------------------
	YamlLangServer::YamlLangServer(YSSCore::Editor::EditorPlugin* plugin) :
		YSSCore::Editor::LangServer("YSS File Extension YAML Language Server",
			"YSSFileExt_Yaml", plugin, "Yaml", { "yml", "yaml" }) {
		connect(VISTM, &Visindigo::Widgets::ThemeManager::programThemeChanged, this, [this]() {
			if (VISTM->getCurrentColorTheme() == "Dark") {
				if (getColorThemeProvider()->getCurrentTheme() == "Visindigo Light 2024") {
					getColorThemeProvider()->setCurrentTheme("Visindigo Dark 2024");
				}
			}
			else if (VISTM->getCurrentColorTheme() == "Light") {
				if (getColorThemeProvider()->getCurrentTheme() == "Visindigo Dark 2024") {
					getColorThemeProvider()->setCurrentTheme("Visindigo Light 2024");
				}
			}
			});
		getColorThemeProvider()->parseStaticThemeFrom(
			Visindigo::Utility::FileUtility::readAll(
				":/resource/cn.yxgeneral.weavestudio.yssfileext/syntaxColorTheme/yaml_dark_2024.json"));
		getColorThemeProvider()->parseStaticThemeFrom(
			Visindigo::Utility::FileUtility::readAll(
				":/resource/cn.yxgeneral.weavestudio.yssfileext/syntaxColorTheme/yaml_light_2024.json"));
		// 样式样本：用于颜色主题设置页的预览编辑器展示全部着色元素
		getColorThemeProvider()->setTemplateTextPath(
			":/resource/cn.yxgeneral.weavestudio.yssfileext/syntaxColorTheme/templateYaml.yml");
		if (getPlugin()->getPluginConfig()->getString("_yss_auto_.LangServer." + getModuleID() + ".CurrentTheme").isEmpty()) {
			getPlugin()->getPluginConfig()->setString("_yss_auto_.LangServer." + getModuleID() + ".CurrentTheme",
				VISTM->getCurrentColorTheme() == "Light" ? "Visindigo Light 2024" : "Visindigo Dark 2024");
			getPlugin()->savePluginConfig();
		}
	}

	YSSCore::Editor::SyntaxHighlighter* YamlLangServer::createHighlighter(YSSCore::Editor::TextEdit* doc) {
		return new YamlLangHighlighter(doc);
	}
}
