/*
	Visindigo Project Full AI Generated Declaration

	1. This file was entirely generated by AI. There was almost no human
	   involvement in the design of its API and implementation.
	2. Provided that the usage characteristics of the program corresponding
	   to this code are not substantially changed, anyone is free to make
	   fundamental modifications to this code.
	3. This code does not guarantee implementation consistency across
	   generations; it only guarantees that the corresponding program
	   features remain basically stable.
*/
#include "LangServer/YSSConfigLangServer.h"
#include <Editor/ColorThemeProvider.h>
#include <Widgets/ThemeManager.h>
#include <General/Log.h>
#include <Utility/FileOperation.h>

namespace YSSFileExt {
	/*!
		\class YSSFileExt::YSSConfigLangServer
		\brief 通用配置语言服务器：加载 Visindigo 2024（Light/Dark）主题并跟随程序主题切换.

		\since YSS 0.17.0
		\inmodule YSSFileExt

		各语言提供自己的分析函数与着色函数即可，主题加载、跟随程序主题、样式样本与
		“当前主题”的默认值等样板都不必再重复一遍。
	*/
	YSSConfigLangServer::YSSConfigLangServer(YSSCore::Editor::EditorPlugin* plugin, const QString& name, const QString& id,
		const QString& langID, const QStringList& supportedExts,
		const QStringList& syntaxThemeFiles, const QString& templateTextPath,
		YSSConfigAnalyzeFn analyzeFn, YSSConfigColorFn colorFn) :
		YSSCore::Editor::LangServer(name, id, plugin, langID, supportedExts),
		AnalyzeFn(analyzeFn), ColorFn(colorFn) {
		connect(VISTM, &Visindigo::Widgets::ThemeManager::programThemeChanged, this, [this]() {
			if (VISTM->getCurrentColorTheme() == "Dark") {
				if (getColorThemeProvider()->getCurrentTheme() == "Visindigo Light 2024") {
					getColorThemeProvider()->setCurrentTheme("Visindigo Dark 2024");
				}
			}
			else if (VISTM->getCurrentColorTheme() == "Light") {
				if (getColorThemeProvider()->getCurrentTheme() == "Visindigo Dark 2024") {
					getColorThemeProvider()->setCurrentTheme("Visindigo Light 2024");
				}
			}
			});
		for (const QString& themeFile : syntaxThemeFiles) {
			Visindigo::Utility::FileOperation::Errorable<QString> themeResult = Visindigo::Utility::FileOperation::readAll(themeFile);
			if (not themeResult) {
				vgErrorF << "Failed to read syntax color theme: " << themeFile
					<< ", error: " << Visindigo::Utility::FileOperation::errorCodeName(themeResult.error());
				continue;
			}
			getColorThemeProvider()->parseStaticThemeFrom(themeResult.value());
		}
		// 样式样本：用于颜色主题设置页的预览编辑器展示全部着色元素
		getColorThemeProvider()->setTemplateTextPath(templateTextPath);
		if (getPlugin()->getPluginConfig()->getString("_yss_auto_.LangServer." + getModuleID() + ".CurrentTheme").isEmpty()) {
			getPlugin()->getPluginConfig()->setString("_yss_auto_.LangServer." + getModuleID() + ".CurrentTheme",
				VISTM->getCurrentColorTheme() == "Light" ? "Visindigo Light 2024" : "Visindigo Dark 2024");
			getPlugin()->savePluginConfig();
		}
	}

	YSSCore::Editor::SyntaxHighlighter* YSSConfigLangServer::createHighlighter(YSSCore::Editor::TextEdit* doc) {
		return new YSSConfigLangHighlighter(doc, AnalyzeFn, ColorFn);
	}
}
