/*
	Visindigo Project Full AI Generated Declaration

	1. This file was entirely generated by AI. There was almost no human
	   involvement in the design of its API and implementation.
	2. Provided that the usage characteristics of the program corresponding
	   to this code are not substantially changed, anyone is free to make
	   fundamental modifications to this code.
	3. This code does not guarantee implementation consistency across
	   generations; it only guarantees that the corresponding program
	   features remain basically stable.
*/
#include "LangServer/YSSConfigLangHighlighter.h"
#include <Editor/TextEdit.h>
#include <Editor/FileEditWidget.h>
#include <Editor/ColorThemeProvider.h>
#include <QtGui/qtextformat.h>
#include <QtGui/qfont.h>
#include <QtCore/qurl.h>

namespace YSSFileExt {
	class YSSConfigLangHighlighterPrivate {
		friend class YSSConfigLangHighlighter;
	protected:
		YSSConfigLangDocument* Document = nullptr;
		YSSConfigColorFn ColorFn;
		QMap<QString, YSSCore::Editor::StyleData> CurrentTheme;
	};

	/*!
		\class YSSFileExt::YSSConfigLangHighlighter
		\brief 通用配置语言高亮器：缓存主题、按样式键着色、把文档诊断渲染成消息.
		\since YSS 0.17.0
		\inmodule YSSFileExt

		各语言只需提供自己的分析函数与着色函数即可获得完整的“高亮 + 诊断”能力。
	*/
	YSSConfigLangHighlighter::YSSConfigLangHighlighter(YSSCore::Editor::TextEdit* parent,
		YSSConfigAnalyzeFn analyzeFn, YSSConfigColorFn colorFn) : SyntaxHighlighter(parent) {
		d = new YSSConfigLangHighlighterPrivate();
		d->ColorFn = colorFn;
		d->Document = new YSSConfigLangDocument(parent, analyzeFn);
		connect(d->Document, &YSSConfigLangDocument::contentChanged, this, &YSSConfigLangHighlighter::rehighlight_s);
	}

	YSSConfigLangHighlighter::~YSSConfigLangHighlighter() {
		delete d;
	}

	YSSConfigLangDocument* YSSConfigLangHighlighter::getDocument() const {
		return d->Document;
	}

	void YSSConfigLangHighlighter::onThemeChanged(const QMap<QString, YSSCore::Editor::StyleData>& theme) {
		d->CurrentTheme = theme;
	}

	void YSSConfigLangHighlighter::onBlockChanged(const QString& text, int blockNumber) {
		if (d->Document) {
			d->Document->onSyntaxHighlighter(text, blockNumber);
		}
		if (d->ColorFn) {
			d->ColorFn(this, text);
		}
		renderDiagnostics(blockNumber);
	}

	void YSSConfigLangHighlighter::setFormatWithColorKey(int start, int count, const QString& styleKey) {
		YSSCore::Editor::StyleData styleData = d->CurrentTheme.value(styleKey, YSSCore::Editor::StyleData());
		QTextCharFormat format;
		format.setForeground(styleData.getTextColor());
		if (styleData.isBgColorEnabled()) {
			format.setBackground(styleData.getBgColor());
		}
		if (styleData.getUnderlineType() != YSSCore::Editor::StyleData::UnderlineType::NoUnderline) {
			format.setUnderlineColor(styleData.getLineColor());
			format.setUnderlineStyle(QTextCharFormat::UnderlineStyle(styleData.getUnderlineType()));
		}
		format.setFontWeight(styleData.isBold() ? QFont::Bold : QFont::Normal);
		format.setFontItalic(styleData.isItalic());
		setFormat(start, count, format);
	}

	int YSSConfigLangHighlighter::getPreviousBlockState() const {
		return previousBlockState();
	}

	void YSSConfigLangHighlighter::applyBlockState(int state) {
		setCurrentBlockState(state);
	}

	void YSSConfigLangHighlighter::renderDiagnostics(qint32 blockNumber) {
		if (d->Document == nullptr) {
			return;
		}
		const QList<YSSLangDiagnosticData> diagnostics = d->Document->getDiagnostics(blockNumber);
		for (const YSSLangDiagnosticData& diagnostic : diagnostics) {
			renderDiagnostic(diagnostic);
		}
	}

	void YSSConfigLangHighlighter::renderDiagnostic(const YSSLangDiagnosticData& diagnostic) {
		const int column = diagnostic.getColumn();
		const int length = qMax(diagnostic.getLength(), 1);
		if (column < 0) return;
		const QString code = diagnostic.getCode();
		if (diagnostic.getSeverity() == YSSLangDiagnosticData::Severity::Warning) {
			createWarningMessage(diagnostic.getMessage(), column, length, code, QUrl(), diagnostic.getFixAdvice());
		}
		else if (diagnostic.getSeverity() == YSSLangDiagnosticData::Severity::Info) {
			createInfoMessage(diagnostic.getMessage(), column, length, code, QUrl(), diagnostic.getFixAdvice());
		}
		else {
			createErrorMessage(diagnostic.getMessage(), column, length, code, QUrl(), diagnostic.getFixAdvice());
		}
	}
}
