/*
	Visindigo Project Full AI Generated Declaration

	1. This file was entirely generated by AI. There was almost no human
	   involvement in the design of its API and implementation.
	2. Provided that the usage characteristics of the program corresponding
	   to this code are not substantially changed, anyone is free to make
	   fundamental modifications to this code.
	3. This code does not guarantee implementation consistency across
	   generations; it only guarantees that the corresponding program
	   features remain basically stable.
*/
#include "LangServer/YSSConfigLangDocument.h"
#include <QtGui/qtextdocument.h>
#include <QtGui/qtextobject.h>

namespace YSSFileExt {
	/*!
		\class YSSFileExt::YSSLangDiagnosticData
		\brief 一条通用语法诊断信息（行、列、长度、严重级别、代码与修复建议）.
		\since YSS 0.17.0
		\inmodule YSSFileExt

		供 JSON / YAML / XML / TOML / INI 各语言服务器共同使用的简单值类型。
	*/
	YSSLangDiagnosticData::YSSLangDiagnosticData() {}
	YSSLangDiagnosticData::YSSLangDiagnosticData(const QString& message, qint32 line, qint32 column, qint32 length,
		Severity severity, const QString& code, const QString& fixAdvice) :
		message(message), line(line), column(column), length(length), severity(severity), code(code), fixAdvice(fixAdvice) {}
	QString YSSLangDiagnosticData::getMessage() const { return message; }
	qint32 YSSLangDiagnosticData::getLine() const { return line; }
	qint32 YSSLangDiagnosticData::getColumn() const { return column; }
	qint32 YSSLangDiagnosticData::getLength() const { return length; }
	YSSLangDiagnosticData::Severity YSSLangDiagnosticData::getSeverity() const { return severity; }
	QString YSSLangDiagnosticData::getCode() const { return code; }
	QString YSSLangDiagnosticData::getFixAdvice() const { return fixAdvice; }

	/*!
		\class YSSFileExt::YSSConfigLangDocument
		\brief 通用配置语言文档：防抖全文档分析，并把诊断按行挂到宿主编辑器的文本块上.
		\since YSS 0.17.0
		\inmodule YSSFileExt

		各语言通过构造函数传入的 YSSConfigAnalyzeFn 提供自己的分析逻辑。诊断不按行号存数组，
		而是挂在行对应的文本块上，所以行被插入、删除或合并时它们跟着走，不需要任何搬运代码。
	*/
	class YSSConfigLangDocumentPrivate {
		friend class YSSConfigLangDocument;
	protected:
		YSSConfigLangDocument* q = nullptr;
		YSSCore::Editor::TextEdit* HostEdit = nullptr;
		YSSConfigAnalyzeFn AnalyzeFn;
		QTimer DebounceTimer;
		// 正在跑由自己发起的重新着色：这期间的行变化通知不要再触发一轮分析。
		bool Analyzing = false;

		void scheduleAnalyze() {
			DebounceTimer.start(0);
		}
	};

	YSSConfigLangDocument::YSSConfigLangDocument(YSSCore::Editor::TextEdit* hostEdit, YSSConfigAnalyzeFn analyzeFn)
		: QObject(hostEdit) {
		d = new YSSConfigLangDocumentPrivate();
		d->q = this;
		d->HostEdit = hostEdit;
		d->AnalyzeFn = analyzeFn;
		d->DebounceTimer.setSingleShot(true);
		connect(&d->DebounceTimer, &QTimer::timeout, this, &YSSConfigLangDocument::analyze);
	}

	YSSConfigLangDocument::~YSSConfigLangDocument() {
		delete d;
	}

	void YSSConfigLangDocument::onSyntaxHighlighter(const QString& text, qint32 lineIndex) {
		if (d->HostEdit == nullptr || lineIndex < 0) {
			return;
		}
		if (d->Analyzing) {
			return;
		}
		d->scheduleAnalyze();
	}

	void YSSConfigLangDocument::analyze() {
		if (d->HostEdit == nullptr) {
			return;
		}
		QStringList lines;
		QTextDocument* document = d->HostEdit->getDocument();
		for (QTextBlock block = document->begin(); block.isValid(); block = block.next()) {
			lines.append(block.text());
		}
		QList<YSSLangDiagnosticData> allDiags;
		if (d->AnalyzeFn) {
			d->AnalyzeFn(lines, &allDiags);
		}
		// 按行归拢，然后整篇替换一次（旧诊断随块上的数据一起被释放）。
		QMap<qint32, QList<YSSLangDiagnosticData>> byLine;
		for (const YSSLangDiagnosticData& diag : allDiags) {
			const qint32 line = diag.getLine();
			if (line >= 0 && line < lines.size()) {
				byLine[line].append(diag);
			}
		}
		d->HostEdit->removeAllBlockData<YSSConfigLineData>();
		for (auto it = byLine.begin(); it != byLine.end(); ++it) {
			YSSConfigLineData* data = new YSSConfigLineData();
			data->Diagnostics = it.value();
			d->HostEdit->setBlockData<YSSConfigLineData>(it.key(), data);
		}
		d->Analyzing = true;
		emit contentChanged();
		d->Analyzing = false;
	}

	QList<YSSLangDiagnosticData> YSSConfigLangDocument::getDiagnostics(qint32 lineNumber) const {
		if (d->HostEdit == nullptr || lineNumber < 0) {
			return QList<YSSLangDiagnosticData>();
		}
		const YSSConfigLineData* data = d->HostEdit->getBlockData<YSSConfigLineData>(lineNumber);
		if (data == nullptr) {
			return QList<YSSLangDiagnosticData>();
		}
		return data->Diagnostics;
	}

	QList<YSSLangDiagnosticData> YSSConfigLangDocument::getAllDiagnostics() const {
		QList<YSSLangDiagnosticData> result;
		if (d->HostEdit == nullptr) {
			return result;
		}
		const QMap<qint32, YSSConfigLineData*> all = d->HostEdit->getAllBlockData<YSSConfigLineData>();
		for (auto it = all.begin(); it != all.end(); ++it) {
			result += it.value()->Diagnostics;
		}
		return result;
	}
}
