/*
	Visindigo Project Full AI Generated Declaration

	1. This file was entirely generated by AI. There was almost no human
	   involvement in the design of its API and implementation.
	2. Provided that the usage characteristics of the program corresponding
	   to this code are not substantially changed, anyone is free to make
	   fundamental modifications to this code.
	3. This code does not guarantee implementation consistency across
	   generations; it only guarantees that the corresponding program
	   features remain basically stable.
*/
#include "LangServer/YSSLangDocument.h"

namespace YSSFileExt {
	// ---------------------------------------------------------------------------
	// YSSLangDiagnosticData
	// ---------------------------------------------------------------------------
	YSSLangDiagnosticData::YSSLangDiagnosticData() {}
	YSSLangDiagnosticData::YSSLangDiagnosticData(const QString& message, qint32 line, qint32 column, qint32 length,
		Severity severity, const QString& code, const QString& fixAdvice) :
		message(message), line(line), column(column), length(length), severity(severity), code(code), fixAdvice(fixAdvice) {}
	QString YSSLangDiagnosticData::getMessage() const { return message; }
	qint32 YSSLangDiagnosticData::getLine() const { return line; }
	qint32 YSSLangDiagnosticData::getColumn() const { return column; }
	qint32 YSSLangDiagnosticData::getLength() const { return length; }
	YSSLangDiagnosticData::Severity YSSLangDiagnosticData::getSeverity() const { return severity; }
	QString YSSLangDiagnosticData::getCode() const { return code; }
	QString YSSLangDiagnosticData::getFixAdvice() const { return fixAdvice; }

	// ---------------------------------------------------------------------------
	// YSSLangDocument
	// ---------------------------------------------------------------------------
	class YSSLangDocumentPrivate {
		friend class YSSLangDocument;
	protected:
		YSSLangDocument* q;
		YSSLangAnalyzeFn AnalyzeFn;
		QTimer DebounceTimer;
		QStringList Lines;
		QList<QList<YSSLangDiagnosticData>> DiagnosticsCache;
		bool Analyzed = false;

		void scheduleAnalyze() {
			DebounceTimer.start(0);
		}
	};

	YSSLangDocument::YSSLangDocument(YSSLangAnalyzeFn analyzeFn, QObject* parent) : QObject(parent) {
		d = new YSSLangDocumentPrivate();
		d->q = this;
		d->AnalyzeFn = analyzeFn;
		d->DebounceTimer.setSingleShot(true);
		connect(&d->DebounceTimer, &QTimer::timeout, this, &YSSLangDocument::analyze);
	}

	YSSLangDocument::~YSSLangDocument() {
		delete d;
	}

	void YSSLangDocument::onSyntaxHighlighter(const QString& text, qint32 lineIndex) {
		if (lineIndex < 0) return;
		while (d->Lines.size() <= lineIndex) {
			d->Lines.append(QString());
		}
		if (d->Lines[lineIndex] == text && d->Analyzed) {
			return; // 内容未变，无需重新分析
		}
		d->Lines[lineIndex] = text;
		d->scheduleAnalyze();
	}

	void YSSLangDocument::onLinesAdded(qint32 startLine, qint32 count) {
		if (startLine < 0 || count <= 0) return;
		// 补齐起始行之前的缺口（理论上不应出现）
		while (d->Lines.size() < startLine) {
			d->Lines.append(QString());
		}
		for (qint32 i = 0; i < count; ++i) {
			if (startLine >= d->Lines.size()) {
				d->Lines.append(QString());
			}
			else {
				d->Lines.insert(startLine, QString());
			}
		}
		d->Analyzed = false;
		d->scheduleAnalyze();
	}

	void YSSLangDocument::onLinesRemoved(qint32 startLine, qint32 count) {
		if (startLine < 0 || count <= 0) return;
		for (qint32 i = 0; i < count; ++i) {
			if (startLine < d->Lines.size()) {
				d->Lines.removeAt(startLine);
			}
		}
		d->Analyzed = false;
		d->scheduleAnalyze();
	}

	void YSSLangDocument::analyze() {
		QList<YSSLangDiagnosticData> allDiags;
		if (d->AnalyzeFn) {
			d->AnalyzeFn(d->Lines, &allDiags);
		}
		const qint32 lineCount = d->Lines.size();
		d->DiagnosticsCache.clear();
		for (qint32 i = 0; i < lineCount; ++i) {
			d->DiagnosticsCache.append(QList<YSSLangDiagnosticData>());
		}
		for (const YSSLangDiagnosticData& diag : allDiags) {
			const qint32 l = diag.getLine();
			if (l >= 0 && l < d->DiagnosticsCache.size()) {
				d->DiagnosticsCache[l].append(diag);
			}
		}
		d->Analyzed = true;
		emit contentChanged();
	}

	QList<YSSLangDiagnosticData> YSSLangDocument::getDiagnostics(qint32 lineNumber) const {
		if (lineNumber < 0 || lineNumber >= d->DiagnosticsCache.size()) {
			return QList<YSSLangDiagnosticData>();
		}
		return d->DiagnosticsCache[lineNumber];
	}

	QList<YSSLangDiagnosticData> YSSLangDocument::getAllDiagnostics() const {
		QList<YSSLangDiagnosticData> result;
		for (const QList<YSSLangDiagnosticData>& list : d->DiagnosticsCache) {
			result += list;
		}
		return result;
	}
}
