/*
	Visindigo Project Full AI Generated Declaration

	1. This file was entirely generated by AI. There was almost no human
	   involvement in the design of its API and implementation.
	2. Provided that the usage characteristics of the program corresponding
	   to this code are not substantially changed, anyone is free to make
	   fundamental modifications to this code.
	3. This code does not guarantee implementation consistency across
	   generations; it only guarantees that the corresponding program
	   features remain basically stable.
*/
#include "LangServer/YSSLangHighlighter.h"
#include <Editor/TextEdit.h>
#include <Editor/FileEditWidget.h>
#include <Editor/ColorThemeProvider.h>
#include <QtCore/qmap.h>
#include <QtCore/qurl.h>

namespace YSSFileExt {
	class YSSLangHighlighterPrivate {
		friend class YSSLangHighlighter;
	protected:
		QString FilePath;
		YSSLangDocument* Document = nullptr;
		QMap<QString, YSSCore::Editor::StyleData> CurrentTheme;
		static QMap<QString, YSSLangDocument*> DocumentMap;
	};
	QMap<QString, YSSLangDocument*> YSSLangHighlighterPrivate::DocumentMap;

	YSSLangHighlighter::YSSLangHighlighter(YSSCore::Editor::TextEdit* parent, YSSLangAnalyzeFn analyzeFn) :
		SyntaxHighlighter(parent) {
		d = new YSSLangHighlighterPrivate();
		d->FilePath = parent->getFilePath();
		YSSLangDocument* doc = new YSSLangDocument(analyzeFn);
		YSSLangHighlighter::setDocument(parent->getFilePath(), doc);
		d->Document = YSSLangHighlighter::getDocument(d->FilePath);
		connect(d->Document, &YSSLangDocument::contentChanged, this, &YSSLangHighlighter::rehighlight_s);
		connect(parent, &YSSCore::Editor::FileEditWidget::fileRenamed, this, [this](const QString& oldPath, const QString& newPath) {
			YSSLangHighlighter::renameDocument(oldPath, newPath);
			d->FilePath = newPath;
			});
	}

	YSSLangHighlighter::~YSSLangHighlighter() {
		YSSLangHighlighter::deleteDocument(d->FilePath);
		delete d;
	}

	void YSSLangHighlighter::onThemeChanged(const QMap<QString, YSSCore::Editor::StyleData>& theme) {
		d->CurrentTheme = theme;
	}

	void YSSLangHighlighter::onBlockAdded(qint32 startBlockNumber, qint32 count) {
		if (d->Document) {
			d->Document->onLinesAdded(startBlockNumber, count);
		}
	}

	void YSSLangHighlighter::onBlockRemoved(qint32 startBlockNumber, qint32 count) {
		if (d->Document) {
			d->Document->onLinesRemoved(startBlockNumber, count);
		}
	}

	void YSSLangHighlighter::setFormatWithColorKey(int start, int count, const QString& styleKey) {
		YSSCore::Editor::StyleData styleData = d->CurrentTheme.value(styleKey, YSSCore::Editor::StyleData());
		QTextCharFormat format;
		format.setForeground(styleData.getTextColor());
		if (styleData.isBgColorEnabled()) {
			format.setBackground(styleData.getBgColor());
		}
		if (styleData.getUnderlineType() != YSSCore::Editor::StyleData::UnderlineType::NoUnderline) {
			format.setUnderlineColor(styleData.getLineColor());
			format.setUnderlineStyle(QTextCharFormat::UnderlineStyle(styleData.getUnderlineType()));
		}
		format.setFontWeight(styleData.isBold() ? QFont::Bold : QFont::Normal);
		format.setFontItalic(styleData.isItalic());
		setFormat(start, count, format);
	}

	void YSSLangHighlighter::renderDiagnostic(const YSSLangDiagnosticData& diagnostic) {
		const int column = diagnostic.getColumn();
		const int length = qMax(diagnostic.getLength(), 1);
		if (column < 0) return;
		const QString code = diagnostic.getCode();
		if (diagnostic.getSeverity() == YSSLangDiagnosticData::Severity::Warning) {
			createWarningMessage(diagnostic.getMessage(), column, length, code, QUrl(), diagnostic.getFixAdvice());
		}
		else if (diagnostic.getSeverity() == YSSLangDiagnosticData::Severity::Info) {
			createInfoMessage(diagnostic.getMessage(), column, length, code, QUrl(), diagnostic.getFixAdvice());
		}
		else {
			createErrorMessage(diagnostic.getMessage(), column, length, code, QUrl(), diagnostic.getFixAdvice());
		}
	}

	void YSSLangHighlighter::renderDiagnostics(qint32 blockNumber) {
		if (!d->Document) return;
		const QList<YSSLangDiagnosticData> diagnostics = d->Document->getDiagnostics(blockNumber);
		for (const YSSLangDiagnosticData& diagnostic : diagnostics) {
			renderDiagnostic(diagnostic);
		}
	}

	void YSSLangHighlighter::onBlockChanged(const QString& text, int blockNumber) {
		if (!d->Document) return;
		d->Document->onSyntaxHighlighter(text, blockNumber);
		colorLine(text);
		renderDiagnostics(blockNumber);
	}

	void YSSLangHighlighter::setDocument(const QString& filePath, YSSLangDocument* doc) {
		YSSLangHighlighterPrivate::DocumentMap.insert(filePath, doc);
	}
	void YSSLangHighlighter::deleteDocument(const QString& filePath) {
		YSSLangDocument* doc = YSSLangHighlighterPrivate::DocumentMap.value(filePath, nullptr);
		if (doc) {
			delete doc;
		}
		YSSLangHighlighterPrivate::DocumentMap.remove(filePath);
	}
	void YSSLangHighlighter::renameDocument(const QString& oldFilePath, const QString& newFilePath) {
		YSSLangDocument* doc = YSSLangHighlighterPrivate::DocumentMap.value(oldFilePath, nullptr);
		if (doc) {
			YSSLangHighlighterPrivate::DocumentMap.remove(oldFilePath);
			YSSLangHighlighterPrivate::DocumentMap.insert(newFilePath, doc);
		}
	}
	YSSLangDocument* YSSLangHighlighter::getDocument(const QString& filePath) {
		return YSSLangHighlighterPrivate::DocumentMap.value(filePath, nullptr);
	}
}
