#pragma execution_character_set("utf-8")
#pragma once
// This file is auto generated by YSSCore/pytools/AutoVersionFromGIT.py
// Do not modify this file manually
#define YSSCore_VERSION_BUILD 37
#define YSSCore_VERSION_BUILD_DATE "2025-07-29"
#define YSSCore_VERSION_BUILD_TIME "00:22:22"
#define YSSCore_VERSION_NICKNAME "Technical Preview 5"
