#pragma execution_character_set("utf-8")
#pragma once
// This file is auto generated by YSSCore/pytools/AutoVersionFromGIT.py
// Do not modify this file manually
#define YSSCore_VERSION_BUILD 6
#define YSSCore_VERSION_BUILD_DATE "2025-05-05"
#define YSSCore_VERSION_BUILD_TIME "01:29:36"
