/*
	Visindigo Project Full AI Generated Declaration

	1. This file was entirely generated by AI. There was almost no human
	   involvement in the design of its API and implementation.
	2. Provided that the usage characteristics of the program corresponding
	   to this code are not substantially changed, anyone is free to make
	   fundamental modifications to this code.
	3. This code does not guarantee implementation consistency across
	   generations; it only guarantees that the corresponding program
	   features remain basically stable.
*/
#ifndef Plugin_YSSFileExt_LangServer_JsonDocument_h
#define Plugin_YSSFileExt_LangServer_JsonDocument_h
#include <QtCore/qobject.h>
#include <QtCore/qstring.h>
#include <QtCore/qstringlist.h>
#include <QtCore/qlist.h>
#include <QtCore/qtimer.h>

namespace YSSFileExt {
	/*!
		\class YSSFileExt::JsonLangDiagnosticData
		\brief 一条 JSON 语法诊断信息（行、列、长度、类型、消息与修复建议）。
		\since YSS 0.16.0

		模仿 ASERStudio::AStorySyntax::AStoryXDiagnosticData 的简单值类型。
	*/
	class JsonLangDiagnosticData {
	public:
		enum DiagnosticType {
			Undefined = 0x0000,
			UnknownError = 0x1000,
			UnexpectedToken,        // 意外的字符 / 无效字面量
			UnterminatedString,     // 字符串未闭合
			InvalidNumber,          // 无效的数字
			InvalidEscape,          // 无效的转义序列
			ExpectedColon,          // 期望 ':' 
			ExpectedValue,          // 期望一个值
			ExpectedKey,            // 期望键名（字符串）
			ExpectedComma,          // 期望 ',' 
			TrailingComma,          // 多余的逗号
			UnclosedBracket,        // 括号未闭合
			DuplicateKey,           // 键名重复
			UnexpectedContent,      // 顶层多余内容
			UnknownWarning = 0x2000,
		};
	public:
		JsonLangDiagnosticData();
		JsonLangDiagnosticData(const QString& message, qint32 line, qint32 column, qint32 length,
			DiagnosticType type = DiagnosticType::Undefined, const QString& fixAdvice = QString());
	public:
		QString getMessage() const;
		qint32 getLine() const;
		qint32 getColumn() const;
		qint32 getLength() const;
		QString getFixAdvice() const;
		DiagnosticType getType() const;
	private:
		QString message;
		qint32 line = -1;
		qint32 column = -1;
		qint32 length = 1;
		DiagnosticType type = DiagnosticType::Undefined;
		QString fixAdvice;
	};

	/*!
		\enum YSSFileExt::JsonTokenType
		\brief JSON 词法单元类型。
	*/
	enum class JsonTokenType {
		Invalid,
		EndOfFile,
		LBrace,     // {
		RBrace,     // }
		LBracket,   // [
		RBracket,   // ]
		Colon,      // :
		Comma,      // ,
		String,     // "..."
		Number,     // 123 / 1.5 / -2e3
		True,       // true
		False,      // false
		Null,       // null
		Unexpected, // 其它意外字符/单元（词法错误，附带诊断）
	};

	/*!
		\struct YSSFileExt::JsonToken
		\brief 一个 JSON 词法单元，含类型、文本及（行、列、长度）位置。
	*/
	struct JsonToken {
		JsonTokenType type = JsonTokenType::Invalid;
		QString text;
		qint32 line = 0;    // 0-based
		qint32 column = 0;  // 0-based，行内列号
		qint32 length = 0;
	};

	/*!
		\brief 对一行 JSON 文本进行词法分析。
		\a line 待分析的单行文本；\a baseLine 该行在文档中的 0-based 行号。
		\a diagnostics 非空时，将词法级错误（未闭合字符串、无效数字等）追加到其中。
		\return 该行的词法单元列表（不含 EndOfFile）。
	*/
	QList<JsonToken> lexJsonLine(const QString& line, qint32 baseLine, QList<JsonLangDiagnosticData>* diagnostics = nullptr);

	class JsonLangDocumentPrivate;
	/*!
		\class YSSFileExt::JsonLangDocument
		\brief 对整个 JSON 文档的封装：维护行内容、进行全文档语法分析并存储逐行诊断。
		\since YSS 0.16.0

		参考 ASERStudio::AStorySyntax::AStoryXDocument：由 SyntaxHighlighter 在
		onBlockChanged 中调用 onSyntaxHighlighter 更新行内容，解析采用防抖定时器
		延迟到事件循环，完成后发出 contentChanged 信号，供 Highlighter 重新着色并
		渲染诊断消息。
	*/
	class JsonLangDocument :public QObject {
		Q_OBJECT;
	signals:
		/*! 全文档重新分析完成，诊断缓存已刷新。 */
		void contentChanged();
	public:
		JsonLangDocument(QObject* parent = nullptr);
		~JsonLangDocument();
		/*! 由 Highlighter 在 onBlockChanged 中调用，更新一行的内容并安排重新分析。 */
		void onSyntaxHighlighter(const QString& text, qint32 lineIndex);
		/*! 行被添加时通知文档（Highlighter 的 onBlockAdded）。 */
		void onLinesAdded(qint32 startLine, qint32 count);
		/*! 行被删除时通知文档（Highlighter 的 onBlockRemoved）。 */
		void onLinesRemoved(qint32 startLine, qint32 count);
		/*! 立即（同步）重新分析整个文档并刷新诊断缓存。 */
		void analyze();
		/*! 获取指定行（0-based）的诊断信息。 */
		QList<JsonLangDiagnosticData> getDiagnostics(qint32 lineNumber) const;
		/*! 获取全部诊断信息。 */
		QList<JsonLangDiagnosticData> getAllDiagnostics() const;
	private:
		JsonLangDocumentPrivate* d;
	};
}
#endif // Plugin_YSSFileExt_LangServer_JsonDocument_h
