/*
	Visindigo Project Full AI Generated Declaration

	1. This file was entirely generated by AI. There was almost no human
	   involvement in the design of its API and implementation.
	2. Provided that the usage characteristics of the program corresponding
	   to this code are not substantially changed, anyone is free to make
	   fundamental modifications to this code.
	3. This code does not guarantee implementation consistency across
	   generations; it only guarantees that the corresponding program
	   features remain basically stable.
*/
#ifndef Plugin_YSSFileExt_LangServer_JsonLangServer_h
#define Plugin_YSSFileExt_LangServer_JsonLangServer_h
#include <Editor/LangServer.h>
#include <Editor/EditorPlugin.h>
#include <Editor/SyntaxHighlighter.h>
#include "LangServer/JsonDocument.h"
#include <QtCore/qmap.h>

namespace YSSFileExt {
	class JsonLangServerPrivate;
	/*!
		\class YSSFileExt::JsonLangServer
		\brief JSON 语言服务器：提供 Visindigo 2024（Light/Dark）主题着色与 JSON 语法错误诊断。
		\since YSS 0.16.0

		参考 ASERStudio::YSS::AStoryXLanguageServer：
		- 构造函数加载 Visindigo 2024 静态颜色主题，并跟随程序主题在 Light/Dark 间自动切换；
		- 为每个文件路径维护一个共享的 JsonLangDocument，供 SyntaxHighlighter 使用。
	*/
	class JsonLangServer :public YSSCore::Editor::LangServer {
	public:
		JsonLangServer(YSSCore::Editor::EditorPlugin* plugin);
		virtual YSSCore::Editor::SyntaxHighlighter* createHighlighter(YSSCore::Editor::TextEdit* doc) override;
		static void setJsonDocument(const QString& filePath, JsonLangDocument* doc);
		static void deleteJsonDocument(const QString& filePath);
		static void renameJsonDocument(const QString& oldFilePath, const QString& newFilePath);
		static JsonLangDocument* getJsonDocument(const QString& filePath);
	};

	class JsonLangHighlighterPrivate;
	/*!
		\class YSSFileExt::JsonLangHighlighter
		\brief JSON 语法高亮器：按主题样式着色 JSON 单元，并渲染 JsonLangDocument 产出的诊断消息。
		\since YSS 0.16.0

		参考 ASERStudio::YSS::LS_AStoryXSyntaxHighlighter：
		- 通过 onThemeChanged 缓存当前主题，用 setFormatWithColorKey 按样式键着色；
		- 通过 createError/Warning/InfoMessage 渲染诊断。
	*/
	class JsonLangHighlighter :public YSSCore::Editor::SyntaxHighlighter {
		Q_OBJECT;
	public:
		JsonLangHighlighter(YSSCore::Editor::TextEdit* parent = nullptr);
		virtual ~JsonLangHighlighter();
		virtual void onBlockChanged(const QString& text, int blockNumber) override;
		virtual void onBlockRemoved(qint32 startBlockNumber, qint32 count) override;
		virtual void onBlockAdded(qint32 startBlockNumber, qint32 count) override;
		virtual void onThemeChanged(const QMap<QString, YSSCore::Editor::StyleData>& theme) override;
		void setFormatWithColorKey(int start, int count, const QString& styleKey);
		void DiagnosticTransform(const JsonLangDiagnosticData& diagnostic);
	private:
		JsonLangHighlighterPrivate* d;
	};
}
#endif // Plugin_YSSFileExt_LangServer_JsonLangServer_h
