/*
	Visindigo Project Full AI Generated Declaration

	1. This file was entirely generated by AI. There was almost no human
	   involvement in the design of its API and implementation.
	2. Provided that the usage characteristics of the program corresponding
	   to this code are not substantially changed, anyone is free to make
	   fundamental modifications to this code.
	3. This code does not guarantee implementation consistency across
	   generations; it only guarantees that the corresponding program
	   features remain basically stable.
*/
#ifndef Plugin_YSSFileExt_LangServer_JsonLang_h
#define Plugin_YSSFileExt_LangServer_JsonLang_h
#include <QtCore/qstring.h>
#include <QtCore/qstringlist.h>
#include <QtCore/qlist.h>
#include "LangServer/YSSConfigLangServer.h"

namespace YSSFileExt {
	class JsonLangDiagnosticData {
	public:
		enum DiagnosticType {
			Undefined = 0x0000,
			UnknownError = 0x1000,
			UnexpectedToken,        // 意外的字符 / 无效字面量
			UnterminatedString,     // 字符串未闭合
			InvalidNumber,          // 无效的数字
			InvalidEscape,          // 无效的转义序列
			ExpectedColon,          // 期望 ':' 
			ExpectedValue,          // 期望一个值
			ExpectedKey,            // 期望键名（字符串）
			ExpectedComma,          // 期望 ',' 
			TrailingComma,          // 多余的逗号
			UnclosedBracket,        // 括号未闭合
			DuplicateKey,           // 键名重复
			UnexpectedContent,      // 顶层多余内容
			UnknownWarning = 0x2000,
		};
	public:
		JsonLangDiagnosticData();
		JsonLangDiagnosticData(const QString& message, qint32 line, qint32 column, qint32 length,
			DiagnosticType type = DiagnosticType::Undefined, const QString& fixAdvice = QString());
	public:
		QString getMessage() const;
		qint32 getLine() const;
		qint32 getColumn() const;
		qint32 getLength() const;
		QString getFixAdvice() const;
		DiagnosticType getType() const;
	private:
		QString message;
		qint32 line = -1;
		qint32 column = -1;
		qint32 length = 1;
		DiagnosticType type = DiagnosticType::Undefined;
		QString fixAdvice;
	};

	enum class JsonTokenType {
		Invalid,
		EndOfFile,
		LBrace,     // {
		RBrace,     // }
		LBracket,   // [
		RBracket,   // ]
		Colon,      // :
		Comma,      // ,
		String,     // "..."
		Number,     // 123 / 1.5 / -2e3
		True,       // true
		False,      // false
		Null,       // null
		Unexpected, // 其它意外字符/单元（词法错误，附带诊断）
	};

	struct JsonToken {
		JsonTokenType type = JsonTokenType::Invalid;
		QString text;
		qint32 line = 0;    // 0-based
		qint32 column = 0;  // 0-based，行内列号
		qint32 length = 0;
	};

	QList<JsonToken> lexJsonLine(const QString& line, qint32 baseLine, QList<JsonLangDiagnosticData>* diagnostics = nullptr);

	class JsonLangServer :public YSSConfigLangServer {
	public:
		JsonLangServer(YSSCore::Editor::EditorPlugin* plugin);
	};
}
#endif // Plugin_YSSFileExt_LangServer_JsonLang_h
