/*
	Visindigo Project Full AI Generated Declaration

	1. This file was entirely generated by AI. There was almost no human
	   involvement in the design of its API and implementation.
	2. Provided that the usage characteristics of the program corresponding
	   to this code are not substantially changed, anyone is free to make
	   fundamental modifications to this code.
	3. This code does not guarantee implementation consistency across
	   generations; it only guarantees that the corresponding program
	   features remain basically stable.
*/
#ifndef Plugin_YSSFileExt_LangServer_JsonLangServer_h
#define Plugin_YSSFileExt_LangServer_JsonLangServer_h
#include <Editor/LangServer.h>
#include <Editor/EditorPlugin.h>
#include <Editor/SyntaxHighlighter.h>
#include "LangServer/JsonDocument.h"
#include <QtCore/qmap.h>

namespace YSSFileExt {
	class JsonLangServerPrivate;
	class JsonLangServer :public YSSCore::Editor::LangServer {
	public:
		JsonLangServer(YSSCore::Editor::EditorPlugin* plugin);
		virtual YSSCore::Editor::SyntaxHighlighter* createHighlighter(YSSCore::Editor::TextEdit* doc) override;
		static void setJsonDocument(const QString& filePath, JsonLangDocument* doc);
		static void deleteJsonDocument(const QString& filePath);
		static void renameJsonDocument(const QString& oldFilePath, const QString& newFilePath);
		static JsonLangDocument* getJsonDocument(const QString& filePath);
	};

	class JsonLangHighlighterPrivate;
	class JsonLangHighlighter :public YSSCore::Editor::SyntaxHighlighter {
		Q_OBJECT;
	public:
		JsonLangHighlighter(YSSCore::Editor::TextEdit* parent = nullptr);
		virtual ~JsonLangHighlighter();
		virtual void onBlockChanged(const QString& text, int blockNumber) override;
		virtual void onBlockRemoved(qint32 startBlockNumber, qint32 count) override;
		virtual void onBlockAdded(qint32 startBlockNumber, qint32 count) override;
		virtual void onThemeChanged(const QMap<QString, YSSCore::Editor::StyleData>& theme) override;
		void setFormatWithColorKey(int start, int count, const QString& styleKey);
		void DiagnosticTransform(const JsonLangDiagnosticData& diagnostic);
	private:
		JsonLangHighlighterPrivate* d;
	};
}
#endif // Plugin_YSSFileExt_LangServer_JsonLangServer_h
