/*
	Visindigo Project Full AI Generated Declaration

	1. This file was entirely generated by AI. There was almost no human
	   involvement in the design of its API and implementation.
	2. Provided that the usage characteristics of the program corresponding
	   to this code are not substantially changed, anyone is free to make
	   fundamental modifications to this code.
	3. This code does not guarantee implementation consistency across
	   generations; it only guarantees that the corresponding program
	   features remain basically stable.
*/
#ifndef YSSFileExt_LangServer_TomlLangServer_h
#define YSSFileExt_LangServer_TomlLangServer_h
#include <Editor/LangServer.h>
#include <Editor/EditorPlugin.h>
#include "LangServer/YSSLangHighlighter.h"

namespace YSSFileExt {
	/*!
		\class YSSFileExt::TomlLangServer
		\brief TOML 语言服务器：提供 Visindigo 2024（Light/Dark）主题着色与 TOML 语法诊断。
		\since YSS 0.16.0

		参考 JsonLangServer：加载 Visindigo 2024 静态颜色主题并跟随程序主题切换；
		通过共享的 YSSLangHighlighter / YSSLangDocument 提供高亮与诊断。
	*/
	class TomlLangServer :public YSSCore::Editor::LangServer {
	public:
		TomlLangServer(YSSCore::Editor::EditorPlugin* plugin);
		virtual YSSCore::Editor::SyntaxHighlighter* createHighlighter(YSSCore::Editor::TextEdit* doc) override;
	};

	/*!
		\class YSSFileExt::TomlLangHighlighter
		\brief TOML 语法高亮器：按主题样式着色 TOML 单元（表头、键、字符串、数字等）。
		\since YSS 0.16.0
	*/
	class TomlLangHighlighter :public YSSLangHighlighter {
	public:
		TomlLangHighlighter(YSSCore::Editor::TextEdit* parent);
		virtual void colorLine(const QString& text) override;
	};
}
#endif // YSSFileExt_LangServer_TomlLangServer_h
