/*
	Visindigo Project Full AI Generated Declaration

	1. This file was entirely generated by AI. There was almost no human
	   involvement in the design of its API and implementation.
	2. Provided that the usage characteristics of the program corresponding
	   to this code are not substantially changed, anyone is free to make
	   fundamental modifications to this code.
	3. This code does not guarantee implementation consistency across
	   generations; it only guarantees that the corresponding program
	   features remain basically stable.
*/
#ifndef Plugin_YSSFileExt_LangServer_XmlLangServer_h
#define Plugin_YSSFileExt_LangServer_XmlLangServer_h
#include <Editor/LangServer.h>
#include <Editor/EditorPlugin.h>
#include "LangServer/YSSLangHighlighter.h"

namespace YSSFileExt {
	/*!
		\class YSSFileExt::XmlLangServer
		\brief XML 语言服务器：提供 Visindigo 2024（Light/Dark）主题着色与 XML 语法诊断。
		\since YSS 0.16.0

		参考 JsonLangServer：加载 Visindigo 2024 静态颜色主题并跟随程序主题切换；
		通过共享的 YSSLangHighlighter / YSSLangDocument 提供高亮与诊断。
	*/
	class XmlLangServer :public YSSCore::Editor::LangServer {
	public:
		XmlLangServer(YSSCore::Editor::EditorPlugin* plugin);
		virtual YSSCore::Editor::SyntaxHighlighter* createHighlighter(YSSCore::Editor::TextEdit* doc) override;
	};

	/*!
		\class YSSFileExt::XmlLangHighlighter
		\brief XML 语法高亮器：按主题样式着色 XML 单元（标签、属性、注释、CDATA 等）。
		\since YSS 0.16.0
	*/
	class XmlLangHighlighter :public YSSLangHighlighter {
	public:
		XmlLangHighlighter(YSSCore::Editor::TextEdit* parent);
		virtual void colorLine(const QString& text) override;
	};
}
#endif // Plugin_YSSFileExt_LangServer_XmlLangServer_h
