/*
	Visindigo Project Full AI Generated Declaration

	1. This file was entirely generated by AI. There was almost no human
	   involvement in the design of its API and implementation.
	2. Provided that the usage characteristics of the program corresponding
	   to this code are not substantially changed, anyone is free to make
	   fundamental modifications to this code.
	3. This code does not guarantee implementation consistency across
	   generations; it only guarantees that the corresponding program
	   features remain basically stable.
*/
#ifndef Plugin_YSSFileExt_LangServer_YamlLangServer_h
#define Plugin_YSSFileExt_LangServer_YamlLangServer_h
#include <Editor/LangServer.h>
#include <Editor/EditorPlugin.h>
#include "LangServer/YSSLangHighlighter.h"

namespace YSSFileExt {
	class YamlLangServer :public YSSCore::Editor::LangServer {
	public:
		YamlLangServer(YSSCore::Editor::EditorPlugin* plugin);
		virtual YSSCore::Editor::SyntaxHighlighter* createHighlighter(YSSCore::Editor::TextEdit* doc) override;
	};

	class YamlLangHighlighter :public YSSLangHighlighter {
	public:
		YamlLangHighlighter(YSSCore::Editor::TextEdit* parent);
		virtual void colorLine(const QString& text) override;
	};
}
#endif // Plugin_YSSFileExt_LangServer_YamlLangServer_h
