/*
	Visindigo Project Full AI Generated Declaration

	1. This file was entirely generated by AI. There was almost no human
	   involvement in the design of its API and implementation.
	2. Provided that the usage characteristics of the program corresponding
	   to this code are not substantially changed, anyone is free to make
	   fundamental modifications to this code.
	3. This code does not guarantee implementation consistency across
	   generations; it only guarantees that the corresponding program
	   features remain basically stable.
*/
#ifndef Plugin_YSSFileExt_LangServer_YSSConfigLangHighlighter_h
#define Plugin_YSSFileExt_LangServer_YSSConfigLangHighlighter_h
#include <functional>
#include <QtCore/qmap.h>
#include <Editor/SyntaxHighlighter.h>
#include "LangServer/YSSConfigLangDocument.h"

namespace YSSFileExt {
	class YSSConfigLangHighlighter;
	// 按样式键为一行文本着色，由各语言提供。
	using YSSConfigColorFn = std::function<void(YSSConfigLangHighlighter* highlighter, const QString& text)>;

	class YSSConfigLangHighlighterPrivate;
	class YSSConfigLangHighlighter :public YSSCore::Editor::SyntaxHighlighter {
		Q_OBJECT;
	public:
		YSSConfigLangHighlighter(YSSCore::Editor::TextEdit* parent, YSSConfigAnalyzeFn analyzeFn, YSSConfigColorFn colorFn);
		virtual ~YSSConfigLangHighlighter();
		// 用当前主题的指定样式键对 [start, start+count) 着色。
		void setFormatWithColorKey(int start, int count, const QString& styleKey);
		// 上一块的着色状态（多行结构用，如 XML 的注释 / CDATA 跨行）。
		int getPreviousBlockState() const;
		// 记录本块的着色状态。
		void applyBlockState(int state);
		// 渲染指定行（0-based）的诊断。
		void renderDiagnostics(qint32 blockNumber);
		// 渲染单条诊断（按严重级别转为错误/警告/信息消息）。
		void renderDiagnostic(const YSSLangDiagnosticData& diagnostic);
		// 本高亮器使用的文档，诊断都在它上面。
		YSSConfigLangDocument* getDocument() const;
	protected:
		virtual void onBlockChanged(const QString& text, int blockNumber) override;
		virtual void onThemeChanged(const QMap<QString, YSSCore::Editor::StyleData>& theme) override;
	private:
		YSSConfigLangHighlighterPrivate* d;
	};
}
#endif // Plugin_YSSFileExt_LangServer_YSSConfigLangHighlighter_h
