/*
	Visindigo Project Full AI Generated Declaration

	1. This file was entirely generated by AI. There was almost no human
	   involvement in the design of its API and implementation.
	2. Provided that the usage characteristics of the program corresponding
	   to this code are not substantially changed, anyone is free to make
	   fundamental modifications to this code.
	3. This code does not guarantee implementation consistency across
	   generations; it only guarantees that the corresponding program
	   features remain basically stable.
*/
#ifndef Plugin_YSSFileExt_LangServer_YSSConfigLangServer_h
#define Plugin_YSSFileExt_LangServer_YSSConfigLangServer_h
#include <QtCore/qstringlist.h>
#include <Editor/LangServer.h>
#include <Editor/EditorPlugin.h>
#include "LangServer/YSSConfigLangHighlighter.h"

namespace YSSFileExt {
	class YSSConfigLangServer :public YSSCore::Editor::LangServer {
	public:
		YSSConfigLangServer(YSSCore::Editor::EditorPlugin* plugin, const QString& name, const QString& id,
			const QString& langID, const QStringList& supportedExts,
			const QStringList& syntaxThemeFiles, const QString& templateTextPath,
			YSSConfigAnalyzeFn analyzeFn, YSSConfigColorFn colorFn);
		virtual YSSCore::Editor::SyntaxHighlighter* createHighlighter(YSSCore::Editor::TextEdit* doc) override;
	private:
		YSSConfigAnalyzeFn AnalyzeFn;
		YSSConfigColorFn ColorFn;
	};
}
#endif // Plugin_YSSFileExt_LangServer_YSSConfigLangServer_h
