/*
	Visindigo Project Full AI Generated Declaration

	1. This file was entirely generated by AI. There was almost no human
	   involvement in the design of its API and implementation.
	2. Provided that the usage characteristics of the program corresponding
	   to this code are not substantially changed, anyone is free to make
	   fundamental modifications to this code.
	3. This code does not guarantee implementation consistency across
	   generations; it only guarantees that the corresponding program
	   features remain basically stable.
*/
#ifndef YSSFileExt_LangServer_YSSLangDocument_h
#define YSSFileExt_LangServer_YSSLangDocument_h
#include <QtCore/qobject.h>
#include <QtCore/qstring.h>
#include <QtCore/qstringlist.h>
#include <QtCore/qlist.h>
#include <QtCore/qtimer.h>
#include <functional>

namespace YSSFileExt {
	/*!
		\class YSSFileExt::YSSLangDiagnosticData
		\brief 一条通用语法诊断信息（行、列、长度、严重级别、代码与修复建议）。
		\since YSS 0.16.0

		供 YAMLLangServer / XMLLangServer / TOMLLangServer / iniLangServer
		共同使用的简单值类型，模仿 ASERStudio::AStorySyntax::AStoryXDiagnosticData。
	*/
	class YSSLangDiagnosticData {
	public:
		enum class Severity {
			Info,
			Warning,
			Error,
		};
	public:
		YSSLangDiagnosticData();
		YSSLangDiagnosticData(const QString& message, qint32 line, qint32 column, qint32 length,
			Severity severity = Severity::Error, const QString& code = QString(), const QString& fixAdvice = QString());
	public:
		QString getMessage() const;
		qint32 getLine() const;
		qint32 getColumn() const;
		qint32 getLength() const;
		Severity getSeverity() const;
		QString getCode() const;
		QString getFixAdvice() const;
	private:
		QString message;
		qint32 line = -1;
		qint32 column = -1;
		qint32 length = 1;
		Severity severity = Severity::Error;
		QString code;
		QString fixAdvice;
	};

	class YSSLangDocumentPrivate;

	/*!
		\brief 全文档分析函数：输入文档全部行，产出诊断列表，由各语言提供。
	*/
	using YSSLangAnalyzeFn = std::function<void(const QStringList& lines, QList<YSSLangDiagnosticData>* diags)>;

	/*!
		\class YSSFileExt::YSSLangDocument
		\brief 通用语言文档：维护行内容、防抖全文档分析并存储逐行诊断。
		\since YSS 0.16.0

		参考 JsonLangDocument：由 SyntaxHighlighter 在 onBlockChanged 中调用
		onSyntaxHighlighter 更新行内容，解析采用防抖定时器延迟到事件循环，
		完成后发出 contentChanged 信号，供 Highlighter 重新着色并渲染诊断消息。
		各语言通过构造函数传入的 YSSLangAnalyzeFn 提供自己的分析逻辑。
	*/
	class YSSLangDocument :public QObject {
		Q_OBJECT;
	signals:
		/*! 全文档重新分析完成，诊断缓存已刷新。 */
		void contentChanged();
	public:
		YSSLangDocument(YSSLangAnalyzeFn analyzeFn, QObject* parent = nullptr);
		~YSSLangDocument();
		/*! 由 Highlighter 在 onBlockChanged 中调用，更新一行的内容并安排重新分析。 */
		void onSyntaxHighlighter(const QString& text, qint32 lineIndex);
		/*! 行被添加时通知文档（Highlighter 的 onBlockAdded）。 */
		void onLinesAdded(qint32 startLine, qint32 count);
		/*! 行被删除时通知文档（Highlighter 的 onBlockRemoved）。 */
		void onLinesRemoved(qint32 startLine, qint32 count);
		/*! 立即（同步）重新分析整个文档并刷新诊断缓存。 */
		void analyze();
		/*! 获取指定行（0-based）的诊断信息。 */
		QList<YSSLangDiagnosticData> getDiagnostics(qint32 lineNumber) const;
		/*! 获取全部诊断信息。 */
		QList<YSSLangDiagnosticData> getAllDiagnostics() const;
	private:
		YSSLangDocumentPrivate* d;
	};
}
#endif // YSSFileExt_LangServer_YSSLangDocument_h
