/*
	Visindigo Project Full AI Generated Declaration

	1. This file was entirely generated by AI. There was almost no human
	   involvement in the design of its API and implementation.
	2. Provided that the usage characteristics of the program corresponding
	   to this code are not substantially changed, anyone is free to make
	   fundamental modifications to this code.
	3. This code does not guarantee implementation consistency across
	   generations; it only guarantees that the corresponding program
	   features remain basically stable.
*/
#ifndef Plugin_YSSFileExt_LangServer_YSSLangDocument_h
#define Plugin_YSSFileExt_LangServer_YSSLangDocument_h
#include <QtCore/qobject.h>
#include <QtCore/qstring.h>
#include <QtCore/qstringlist.h>
#include <QtCore/qlist.h>
#include <QtCore/qtimer.h>
#include <functional>

namespace YSSFileExt {
	class YSSLangDiagnosticData {
	public:
		enum class Severity {
			Info,
			Warning,
			Error,
		};
	public:
		YSSLangDiagnosticData();
		YSSLangDiagnosticData(const QString& message, qint32 line, qint32 column, qint32 length,
			Severity severity = Severity::Error, const QString& code = QString(), const QString& fixAdvice = QString());
	public:
		QString getMessage() const;
		qint32 getLine() const;
		qint32 getColumn() const;
		qint32 getLength() const;
		Severity getSeverity() const;
		QString getCode() const;
		QString getFixAdvice() const;
	private:
		QString message;
		qint32 line = -1;
		qint32 column = -1;
		qint32 length = 1;
		Severity severity = Severity::Error;
		QString code;
		QString fixAdvice;
	};

	class YSSLangDocumentPrivate;

	// 全文档分析函数：输入文档全部行，产出诊断列表，由各语言提供。
	using YSSLangAnalyzeFn = std::function<void(const QStringList& lines, QList<YSSLangDiagnosticData>* diags)>;

	class YSSLangDocument :public QObject {
		Q_OBJECT;
	signals:
		// 全文档重新分析完成，诊断缓存已刷新。
		void contentChanged();
	public:
		YSSLangDocument(YSSLangAnalyzeFn analyzeFn, QObject* parent = nullptr);
		~YSSLangDocument();
		// 由 Highlighter 在 onBlockChanged 中调用，更新一行的内容并安排重新分析。
		void onSyntaxHighlighter(const QString& text, qint32 lineIndex);
		// 行被添加时通知文档（Highlighter 的 onBlockAdded）。
		void onLinesAdded(qint32 startLine, qint32 count);
		// 行被删除时通知文档（Highlighter 的 onBlockRemoved）。
		void onLinesRemoved(qint32 startLine, qint32 count);
		// 立即（同步）重新分析整个文档并刷新诊断缓存。
		void analyze();
		// 获取指定行（0-based）的诊断信息。
		QList<YSSLangDiagnosticData> getDiagnostics(qint32 lineNumber) const;
		// 获取全部诊断信息。
		QList<YSSLangDiagnosticData> getAllDiagnostics() const;
	private:
		YSSLangDocumentPrivate* d;
	};
}
#endif // Plugin_YSSFileExt_LangServer_YSSLangDocument_h
