/*
	Visindigo Project Full AI Generated Declaration

	1. This file was entirely generated by AI. There was almost no human
	   involvement in the design of its API and implementation.
	2. Provided that the usage characteristics of the program corresponding
	   to this code are not substantially changed, anyone is free to make
	   fundamental modifications to this code.
	3. This code does not guarantee implementation consistency across
	   generations; it only guarantees that the corresponding program
	   features remain basically stable.
*/
#ifndef Plugin_YSSFileExt_FileTemplate_SimpleFileTemplate_h
#define Plugin_YSSFileExt_FileTemplate_SimpleFileTemplate_h
#include <Editor/FileTemplateProvider.h>
#include <QtCore/qstringlist.h>

namespace YSSFileExt {
	class SimpleFileTemplateInitWidgetPrivate;

	class SimpleFileTemplateInitWidget :public YSSCore::Editor::FileTemplateInitWidget {
		Q_OBJECT;
	public:
		SimpleFileTemplateInitWidget(const QString& initFolder, const QString& extension, QWidget* parent = nullptr);
		virtual ~SimpleFileTemplateInitWidget();
	private:
		SimpleFileTemplateInitWidgetPrivate* d;
	};

	class SimpleFileTemplateProvider :public YSSCore::Editor::FileTemplateProvider {
	public:
		SimpleFileTemplateProvider(YSSCore::Editor::EditorPlugin* plugin, const QString& name, const QString& id,
			const QString& templateID, const QString& templateName, const QString& description,
			const QStringList& tags, const QString& extension);
		virtual YSSCore::Editor::FileTemplateInitWidget* fileInitWidget(const QString& initPath) override;
	private:
		QString Extension;
	};
}
#endif // Plugin_YSSFileExt_FileTemplate_SimpleFileTemplate_h
