/*
	Visindigo Project Full AI Generated Declaration

	1. This file was entirely generated by AI. There was almost no human
	   involvement in the design of its API and implementation.
	2. Provided that the usage characteristics of the program corresponding
	   to this code are not substantially changed, anyone is free to make
	   fundamental modifications to this code.
	3. This code does not guarantee implementation consistency across
	   generations; it only guarantees that the corresponding program
	   features remain basically stable.
*/
#include <QtCore/qlist.h>
#include <QtCore/qmap.h>
#include <QtCore/qobject.h>
#include <QtCore/qstring.h>
#include <QtCore/qstringlist.h>
#include "Agent/Center.h"
#include "Agent/Dialog.h"
#include "Agent/Function.h"
#include "Agent/MCP.h"
#include "Agent/Model.h"
#include "Agent/Prompt.h"
#include "Agent/Provider.h"
#include "Agent/Skill.h"
#include "Agent/private/Center_p.h"
#include "Utility/JsonConfig.h"

namespace Visindigo::Agent {
	Center* CenterPrivate::Instance = nullptr;

	/*!
		\class Visindigo::Agent::Center
		\inheaderfile Agent/Center.h
		\since Visindigo 0.17.0
		\inmodule Visindigo
		\brief 智能体配置与对话的全局注册表。

		Center 集中保存模型池、服务商、技能、工具服务器、函数、提示模板以及
		全部对话，并提供唯一的进程级实例。它是一个单例，但不是一个"什么都干"
		的类：它只负责按 id 存取与给出默认项，真正的执行逻辑在 \l Dialog::run()
		里，这样想换一套执行策略时不必改动注册表。

		按 id 索引而不是按名称，是因为名称是给人看的，可能重复、可能改名，
		而 id 一旦生成就稳定。凭据也都集中在模型池里，Provider 与 Dialog 只保存
		id，于是轮换一次密钥只需要改一处。

		\warning 传入指针的接口（\l addFunction()、\l createDialog() 等）转移所有权。
		销毁必须走对应的 \c remove 接口，直接 \c delete 会让注册表留下悬空指针。
	*/

	/*!
		\since Visindigo 0.17.0

		返回唯一实例，首次调用时创建。实例在进程结束前不会被销毁。
	*/
	Center* Center::getInstance() {
		if (CenterPrivate::Instance == nullptr) {
			CenterPrivate::Instance = new Center();
		}
		return CenterPrivate::Instance;
	}

	/*!
		\since Visindigo 0.17.0

		注册一个模型，以 \l Model::getId() 为键。同 id 会覆盖旧项。

		\note 注册时会保留传入对象原有的 id，因此"先取出、改一改、再放回"是可用的
		更新方式。
	*/
	Center& Center::addModel(const Model& model) {
		if (not model.getId().isEmpty()) {
			d->Models.insert(model.getId(), model);
		}
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		移除一个模型。已经引用该 id 的 Provider 与 Dialog 不会因此报错，只是
		在挑选模型时挑不到它。
	*/
	Center& Center::removeModel(const QString& id) {
		d->Models.remove(id);
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		按 id 返回模型。不存在时返回一个 \l Model::isValid() 为 \c false 的空模型，
		因此判断"有没有"请用 \c isValid() 而不是别的字段。
	*/
	Model Center::getModel(const QString& id) const {
		return d->Models.value(id);
	}

	/*!
		\since Visindigo 0.17.0

		返回全部模型。
	*/
	QList<Model> Center::getModels() const {
		return d->Models.values();
	}

	/*!
		\since Visindigo 0.17.0

		返回全部模型 id。
	*/
	QStringList Center::getModelIds() const {
		return d->Models.keys();
	}

	/*!
		\since Visindigo 0.17.0

		注册一个服务商，以 \l Provider::getId() 为键。同 id 会覆盖旧项。
	*/
	Center& Center::addProvider(const Provider& provider) {
		if (not provider.getId().isEmpty()) {
			d->Providers.insert(provider.getId(), provider);
		}
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		移除一个服务商。若它正是默认服务商，默认项会被一并清空——留着指向一个
		不存在的服务商，只会在下次执行时得到一句莫名其妙的失败。
	*/
	Center& Center::removeProvider(const QString& id) {
		d->Providers.remove(id);
		if (d->DefaultProviderId == id) {
			d->DefaultProviderId.clear();
		}
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		按 id 返回服务商。不存在时返回一个 \l Provider::isValid() 为 \c false
		的空对象。
	*/
	Provider Center::getProvider(const QString& id) const {
		return d->Providers.value(id);
	}

	/*!
		\since Visindigo 0.17.0

		返回全部服务商。
	*/
	QList<Provider> Center::getProviders() const {
		return d->Providers.values();
	}

	/*!
		\since Visindigo 0.17.0

		注册一个全局技能，以名称为键。同名会覆盖旧项。
	*/
	Center& Center::addSkill(const Skill& skill) {
		if (not skill.getName().isEmpty()) {
			d->Skills.insert(skill.getName(), skill);
		}
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		移除一个全局技能。挂载了同名技能的对话不受影响：它们保存的是自己的副本。
	*/
	Center& Center::removeSkill(const QString& name) {
		d->Skills.remove(name);
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		按名称返回全局技能。不存在时返回一个 \l Skill::isValid() 为 \c false 的空对象。
	*/
	Skill Center::getSkill(const QString& name) const {
		return d->Skills.value(name);
	}

	/*!
		\since Visindigo 0.17.0

		返回全部全局技能。
	*/
	QList<Skill> Center::getSkills() const {
		return d->Skills.values();
	}

	/*!
		\since Visindigo 0.17.0

		注册一个全局工具服务器配置，以名称为键。同名会覆盖旧项。
	*/
	Center& Center::addMCP(const MCP& server) {
		if (not server.getName().isEmpty()) {
			d->MCPs.insert(server.getName(), server);
		}
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		移除一个全局工具服务器配置。
	*/
	Center& Center::removeMCP(const QString& name) {
		d->MCPs.remove(name);
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		按名称返回全局工具服务器配置。不存在时返回一个 \l MCP::isValid() 为
		\c false 的空对象。
	*/
	MCP Center::getMCP(const QString& name) const {
		return d->MCPs.value(name);
	}

	/*!
		\since Visindigo 0.17.0

		返回全部全局工具服务器配置。
	*/
	QList<MCP> Center::getMCPs() const {
		return d->MCPs.values();
	}

	/*!
		\since Visindigo 0.17.0

		注册一个全局函数，以 \l Function::getId() 为键，所有权转移给 Center。

		同 id 会替换旧项并释放旧对象。传入 \c nullptr 什么也不做。

		\note 只接受 id 为空的函数是不会成功的——id 既是索引键也是发给模型的工具名，
		没有它这个函数就无法被调用。传入 \c nullptr 与空 id 都不会改变现有注册，
		因此不需要在调用前先判断一次。
	*/
	Center& Center::addFunction(Function* function) {
		if (function == nullptr or function->getId().isEmpty()) {
			return *this;
		}
		removeFunction(function->getId());
		d->Functions.insert(function->getId(), function);
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		移除并释放一个全局函数。挂载了同 id 函数的对话会重新解析到这个空位，
		它们自己的副本不受影响。
	*/
	Center& Center::removeFunction(const QString& id) {
		auto it = d->Functions.find(id);
		if (it != d->Functions.end()) {
			delete it.value();
			d->Functions.erase(it);
		}
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		按 id 返回全局函数。不存在时返回 \c nullptr。

		\note 返回的是借用指针，所有权仍在 Center；调用方不得删除它。
	*/
	Function* Center::getFunction(const QString& id) const {
		return d->Functions.value(id, nullptr);
	}

	/*!
		\since Visindigo 0.17.0

		返回全部全局函数 id。
	*/
	QStringList Center::getFunctionIds() const {
		return d->Functions.keys();
	}

	/*!
		\since Visindigo 0.17.0

		注册一个全局提示模板，以名称为键。同名会覆盖旧项。
	*/
	Center& Center::addPrompt(const Prompt& prompt) {
		if (not prompt.getName().isEmpty()) {
			d->Prompts.insert(prompt.getName(), prompt);
		}
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		移除一个全局提示模板。
	*/
	Center& Center::removePrompt(const QString& name) {
		d->Prompts.remove(name);
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		按名称返回全局提示模板。不存在时返回一个 \l Prompt::isValid() 为 \c false
		的空对象。
	*/
	Prompt Center::getPrompt(const QString& name) const {
		return d->Prompts.value(name);
	}

	/*!
		\since Visindigo 0.17.0

		返回全部全局提示模板。
	*/
	QList<Prompt> Center::getPrompts() const {
		return d->Prompts.values();
	}

	/*!
		\since Visindigo 0.17.0

		设置没有指定服务商的对话默认使用哪一个。传入空串表示取消默认项。

		\note 这里不校验 \a id 是否存在，以便先设默认、后注册服务商；代价是写错
		id 时只会在执行阶段表现为"没有可用的服务商"。
	*/
	Center& Center::setDefaultProvider(const QString& id) {
		d->DefaultProviderId = id;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		返回默认服务商的 id；未设置时返回空串。
	*/
	QString Center::getDefaultProvider() const {
		return d->DefaultProviderId;
	}

	/*!
		\since Visindigo 0.17.0

		建立一条新对话并注册，返回其指针。id 由对话自己在构造时生成。
	*/
	Dialog* Center::createDialog() {
		Dialog* dialog = new Dialog();
		d->Dialogs.insert(dialog->getId(), dialog);
		return dialog;
	}

	/*!
		\since Visindigo 0.17.0

		从存档恢复一条对话并注册，返回其指针。

		先恢复内容再注册，这样注册用的就是存档里的 id，而不是新建时临时生成的那个；
		否则恢复出来的对话会与存档里的引用对不上。
	*/
	Dialog* Center::restoreDialog(const Visindigo::Utility::JsonConfig& json) {
		Dialog* dialog = new Dialog();
		dialog->fromJson(json);
		d->Dialogs.insert(dialog->getId(), dialog);
		return dialog;
	}

	/*!
		\since Visindigo 0.17.0

		导出一条对话的存档。\a dialog 为空时返回空对象。
	*/
	Visindigo::Utility::JsonConfig Center::saveDialog(const Dialog* dialog) const {
		if (dialog == nullptr) {
			return Visindigo::Utility::JsonConfig();
		}
		return dialog->toJson();
	}

	/*!
		\since Visindigo 0.17.0

		移除并销毁一条对话。id 不存在时什么也不做。

		这是销毁对话的正确方式；直接 \c delete 会让注册表留下悬空指针。
	*/
	void Center::removeDialog(const QString& id) {
		auto it = d->Dialogs.find(id);
		if (it != d->Dialogs.end()) {
			Dialog* dialog = it.value();
			d->Dialogs.erase(it);
			delete dialog;
		}
	}

	/*!
		\since Visindigo 0.17.0

		按 id 返回对话。不存在时返回 \c nullptr。

		\note 返回的是借用指针，所有权仍在 Center。
	*/
	Dialog* Center::getDialog(const QString& id) const {
		return d->Dialogs.value(id, nullptr);
	}

	/*!
		\since Visindigo 0.17.0

		返回全部对话 id。
	*/
	QStringList Center::getDialogIds() const {
		return d->Dialogs.keys();
	}

	/*!
		\since Visindigo 0.17.0

		以现有对话为模板建立一条新对话，返回新对话的指针；原对话保留。

		新对话的 \l Dialog::getBranchFromID() 指向原对话。两条对话各自独立演化，
		互不影响。

		\a dialogId 不存在时返回 \c nullptr。
	*/
	Dialog* Center::cloneDialog(const QString& dialogId) {
		Dialog* source = getDialog(dialogId);
		if (source == nullptr) {
			return nullptr;
		}
		Dialog* target = createDialog();
		source->copyTo(target);
		target->setBranchFromID(source->getId());
		return target;
	}

	/*!
		\since Visindigo 0.17.0

		重新生成最后一条回答：克隆到"最后一条助手消息之前"，然后立刻执行。

		结果是一条新对话，它不是"修改了原对话"，而是取代了原对话——原对话连同
		那次被否决的回答一起留在注册表里，随时可以翻回去看。分支关系记录在新对话
		的 \l Dialog::getBranchFromID() 上，因此不需要额外的版本列表。

		\a dialogId 不存在时返回 \c nullptr。原对话没有助手消息时，等同于一次
		普通的重新执行。
	*/
	Dialog* Center::regenerate(const QString& dialogId) {
		Dialog* source = getDialog(dialogId);
		if (source == nullptr) {
			return nullptr;
		}
		Dialog* target = createDialog();
		source->copyTo(target);
		target->setBranchFromID(source->getId());
		const qint32 lastAssistant = target->findLastAssistantMessage();
		if (lastAssistant >= 0) {
			target->truncateTo(lastAssistant);
		}
		target->run();
		return target;
	}

	/*!
		\since Visindigo 0.17.0

		序列化整个注册表：模型池、服务商、技能、工具服务器、提示模板、默认服务商
		以及全部对话。

		\warning 产物中含有模型凭据，见 \l Model::setToken() 的警告。
	*/
	Visindigo::Utility::JsonConfig Center::toJson() const {
		Visindigo::Utility::JsonConfig config;
		QList<Visindigo::Utility::JsonConfig> models;
		for (const Model& model : d->Models) {
			models.append(model.toJson());
		}
		config.setArray("models", models);
		QList<Visindigo::Utility::JsonConfig> providers;
		for (const Provider& provider : d->Providers) {
			providers.append(provider.toJson());
		}
		config.setArray("providers", providers);
		QList<Visindigo::Utility::JsonConfig> skills;
		for (const Skill& skill : d->Skills) {
			skills.append(skill.toJson());
		}
		config.setArray("skills", skills);
		QList<Visindigo::Utility::JsonConfig> servers;
		for (const MCP& server : d->MCPs) {
			servers.append(server.toJson());
		}
		config.setArray("mcps", servers);
		QList<Visindigo::Utility::JsonConfig> prompts;
		for (const Prompt& prompt : d->Prompts) {
			prompts.append(prompt.toJson());
		}
		config.setArray("prompts", prompts);
		config.setString("defaultProviderId", d->DefaultProviderId);
		QList<Visindigo::Utility::JsonConfig> dialogs;
		for (const Dialog* dialog : d->Dialogs) {
			dialogs.append(dialog->toJson());
		}
		config.setArray("dialogs", dialogs);
		return config;
	}

	/*!
		\since Visindigo 0.17.0

		用存档整体替换当前注册表，返回是否成功处理。

		\note 这是替换而不是合并：已经存在的对话会被销毁。合并两份存档看起来更
		友好，但同名项该保留谁的、对话 id 撞了该听谁的，都无法给出一个不需要
		调用方补充规则的回答，因此不如让调用方自己决定怎么拼。
	*/
	bool Center::fromJson(const Visindigo::Utility::JsonConfig& json) {
		if (json.isEmpty()) {
			return false;
		}
		d->Models.clear();
		for (const Visindigo::Utility::JsonConfig& entry : json.getArray("models")) {
			Model model;
			model.fromJson(entry);
			addModel(model);
		}
		d->Providers.clear();
		for (const Visindigo::Utility::JsonConfig& entry : json.getArray("providers")) {
			Provider provider;
			provider.fromJson(entry);
			addProvider(provider);
		}
		d->Skills.clear();
		for (const Visindigo::Utility::JsonConfig& entry : json.getArray("skills")) {
			Skill skill;
			skill.fromJson(entry);
			addSkill(skill);
		}
		d->MCPs.clear();
		for (const Visindigo::Utility::JsonConfig& entry : json.getArray("mcps")) {
			MCP server;
			server.fromJson(entry);
			addMCP(server);
		}
		d->Prompts.clear();
		for (const Visindigo::Utility::JsonConfig& entry : json.getArray("prompts")) {
			Prompt prompt;
			prompt.fromJson(entry);
			addPrompt(prompt);
		}
		d->DefaultProviderId = json.getString("defaultProviderId");
		const QList<Dialog*> oldDialogs = d->Dialogs.values();
		d->Dialogs.clear();
		for (Dialog* dialog : oldDialogs) {
			delete dialog;
		}
		for (const Visindigo::Utility::JsonConfig& entry : json.getArray("dialogs")) {
			restoreDialog(entry);
		}
		return true;
	}

	Center::Center() : QObject() {
		d = new CenterPrivate();
	}

	Center::~Center() {
		const QList<Dialog*> dialogs = d->Dialogs.values();
		d->Dialogs.clear();
		for (Dialog* dialog : dialogs) {
			delete dialog;
		}
		const QList<Function*> functions = d->Functions.values();
		d->Functions.clear();
		for (Function* function : functions) {
			delete function;
		}
		delete d;
	}
}
