/*
	Visindigo Project Full AI Generated Declaration

	1. This file was entirely generated by AI. There was almost no human
	   involvement in the design of its API and implementation.
	2. Provided that the usage characteristics of the program corresponding
	   to this code are not substantially changed, anyone is free to make
	   fundamental modifications to this code.
	3. This code does not guarantee implementation consistency across
	   generations; it only guarantees that the corresponding program
	   features remain basically stable.
*/
#include <QtCore/qmap.h>
#include <QtCore/qstring.h>
#include <QtCore/qstringlist.h>
#include <QtCore/qurl.h>
#include "Agent/MCP.h"
#include "Agent/private/MCP_p.h"
#include "Utility/JsonConfig.h"

namespace Visindigo::Agent {
	/*!
		\class Visindigo::Agent::MCP
		\inheaderfile Agent/MCP.h
		\since Visindigo 0.17.0
		\inmodule Visindigo
		\brief 一个外部工具服务器的连接描述。

		MCP 保存"如何连上某个工具服务器"，包含传输方式、地址或可执行文件、以及
		环境变量与请求头。服务器自身提供的工具会在连接后由 Visindigo 转换成
		\l Function，从而和本地函数走同一套调用路径。

		\note 本版本只实现配置的保存与读取，尚未建立实际连接。字段的含义已经按
		约定固定下来，补齐传输层时不需要改动现有的配置格式。
	*/

	/*!
		\enum Visindigo::Agent::MCP::Transport
		\since Visindigo 0.17.0

		传输方式。

		\value Stdio 以子进程方式启动本地服务器，通过标准输入输出交换按行分隔的
			JSON-RPC 消息。适用于随程序分发的本地工具。
		\value Sse 通过 Server-Sent Events 接收服务端推送，请求走普通的 HTTP POST。
			这是较早的远程传输方式。
		\value StreamableHttp 在单个 HTTP 端点上完成全部收发，服务端可以按需返回
			普通 JSON 或事件流。这是较新的远程传输方式，优先选它。
	*/

	/*!
		\since Visindigo 0.17.0

		构造一个空配置，默认使用 \l Transport::Stdio。
	*/
	MCP::MCP() {
		d = new MCPPrivate();
	}

	/*!
		\since Visindigo 0.17.0

		以名称构造配置，\a name 同时作为索引键。
	*/
	MCP::MCP(const QString& name) {
		d = new MCPPrivate();
		d->Name = name;
	}

	VICopyable_Impl(MCP);
	VIMoveable_Impl(MCP);

	/*!
		\since Visindigo 0.17.0
	*/
	MCP::~MCP() {
		delete d;
	}

	/*!
		\since Visindigo 0.17.0

		设置名称。名称是配置在 Center 与 Dialog 中的索引键，同名会互相覆盖。
	*/
	MCP& MCP::setName(const QString& name) {
		d->Name = name;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		设置传输方式。

		\note 切换传输方式不会清空另一种方式专用的字段（例如从 \l Transport::Stdio
		换成 \l Transport::Sse 后，原有的 command 仍然留着）。这样在两种配置之间
		来回切换时不必重新填写，代价是序列化结果里会同时出现两种字段。
	*/
	MCP& MCP::setTransport(Transport transport) {
		d->TransportKind = transport;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		设置远程服务器的地址。仅对 \l Transport::Sse 与 \l Transport::StreamableHttp 有意义。
	*/
	MCP& MCP::setUrl(const QUrl& url) {
		d->Url = url;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		设置要启动的可执行文件。仅对 \l Transport::Stdio 有意义。

		\warning 该字段会在启动服务器时被当作程序路径直接执行。它只应来自用户
		自己的配置文件，不应该来自网络内容或项目文件，否则等同于开放任意代码执行。
	*/
	MCP& MCP::setCommand(const QString& command) {
		d->Command = command;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		设置启动参数，逐项传递、不经过 shell，因此路径中的空格无需自行转义。
	*/
	MCP& MCP::setArguments(const QStringList& arguments) {
		d->Arguments = arguments;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		设置追加到子进程的环境变量。是追加而不是替换：未列出的变量继承当前进程，
		因此不需要为启动一个工具而拼出一份完整的 PATH。
	*/
	MCP& MCP::setEnvironment(const QMap<QString, QString>& environment) {
		d->Environment = environment;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		设置远程请求的附加头，常用于携带鉴权信息。
	*/
	MCP& MCP::setHeaders(const QMap<QString, QString>& headers) {
		d->Headers = headers;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		设置是否启用，默认启用。被禁用的配置不会参与连接。
	*/
	MCP& MCP::setEnabled(bool enabled) {
		d->Enabled = enabled;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		设置是否在应用启动时自动连接，默认开启。

		\warning \l Transport::Stdio 的自动启动意味着每次开程序都会拉起一批子进程。
		如果服务器启动缓慢或会常驻，应关掉它改为按需连接。
	*/
	MCP& MCP::setAutoStart(bool autoStart) {
		d->AutoStart = autoStart;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		返回名称。
	*/
	QString MCP::getName() const {
		return d->Name;
	}

	/*!
		\since Visindigo 0.17.0

		返回传输方式。
	*/
	MCP::Transport MCP::getTransport() const {
		return d->TransportKind;
	}

	/*!
		\since Visindigo 0.17.0

		返回远程服务器地址。
	*/
	QUrl MCP::getUrl() const {
		return d->Url;
	}

	/*!
		\since Visindigo 0.17.0

		返回要启动的可执行文件。
	*/
	QString MCP::getCommand() const {
		return d->Command;
	}

	/*!
		\since Visindigo 0.17.0

		返回启动参数。
	*/
	QStringList MCP::getArguments() const {
		return d->Arguments;
	}

	/*!
		\since Visindigo 0.17.0

		返回追加的环境变量。
	*/
	QMap<QString, QString> MCP::getEnvironment() const {
		return d->Environment;
	}

	/*!
		\since Visindigo 0.17.0

		返回远程请求的附加头。
	*/
	QMap<QString, QString> MCP::getHeaders() const {
		return d->Headers;
	}

	/*!
		\since Visindigo 0.17.0

		返回是否启用。
	*/
	bool MCP::isEnabled() const {
		return d->Enabled;
	}

	/*!
		\since Visindigo 0.17.0

		返回是否自动连接。
	*/
	bool MCP::isAutoStart() const {
		return d->AutoStart;
	}

	/*!
		\since Visindigo 0.17.0

		判断配置是否足够建立一次连接：名称非空，且按传输方式提供了必需的目标
		（\l Transport::Stdio 需要可执行文件，其余需要合法的绝对 URL）。
	*/
	bool MCP::isValid() const {
		if (d->Name.isEmpty()) {
			return false;
		}
		if (d->TransportKind == Transport::Stdio) {
			return not d->Command.isEmpty();
		}
		return d->Url.isValid() and not d->Url.scheme().isEmpty();
	}

	/*!
		\since Visindigo 0.17.0

		序列化为 JSON 对象。
	*/
	Visindigo::Utility::JsonConfig MCP::toJson() const {
		Visindigo::Utility::JsonConfig config;
		config.setString("name", d->Name);
		config.setString("transport", d->TransportKind == Transport::Stdio ? "stdio"
			: (d->TransportKind == Transport::Sse ? "sse" : "streamableHttp"));
		config.setString("url", d->Url.toString());
		config.setString("command", d->Command);
		config.setStringList("arguments", d->Arguments);
		Visindigo::Utility::JsonConfig environment;
		for (auto it = d->Environment.constBegin(); it != d->Environment.constEnd(); ++it) {
			environment.setString(it.key(), it.value());
		}
		config.setObject("environment", environment);
		Visindigo::Utility::JsonConfig headers;
		for (auto it = d->Headers.constBegin(); it != d->Headers.constEnd(); ++it) {
			headers.setString(it.key(), it.value());
		}
		config.setObject("headers", headers);
		config.setBool("enabled", d->Enabled);
		config.setBool("autoStart", d->AutoStart);
		return config;
	}

	/*!
		\since Visindigo 0.17.0

		从 JSON 对象恢复。返回恢复后配置是否有效。

		未知的 \c transport 取值按 \l Transport::Stdio 处理，同时保留 \c command 与
		\c url 两个字段，因此配置文件里多写的字段不会造成信息丢失。
	*/
	bool MCP::fromJson(const Visindigo::Utility::JsonConfig& json) {
		d->Name = json.getString("name");
		const QString transport = json.getString("transport");
		if (transport.compare("sse", Qt::CaseInsensitive) == 0) {
			d->TransportKind = Transport::Sse;
		}
		else if (transport.compare("streamableHttp", Qt::CaseInsensitive) == 0) {
			d->TransportKind = Transport::StreamableHttp;
		}
		else {
			d->TransportKind = Transport::Stdio;
		}
		d->Url = QUrl(json.getString("url"));
		d->Command = json.getString("command");
		d->Arguments = json.getStringList("arguments");
		d->Environment.clear();
		const Visindigo::Utility::JsonConfig environment = json.getObject("environment");
		for (const QString& key : environment.keys()) {
			d->Environment.insert(key, environment.getString(key));
		}
		d->Headers.clear();
		const Visindigo::Utility::JsonConfig headers = json.getObject("headers");
		for (const QString& key : headers.keys()) {
			d->Headers.insert(key, headers.getString(key));
		}
		d->Enabled = json.contains("enabled") ? json.getBool("enabled") : true;
		d->AutoStart = json.contains("autoStart") ? json.getBool("autoStart") : true;
		return isValid();
	}
}
