/*
	Visindigo Project Full AI Generated Declaration

	1. This file was entirely generated by AI. There was almost no human
	   involvement in the design of its API and implementation.
	2. Provided that the usage characteristics of the program corresponding
	   to this code are not substantially changed, anyone is free to make
	   fundamental modifications to this code.
	3. This code does not guarantee implementation consistency across
	   generations; it only guarantees that the corresponding program
	   features remain basically stable.
*/
#include <QtCore/qmap.h>
#include <QtCore/qstring.h>
#include <QtCore/qstringlist.h>
#include <QtCore/qregularexpression.h>
#include "Agent/Dialog.h"
#include "Agent/Prompt.h"
#include "Agent/private/Prompt_p.h"
#include "Utility/JsonConfig.h"

namespace Visindigo::Agent {
	/*!
		\class Visindigo::Agent::Prompt
		\inheaderfile Agent/Prompt.h
		\since Visindigo 0.17.0
		\inmodule Visindigo
		\brief 可复用的提示模板。

		Prompt 是一段带有待填占位符的文本。占位符由双花括号包裹变量名构成，例如：

		\code
			把下面这段文字翻译成{{language}}，只输出译文：
			{{text}}
		\endcode

		调用 \l render() 时传入同名变量即可得到填好的 \l Message。把常用的提问
		方式固化成模板，比每次重新打一遍更不容易漏掉约束条件。

		Prompt 与 \l Skill 的分工：Prompt 由用户在需要时显式插入对话，渲染结果
		是一条普通消息，因此它会留在会话记录里；Skill 是常驻的系统提示片段，
		不产生消息。前者用于"这次我想按这个格式问"，后者用于"这个助手一贯如此"。
	*/

	/*!
		\since Visindigo 0.17.0

		构造一个空模板。
	*/
	Prompt::Prompt() {
		d = new PromptPrivate();
	}

	/*!
		\since Visindigo 0.17.0

		以名称与正文构造模板。\a name 同时作为索引键。
	*/
	Prompt::Prompt(const QString& name, const QString& content) {
		d = new PromptPrivate();
		d->Name = name;
		d->Content = content;
	}

	VICopyable_Impl(Prompt);
	VIMoveable_Impl(Prompt);

	/*!
		\since Visindigo 0.17.0
	*/
	Prompt::~Prompt() {
		delete d;
	}

	/*!
		\since Visindigo 0.17.0

		设置名称。名称是模板在 Center 与 Dialog 中的索引键，\l appendPrompt()
		也通过它查找模板。
	*/
	Prompt& Prompt::setName(const QString& name) {
		d->Name = name;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		设置描述，用于在模板列表里说明用途。
	*/
	Prompt& Prompt::setDescription(const QString& description) {
		d->Description = description;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		设置模板正文。其中的双花括号占位符会被 \l getVariables() 与 \l render() 识别。
	*/
	Prompt& Prompt::setContent(const QString& content) {
		d->Content = content;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		设置标签，供调用方分类。Visindigo 不解释标签的含义。
	*/
	Prompt& Prompt::setTags(const QStringList& tags) {
		d->Tags = tags;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		返回名称。
	*/
	QString Prompt::getName() const {
		return d->Name;
	}

	/*!
		\since Visindigo 0.17.0

		返回描述。
	*/
	QString Prompt::getDescription() const {
		return d->Description;
	}

	/*!
		\since Visindigo 0.17.0

		返回模板正文，占位符保持原样。
	*/
	QString Prompt::getContent() const {
		return d->Content;
	}

	/*!
		\since Visindigo 0.17.0

		返回标签列表。
	*/
	QStringList Prompt::getTags() const {
		return d->Tags;
	}

	/*!
		\since Visindigo 0.17.0

		扫描模板正文，返回其中出现的全部占位符名称。

		重复出现的同名占位符只返回一次；返回顺序为首次出现的位置。
	*/
	QStringList Prompt::getVariables() const {
		QStringList variables;
		static const QRegularExpression pattern(QStringLiteral("\\{\\{\\s*([A-Za-z0-9_\\.\\-]+)\\s*\\}\\}"));
		QRegularExpressionMatchIterator it = pattern.globalMatch(d->Content);
		while (it.hasNext()) {
			const QString name = it.next().captured(1);
			if (not variables.contains(name)) {
				variables.append(name);
			}
		}
		return variables;
	}

	/*!
		\since Visindigo 0.17.0

		判断模板是否可用：名称与正文都不能为空。
	*/
	bool Prompt::isValid() const {
		return not d->Name.isEmpty() and not d->Content.isEmpty();
	}

	/*!
		\since Visindigo 0.17.0

		用 \a variables 填充占位符，得到一条角色为 \l Message::Role::Prompt 的消息。

		\a variables 中未提供的占位符会原样留在结果里。这是刻意的：模板填了一半
		就发出去，模型多半会自行猜测缺失的内容，而把占位符摆在明面上至少
		能让人一眼看出哪儿漏了。

		\note 渲染结果的角色是 \l Message::Role::Prompt 而不是 \l Message::Role::User，
		以便在会话记录里区分"用户手打的"和"模板生成的"。发往服务端时两者都会被
		当作 \c user 角色。
	*/
	Message Prompt::render(const QMap<QString, QString>& variables) const {
		static const QRegularExpression pattern(QStringLiteral("\\{\\{\\s*([A-Za-z0-9_\\.\\-]+)\\s*\\}\\}"));
		QString content = d->Content;
		QList<QRegularExpressionMatch> matches;
		QRegularExpressionMatchIterator it = pattern.globalMatch(content);
		while (it.hasNext()) {
			matches.append(it.next());
		}
		// 从后往前替换，避免先前的替换改变后续匹配的偏移
		for (qsizetype i = matches.size() - 1; i >= 0; --i) {
			const QRegularExpressionMatch& match = matches[i];
			auto found = variables.constFind(match.captured(1));
			if (found != variables.constEnd()) {
				content.replace(match.capturedStart(), match.capturedLength(), found.value());
			}
		}
		Message message;
		message.setRole(Message::Role::Prompt);
		message.setContent(content);
		message.setName(d->Name);
		return message;
	}

	/*!
		\since Visindigo 0.17.0

		序列化为 JSON 对象。
	*/
	Visindigo::Utility::JsonConfig Prompt::toJson() const {
		Visindigo::Utility::JsonConfig config;
		config.setString("name", d->Name);
		config.setString("description", d->Description);
		config.setString("content", d->Content);
		config.setStringList("tags", d->Tags);
		return config;
	}

	/*!
		\since Visindigo 0.17.0

		从 JSON 对象恢复。返回恢复后模板是否有效。
	*/
	bool Prompt::fromJson(const Visindigo::Utility::JsonConfig& json) {
		d->Name = json.getString("name");
		d->Description = json.getString("description");
		d->Content = json.getString("content");
		d->Tags = json.getStringList("tags");
		return isValid();
	}
}
