/*
	Visindigo Project Full AI Generated Declaration

	1. This file was entirely generated by AI. There was almost no human
	   involvement in the design of its API and implementation.
	2. Provided that the usage characteristics of the program corresponding
	   to this code are not substantially changed, anyone is free to make
	   fundamental modifications to this code.
	3. This code does not guarantee implementation consistency across
	   generations; it only guarantees that the corresponding program
	   features remain basically stable.
*/
#include <algorithm>
#include <QtCore/qlist.h>
#include <QtCore/qmap.h>
#include <QtCore/qpair.h>
#include <QtCore/qstring.h>
#include <QtCore/qstringlist.h>
#include <QtCore/quuid.h>
#include "Agent/Center.h"
#include "Agent/Model.h"
#include "Agent/Provider.h"
#include "Agent/private/Provider_p.h"
#include "Utility/JsonConfig.h"

namespace Visindigo::Agent {
	/*!
		\class Visindigo::Agent::Provider
		\inheaderfile Agent/Provider.h
		\since Visindigo 0.17.0
		\inmodule Visindigo
		\brief 一组模型的集合，用于在实际执行时挑选一个可用的模型。

		Provider 回答的是"该用哪个模型"：它按优先级持有一批模型 id，并提供
		\l pickFirst() / \l pickNext() 两个挑选入口。前者用于正常发起一次对话，
		后者用于某个模型失败或额度耗尽时换一个继续。

		Provider 只保存模型 id，不保存 \l Model 本身。这样做的直接好处是
		\l toJson() 的产物里不含任何凭据——服务商列表可以随手贴给别人看，
		而共享同一批模型的多个 Provider 也不会各自持有一份 token 副本。

		Provider 自身也用 UUID 作索引，注册在 Visindigo::Agent::Center 中。
	*/

	/*!
		\since Visindigo 0.17.0

		构造一个空 Provider，并立即分配一个新的 UUID。
	*/
	Provider::Provider() {
		d = new ProviderPrivate();
		d->Id = QUuid::createUuid().toString(QUuid::WithoutBraces);
	}

	/*!
		\since Visindigo 0.17.0

		以名称构造空 Provider。名称仅用于展示，索引仍走 id。
	*/
	Provider::Provider(const QString& name) {
		d = new ProviderPrivate();
		d->Id = QUuid::createUuid().toString(QUuid::WithoutBraces);
		d->Name = name;
	}

	VICopyable_Impl(Provider);
	VIMoveable_Impl(Provider);

	/*!
		\since Visindigo 0.17.0
	*/
	Provider::~Provider() {
		delete d;
	}

	/*!
		\since Visindigo 0.17.0

		设置供展示的名称，例如服务商名。
	*/
	Provider& Provider::setName(const QString& name) {
		d->Name = name;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		加入一个模型 id，并指定其优先级。优先级越大越先被 \l pickFirst() 选中，
		默认 \c 0。

		重复加入同一个 id 会覆盖其优先级，而不是产生第二个条目。

		\note 这里不检查 \a modelId 是否已在 Center 的模型池中存在。允许先建
		Provider 后补模型，可以让配置的读取顺序不受限制；代价是写错 id 时
		只会在挑选阶段表现为"挑不到模型"。
	*/
	Provider& Provider::addModel(const QString& modelId, qint32 priority) {
		if (not modelId.isEmpty()) {
			d->ModelPriorities.insert(modelId, priority);
		}
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		移除一个模型 id。id 不存在时什么也不做。
	*/
	Provider& Provider::removeModel(const QString& modelId) {
		d->ModelPriorities.remove(modelId);
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		清空全部模型。
	*/
	Provider& Provider::clearModels() {
		d->ModelPriorities.clear();
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		返回唯一标识。
	*/
	QString Provider::getId() const {
		return d->Id;
	}

	/*!
		\since Visindigo 0.17.0

		返回展示名称。
	*/
	QString Provider::getName() const {
		return d->Name;
	}

	/*!
		\since Visindigo 0.17.0

		返回全部模型 id。

		\note 返回顺序是 id 的字典序，不是优先级顺序。需要按优先级遍历请使用
		\l pickFirst() 与 \l pickNext()。
	*/
	QStringList Provider::getModelIds() const {
		return d->ModelPriorities.keys();
	}

	/*!
		\since Visindigo 0.17.0

		返回指定模型的优先级；该 id 不在本 Provider 中时返回 \c 0。
	*/
	qint32 Provider::getModelPriority(const QString& modelId) const {
		return d->ModelPriorities.value(modelId, 0);
	}

	/*!
		\since Visindigo 0.17.0

		按优先级从高到低挑选第一个满足 \a required 的模型，返回其 id。

		优先级相同时按 id 字典序决定先后，因此挑选结果与插入顺序无关，也不随
		底层容器的遍历顺序变化——同一份配置在任意一次运行里都会挑出同一个模型。

		满足条件指的是：该 id 能在 Center 的模型池里找到、该模型 \l Model::isValid()
		为真、并且它的能力位包含 \a required 的全部位。传入 \l Model::Capability::None
		表示只要求模型可用。

		挑不到时返回空串；调用方应当据此放弃本次请求，而不是退回默认模型硬发。
	*/
	QString Provider::pickFirst(Model::Capabilities required) const {
		QList<QPair<QString, qint32>> ordered;
		ordered.reserve(d->ModelPriorities.size());
		for (auto it = d->ModelPriorities.constBegin(); it != d->ModelPriorities.constEnd(); ++it) {
			ordered.append(qMakePair(it.key(), it.value()));
		}
		std::sort(ordered.begin(), ordered.end(), [](const QPair<QString, qint32>& left, const QPair<QString, qint32>& right) {
			if (left.second != right.second) {
				return left.second > right.second;
			}
			return left.first < right.first;
		});
		Center* center = Center::getInstance();
		for (const QPair<QString, qint32>& entry : ordered) {
			const Model model = center->getModel(entry.first);
			if (not model.isValid()) {
				continue;
			}
			if (required == Model::Capability::None) {
				return entry.first;
			}
			if ((model.getCapabilities() & required) == required) {
				return entry.first;
			}
		}
		return QString();
	}

	/*!
		\since Visindigo 0.17.0

		在 \l pickFirst() 的挑选顺序里，返回 \a afterModelId 之后第一个满足
		\a required 的模型 id。

		这是"降级重试"的入口：当前模型超时或被限流时换下一个继续，而不是直接
		把失败抛给用户。\a afterModelId 不在本 Provider 中时，等价于 \l pickFirst()。

		\note 它不会回绕到序列开头。若 \a afterModelId 已是最后一个候选，返回空串；
		调用方需要自行判断要不要从头再来一次，而不是让本函数悄悄循环——那样在
		所有模型都不可用时就会变成死循环。
	*/
	QString Provider::pickNext(const QString& afterModelId, Model::Capabilities required) const {
		QList<QPair<QString, qint32>> ordered;
		ordered.reserve(d->ModelPriorities.size());
		for (auto it = d->ModelPriorities.constBegin(); it != d->ModelPriorities.constEnd(); ++it) {
			ordered.append(qMakePair(it.key(), it.value()));
		}
		std::sort(ordered.begin(), ordered.end(), [](const QPair<QString, qint32>& left, const QPair<QString, qint32>& right) {
			if (left.second != right.second) {
				return left.second > right.second;
			}
			return left.first < right.first;
		});
		Center* center = Center::getInstance();
		bool afterSeen = afterModelId.isEmpty();
		for (const QPair<QString, qint32>& entry : ordered) {
			if (not afterSeen) {
				if (entry.first == afterModelId) {
					afterSeen = true;
				}
				continue;
			}
			const Model model = center->getModel(entry.first);
			if (not model.isValid()) {
				continue;
			}
			if (required == Model::Capability::None) {
				return entry.first;
			}
			if ((model.getCapabilities() & required) == required) {
				return entry.first;
			}
		}
		return QString();
	}

	/*!
		\since Visindigo 0.17.0

		判断 Provider 是否至少持有一个模型 id。

		\note 它不检查这些 id 是否真的能在模型池里解析出来——那需要查询 Center，
		而本函数在 Provider 的拷贝上也会被调用。
	*/
	bool Provider::isValid() const {
		return not d->ModelPriorities.isEmpty();
	}

	/*!
		\since Visindigo 0.17.0

		序列化为 JSON 对象，形态为 \c {"id": "...", "name": "...", "models": [{"id": "...", "priority": 0}]}。

		产物里只有 id，不含地址与凭据，因此可以安全地写进项目文件或随日志附上。
	*/
	Visindigo::Utility::JsonConfig Provider::toJson() const {
		Visindigo::Utility::JsonConfig config;
		config.setString("id", d->Id);
		config.setString("name", d->Name);
		QList<Visindigo::Utility::JsonConfig> models;
		for (auto it = d->ModelPriorities.constBegin(); it != d->ModelPriorities.constEnd(); ++it) {
			Visindigo::Utility::JsonConfig entry;
			entry.setString("id", it.key());
			entry.setInt("priority", it.value());
			models.append(entry);
		}
		config.setArray("models", models);
		return config;
	}

	/*!
		\since Visindigo 0.17.0

		从 JSON 对象恢复。返回是否恢复了 id。

		存档里带有 id 时会一并恢复；没有 id 字段时保留当前（新生成的）id，
		因而可以把手写的服务商片段直接读进来。

		\note 恢复只影响 id 与优先级，模型本身仍由 Center 的模型池提供。若模型池
		里没有对应 id，该候选项会在挑选阶段被跳过，而不是在这里报错。
	*/
	bool Provider::fromJson(const Visindigo::Utility::JsonConfig& json) {
		bool ok = false;
		const QString id = json.getString("id", &ok);
		if (ok and not id.isEmpty()) {
			d->Id = id;
		}
		d->Name = json.getString("name");
		d->ModelPriorities.clear();
		const QList<Visindigo::Utility::JsonConfig> models = json.getArray("models");
		for (const Visindigo::Utility::JsonConfig& entry : models) {
			const QString modelId = entry.getString("id");
			if (not modelId.isEmpty()) {
				d->ModelPriorities.insert(modelId, static_cast<qint32>(entry.getInt("priority")));
			}
		}
		return ok and not id.isEmpty();
	}
}
