/*
	Visindigo Project Full AI Generated Declaration

	1. This file was entirely generated by AI. There was almost no human
	   involvement in the design of its API and implementation.
	2. Provided that the usage characteristics of the program corresponding
	   to this code are not substantially changed, anyone is free to make
	   fundamental modifications to this code.
	3. This code does not guarantee implementation consistency across
	   generations; it only guarantees that the corresponding program
	   features remain basically stable.
*/
#include <QtCore/qstring.h>
#include <QtCore/qstringlist.h>
#include "Agent/Skill.h"
#include "Agent/private/Skill_p.h"
#include "Utility/JsonConfig.h"

namespace Visindigo::Agent {
	/*!
		\class Visindigo::Agent::Skill
		\inheaderfile Agent/Skill.h
		\since Visindigo 0.17.0
		\inmodule Visindigo
		\brief 一段可复用的行为说明，用于给对话注入领域知识。

		一个 Skill 就是"当用户提出这类问题时应遵守的规则"的载体：它由一段说明
		文本（\l setInstruction()）加上若干可选的能力声明组成，在构造请求时被
		拼进系统提示。

		它和 \l Prompt 的区别在于谁决定内容：Prompt 由用户显式触发，模板里有
		变量占位符，渲染出的是对话中的某一条消息；Skill 是常驻的，只要被挂上且
		处于启用状态，就会一直参与系统提示的拼装，不需要用户逐次点名。

		Skill 本身不持有任何可执行对象。它记录的是函数 id，而不是函数指针，
		因为同一份 Skill 可能被多份对话共享，而函数的所有权属于 Center 或
		某个具体的 Dialog；把指针存进值类型里，拷贝时所有权就说不清了。
	*/

	/*!
		\since Visindigo 0.17.0

		构造一个空技能。空技能 \l isValid() 为 \c false，需要至少设置名称与说明。
	*/
	Skill::Skill() {
		d = new SkillPrivate();
	}

	/*!
		\since Visindigo 0.17.0

		以名称构造技能，\a name 同时作为索引键。
	*/
	Skill::Skill(const QString& name) {
		d = new SkillPrivate();
		d->Name = name;
	}

	VICopyable_Impl(Skill);
	VIMoveable_Impl(Skill);

	/*!
		\since Visindigo 0.17.0
	*/
	Skill::~Skill() {
		delete d;
	}

	/*!
		\since Visindigo 0.17.0

		设置名称。名称是 Skill 在 Center 与 Dialog 中的索引键，同名会互相覆盖。
	*/
	Skill& Skill::setName(const QString& name) {
		d->Name = name;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		设置一句话描述，用于在界面或日志里说明这个技能是做什么的。

		\note 描述不会进入系统提示；进入提示的是 \l setInstruction() 的内容。
	*/
	Skill& Skill::setDescription(const QString& description) {
		d->Description = description;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		设置技能的正文，也就是真正被拼进系统提示的规则文本。

		写成祈使句比写成陈述句有效得多：「回答前先确认单位」比「用户可能会省略
		单位」更容易被遵守。说明里也不适合放大段背景资料，那会稀释规则本身。
	*/
	Skill& Skill::setInstruction(const QString& instruction) {
		d->Instruction = instruction;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		设置是否启用，默认启用。被禁用的技能不会参与系统提示拼装。
	*/
	Skill& Skill::setEnabled(bool enabled) {
		d->Enabled = enabled;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		设置标签，供调用方按主题批量筛选技能。Visindigo 不解释标签的含义。
	*/
	Skill& Skill::setTags(const QStringList& tags) {
		d->Tags = tags;
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		关联一个函数 id，表示"这个技能用到的工具"。重复添加同一个 id 不会产生重复项。

		\a functionId 由 \l Visindigo::Agent::Function::getId() 定义，实际对象在
		执行时由 Center 或 Dialog 的函数表解析。
	*/
	Skill& Skill::addFunction(const QString& functionId) {
		if (not functionId.isEmpty() and not d->FunctionIds.contains(functionId)) {
			d->FunctionIds.append(functionId);
		}
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		解除一个函数 id 的关联。id 不存在时什么也不做。
	*/
	Skill& Skill::removeFunction(const QString& id) {
		d->FunctionIds.removeAll(id);
		return *this;
	}

	/*!
		\since Visindigo 0.17.0

		判断是否关联了指定函数。
	*/
	bool Skill::hasFunction(const QString& id) const {
		return d->FunctionIds.contains(id);
	}

	/*!
		\since Visindigo 0.17.0

		返回关联的全部函数 id，按添加顺序。
	*/
	QStringList Skill::getFunctionIds() const {
		return d->FunctionIds;
	}

	/*!
		\since Visindigo 0.17.0

		返回名称。
	*/
	QString Skill::getName() const {
		return d->Name;
	}

	/*!
		\since Visindigo 0.17.0

		返回描述。
	*/
	QString Skill::getDescription() const {
		return d->Description;
	}

	/*!
		\since Visindigo 0.17.0

		返回技能正文。
	*/
	QString Skill::getInstruction() const {
		return d->Instruction;
	}

	/*!
		\since Visindigo 0.17.0

		返回是否启用。
	*/
	bool Skill::isEnabled() const {
		return d->Enabled;
	}

	/*!
		\since Visindigo 0.17.0

		返回标签列表。
	*/
	QStringList Skill::getTags() const {
		return d->Tags;
	}

	/*!
		\since Visindigo 0.17.0

		判断技能是否可用：名称与正文都不能为空。

		\note 只有名称没有正文的技能是无效的——它拼进系统提示后不产生任何内容，
		留着只会让配置看起来比实际更丰富。
	*/
	bool Skill::isValid() const {
		return not d->Name.isEmpty() and not d->Instruction.isEmpty();
	}

	/*!
		\since Visindigo 0.17.0

		序列化为 JSON 对象。
	*/
	Visindigo::Utility::JsonConfig Skill::toJson() const {
		Visindigo::Utility::JsonConfig config;
		config.setString("name", d->Name);
		config.setString("description", d->Description);
		config.setString("instruction", d->Instruction);
		config.setBool("enabled", d->Enabled);
		config.setStringList("tags", d->Tags);
		config.setStringList("functions", d->FunctionIds);
		return config;
	}

	/*!
		\since Visindigo 0.17.0

		从 JSON 对象恢复。返回恢复后技能是否有效。

		\note 缺失的字段保留默认值；\c enabled 缺失时按启用处理，这样手写的精简
		配置不必每次都写一遍开关。
	*/
	bool Skill::fromJson(const Visindigo::Utility::JsonConfig& json) {
		d->Name = json.getString("name");
		d->Description = json.getString("description");
		d->Instruction = json.getString("instruction");
		d->Enabled = json.contains("enabled") ? json.getBool("enabled") : true;
		d->Tags = json.getStringList("tags");
		d->FunctionIds = json.getStringList("functions");
		return isValid();
	}
}
